Repository DFE-Digital/publish-teacher-training, pull requests merged in 2021-10, with the labels that each got.

#2163 Bump govuk-components to 2.1.1
  Gemfile.lock
  app/components/notification_banner/view.rb
  app/components/persona/view.rb
  app/views/layouts/provider_record.html.erb
  app/views/support/providers/show.html.erb
Labels: deploy

#2206 [2261] Stop logging bigquery
  app/jobs/send_event_to_big_query_job.rb
  config/initializers/sidekiq.rb
Labels: Devops

#2209 [164] [dry run] Updated recruitment cycle to 2022 on staging settings
  config/routes.rb
  config/settings.yml
  config/settings/production.yml
  spec/config/settings_spec.rb
  spec/controllers/api/public/v1/courses_controller_spec.rb
  spec/controllers/api/v2/courses_controller_spec.rb
  spec/factories/course_enrichments.rb
  spec/models/course/publishable_spec.rb
  spec/models/course_spec.rb
  spec/models/recruitment_cycle_spec.rb
  spec/requests/api/v2/build_new_course_spec.rb
  spec/requests/api/v2/providers/courses/publish_spec.rb
  spec/requests/api/v2/providers/courses/publishable_spec.rb
  spec/requests/api/v2/providers/courses/update_gcse_requirements_spec.rb
  spec/requests/api/v3/courses/index_spec.rb
Labels: do not merge
