Repository DFE-Digital/publish-teacher-training, pull requests merged in 2021-07, with the labels that each got.

#1786 Wait for review app deployment to finish
  .github/workflows/build.yml
Labels: devops

#1803 Deploy review app only if labelled
  .github/workflows/build.yml
  .github/workflows/delete-review-app.yml
Labels: deploy, devops

#1768 Tidy up forms that use GOV.UK Form Builder
  app/views/contacts/edit.html.erb
  app/views/courses/_course_length.html.erb
  app/views/courses/_related_sidebar.html.erb
  app/views/courses/about.html.erb
  app/views/courses/age_range/_form_fields.html.erb
  app/views/courses/age_range/edit.html.erb
  app/views/courses/age_range/new.html.erb
  app/views/courses/confirmation.html.erb
  app/views/courses/delete.html.erb
  app/views/courses/fees.html.erb
  app/views/courses/requirements.html.erb
  app/views/courses/salary.html.erb
  app/views/courses/sites/edit.html.erb
  app/views/courses/subjects/new.erb
  app/views/courses/withdraw.html.erb
  app/views/pages/accept_terms.html.erb
  app/views/providers/allocations/check_your_information.html.erb
  app/views/providers/allocations/edit.html.erb
  app/views/providers/allocations/initial_request.html.erb
  app/views/providers/allocations/new_repeat_request.html.erb
  app/views/providers/allocations/number_of_places.html.erb
  app/views/providers/allocations/pick_a_provider.html.erb
  app/views/providers/edit_initial_allocations/check_answers.html.erb
  app/views/providers/edit_initial_allocations/do_you_want.html.erb
  app/views/providers/edit_initial_allocations/number_of_places.html.erb
  app/views/providers/visas/edit.html.erb
  app/views/sign_in/dfe_sign_in_is_down.html.erb
  config/locales/helpers.yml
Labels: deploy

#1796 [2145] Update Makefile
  .github/workflows/delete-review-app.yml
  .github/workflows/deploy.yml
  .gitignore
  Makefile
  terraform/terraform.tf
  terraform/variables.tf
Labels: deploy, devops

#1806 [2145] Enable automated deployment to production
  .github/workflows/deploy.yml
Labels: deploy, devops

#1805 Upgrade to ruby 2.7.4
  .github/workflows/smoke-test.yml
  .tool-versions
  Dockerfile
  Gemfile
Labels: deploy, devops

#1816 Remove Rollover Environment
  .github/workflows/build.yml
  .github/workflows/deploy.yml
  Makefile
  config/environments/rollover.rb
  config/settings/rollover.yml
  terraform/workspace_variables/app_config.yml
  terraform/workspace_variables/rollover.sh
  terraform/workspace_variables/rollover.tfvars
  terraform/workspace_variables/rollover_backend.tfvars
Labels: devops

#1822 [2301] Hide CSV export if there are no training providers
  app/views/providers/training_providers.html.erb
  spec/features/providers/training_providers_spec.rb
Labels: deploy

#1836 [XXX] Tidy up environment variables
  terraform/workspace_variables/app_config.yml
Labels: deploy
