Repository DFE-Digital/publish-teacher-training, pull requests merged in 2021-12, with the labels that each got.

#2310 Add additional Persona users
  app/components/persona/view.html.erb
  app/views/personas/index.html.erb
  spec/features/auth/persona_spec.rb
Labels: deploy

#2311 [xxxx] Fixed stolen lines
  app/views/support/allocations/show.html.erb
  app/views/support/providers/show.html.erb
Labels: deploy

#2307 [411] Course financial incentives scoped to first subject
  app/models/course.rb
  spec/models/course_spec.rb
Labels: do not merge

#2318 [376] Add to search via course code to Providers list on support
  app/components/providers/filters/view.html.erb
  app/components/providers/filters/view.rb
  app/controllers/api/public/v1/provider_suggestions_controller.rb
  app/controllers/api/v2/providers_controller.rb
  app/controllers/api/v3/provider_suggestions_controller.rb
  app/controllers/api/v3/providers_controller.rb
  app/controllers/support/providers_controller.rb
  app/models/course.rb
  app/models/provider.rb
  app/models/provider_filter.rb
  app/services/support/filter.rb
  app/views/support/providers/index.html.erb
  config/locales/en.yml
  spec/features/support/providers/providers_filter_spec.rb
  spec/models/course_spec.rb
  spec/models/provider_filter_spec.rb
  spec/models/provider_spec.rb
  spec/services/support/filters/filter_spec.rb
Labels: deploy

#2327 [0405] Review of error messages and summaries in Publish
  app/services/courses/validate_custom_age_range_service.rb
  config/locales/en.yml
  spec/requests/api/v2/access_request_spec.rb
  spec/requests/api/v2/providers/courses/create/age_range_in_years_spec.rb
  spec/requests/api/v2/providers/sites_spec.rb
  spec/services/courses/validate_custom_age_range_service_spec.rb
Labels: deploy

#2342 [485] Change pg search method
  app/controllers/api/public/v1/provider_suggestions_controller.rb
  app/controllers/api/v2/providers_controller.rb
  app/controllers/api/v3/provider_suggestions_controller.rb
  app/controllers/api/v3/providers_controller.rb
  app/models/provider.rb
  app/services/support/filter.rb
  spec/models/provider_spec.rb
  spec/services/support/filters/filter_spec.rb
Labels: deploy

#2322 Add About Your Organisation page
  .codeclimate.yml
  Gemfile
  Gemfile.lock
  app/controllers/application_controller.rb
  app/controllers/publish_interface/providers_controller.rb
  app/helpers/application_helper.rb
  app/helpers/provider_helper.rb
  app/helpers/view_helper.rb
  app/models/provider.rb
  app/models/recruitment_cycle.rb
  app/services/providers/visa_sponsorship_service.rb
  app/views/errors/not_found.html.erb
  app/views/publish_interface/providers/details.html.erb
  app/webpacker/styles/_status-box.scss
  app/webpacker/styles/_summary-list.scss
  app/webpacker/styles/application.scss
  config/routes.rb
  config/settings.yml
  spec/requests/api/v3/courses/index_spec.rb
Labels: deploy, publish/ttapi merge

#2337 [433] Allow support users to edit the details of a course
  app/controllers/support/courses_controller.rb
  app/views/support/courses/edit.html.erb
  app/views/support/courses/index.html.erb
  config/locales/en.yml
  spec/features/support/providers/courses/editing_a_course_spec.rb
  spec/features/support/providers/provider_courses_list_spec.rb
  spec/requests/api/v2/build_new_course_spec.rb
  spec/support/page_objects/sections/course.rb
  spec/support/page_objects/support/provider/course_edit_page.rb
Labels: deploy

#2344 Add custom error pages
  app/controllers/api_error_controller.rb
  app/controllers/application_controller.rb
  app/controllers/error_controller.rb
  app/controllers/errors_controller.rb
  app/controllers/publish_interface/providers_controller.rb
  app/helpers/provider_helper.rb
  app/views/errors/forbidden.html.erb
  app/views/errors/internal_server_error.html.erb
  app/views/layouts/publish_interface.html.erb
  app/views/layouts/support.html.erb
  config/application.rb
  config/locales/en.yml
  config/routes.rb
  spec/controllers/api_error_controller_spec.rb
Labels: deploy

#2345 [448] Rescue from discarded provider in support providers controller
  app/controllers/support/courses_controller.rb
  spec/features/support/providers/courses/viewing_providers_courses_spec.rb
Labels: deploy

#2340 Migrate Provider and Contact details from Old Publish
  app/controllers/application_controller.rb
  app/controllers/publish_interface/providers_controller.rb
  app/controllers/sessions_controller.rb
  app/forms/publish_interface/about_your_organisation_form.rb
  app/helpers/view_helper.rb
  app/models/provider.rb
  app/views/layouts/application.html.erb
  app/views/publish_interface/providers/about.html.erb
  app/views/publish_interface/providers/contact.html.erb
  app/views/publish_interface/providers/details.html.erb
  config/locales/en.yml
  config/routes.rb
  spec/features/publish_interface/edit_provider_details_spec.rb
  spec/support/feature_helpers/govuk_components.rb
  spec/support/feature_helpers/publish_interface_pages.rb
  spec/support/feature_helpers/support_pages.rb
  spec/support/features.rb
  spec/support/page_objects/publish_interface/provider_contact_details_edit.rb
  spec/support/page_objects/publish_interface/provider_details_edit.rb
  spec/support/page_objects/publish_interface/provider_details_show.rb
Labels: deploy

#2347 [447] Display and editing of ab/provider type in support UI
  app/components/providers/provider_list/view.html.erb
  app/components/providers/provider_list/view.rb
  app/controllers/support/providers_controller.rb
  app/views/support/providers/edit.html.erb
  app/views/support/providers/show.html.erb
  config/locales/en.yml
  spec/components/providers/view_preview.rb
  spec/components/providers/view_spec.rb
  spec/features/support/providers/editing_a_provider_spec.rb
  spec/support/page_objects/support/provider_edit.rb
  spec/support/page_objects/support/provider_show.rb
Labels: deploy

#2354 [481] Migrate visa sponsorships
  app/controllers/publish_interface/providers/visas_controller.rb
  app/forms/publish_interface/base_provider_form.rb
  app/forms/publish_interface/provider_visa_form.rb
  app/views/publish_interface/providers/details.html.erb
  app/views/publish_interface/providers/visas/edit.html.erb
  config/locales/en.yml
  config/routes.rb
  spec/features/publish_interface/editing_visa_sponsorships_spec.rb
  spec/forms/publish_interface/provider_visa_form_spec.rb
  spec/support/feature_helpers/publish_interface_pages.rb
  spec/support/page_objects/publish_interface/provider_visa_sponsorships.rb
Labels: deploy

#2362 [499] Add locations list to providers tab in support console
  app/controllers/support/locations_controller.rb
  app/views/layouts/provider_record.html.erb
  app/views/support/locations/index.html.erb
  config/locales/en.yml
  config/routes.rb
  spec/features/support/providers/courses/viewing_providers_courses_spec.rb
  spec/features/support/providers/locations/locations_list_spec.rb
  spec/support/feature_helpers/support_pages.rb
  spec/support/page_objects/sections/location.rb
  spec/support/page_objects/support/provider/locations_index_page.rb
Labels: deploy

#2371 [514] Allow locations to be edited
  app/controllers/support/courses_controller.rb
  app/controllers/support/locations_controller.rb
  app/controllers/support/providers_controller.rb
  app/views/support/allocation_uplifts/new.html.erb
  app/views/support/courses/edit.html.erb
  app/views/support/locations/edit.html.erb
  app/views/support/locations/index.html.erb
  app/views/support/providers/edit.html.erb
  config/locales/en.yml
  config/routes.rb
  spec/features/support/providers/locations/locations_list_spec.rb
  spec/features/support/providers/locations/managing_locations_spec.rb
  spec/support/feature_helpers/support_pages.rb
  spec/support/page_objects/sections/location.rb
  spec/support/page_objects/support/provider/location_edit_page.rb
Labels: deploy

#2372 [503] Allow locations to be deleted
  app/controllers/support/locations_controller.rb
  app/models/provider.rb
  app/models/site.rb
  app/views/support/locations/edit.html.erb
  config/locales/en.yml
  config/routes.rb
  db/migrate/20211231135038_add_discarded_at_to_site.rb
  db/migrate/20211231135738_update_uniq_index_on_site.rb
  db/schema.rb
  docs/database-diagram.jpg
  spec/features/support/providers/locations/managing_locations_spec.rb
  spec/models/provider_spec.rb
  spec/models/site_spec.rb
  spec/support/page_objects/support/provider/location_edit_page.rb
Labels: deploy
