Repository DFE-Digital/publish-teacher-training, pull requests merged in 2021-09, with the labels that each got.

#1851 Update content following a review
  app/components/degree_preview_component.html.erb
  app/components/degree_preview_component.rb
  app/components/gcse_requirements_component.rb
  app/components/gcse_row_content_component.html.erb
  app/decorators/course_decorator.rb
  spec/components/degree_preview_component_spec.rb
  spec/components/gcse_preview_component_spec.rb
  spec/components/gcse_row_content_component_spec.rb
  spec/features/courses/gcse_equivalency_spec.rb
Labels: deploy

#1884 [2647] Warning links now link to input box
  app/views/courses/_copy_content_warning.html.erb
Labels: deploy

#1718 Update govuk-components to v2
  Gemfile
  Gemfile.lock
  app/helpers/application_helper.rb
  app/helpers/breadcrumb_helper.rb
  app/helpers/view_helper.rb
  app/views/access_requests/_access_request.html.erb
  app/views/access_requests/inform_publisher.html.erb
  app/views/courses/_basic_details_tab.html.erb
  app/views/courses/_copy_content_warning.html.erb
  app/views/courses/_description_content.html.erb
  app/views/courses/_entry_requirements.html.erb
  app/views/courses/about.html.erb
  app/views/courses/confirmation.html.erb
  app/views/courses/delete.html.erb
  app/views/courses/index.html.erb
  app/views/courses/preview.html.erb
  app/views/courses/preview/_apply.html.erb
  app/views/courses/preview/qualification/_pgce.html.erb
  app/views/courses/preview/qualification/_pgce_with_qts.html.erb
  app/views/courses/preview/qualification/_pgde.html.erb
  app/views/courses/preview/qualification/_pgde_with_qts.html.erb
  app/views/courses/preview/qualification/_qts.html.erb
  app/views/courses/request_change.html.erb
  app/views/courses/subjects/_form_fields.html.erb
  app/views/courses/withdraw.html.erb
  app/views/layouts/_flash.html.erb
  app/views/layouts/_footer.html.erb
  app/views/layouts/_header.html.erb
  app/views/layouts/_phase_banner.html.erb
  app/views/pages/guidance.html.erb
  app/views/pages/notifications_info.html.erb
  app/views/pages/performance_dashboard.html.erb
  app/views/providers/_show_during_rollover.html.erb
  app/views/providers/allocations/_allocation_request_open_state.html.erb
  app/views/providers/allocations/check_your_information.html.erb
  app/views/providers/allocations/pick_a_provider.html.erb
  app/views/providers/allocations/requests/_yes_requested.html.erb
  app/views/providers/details.html.erb
  app/views/providers/edit_initial_allocations/check_answers.html.erb
  app/views/providers/users/index.html.erb
  app/views/sign_in/dfe_sign_in_is_down.html.erb
  app/views/sign_in/index.html.erb
  app/views/sites/index.html.erb
  app/views/ucas_contacts/_ucas_contact_list.html.erb
  app/views/ucas_contacts/show.html.erb
  app/webpacker/stylesheets/_summary-list.scss
  spec/features/courses/show_spec.rb
  spec/helpers/application_helper_spec.rb
  spec/helpers/view_helper_spec.rb
Labels: Components

#1895 [22] Degree subject requirements now has copy ability from other courses
  app/controllers/application_controller.rb
  app/controllers/concerns/course_fetcher.rb
  app/controllers/courses/degrees/base_controller.rb
  app/controllers/courses/degrees/subject_requirements_controller.rb
  app/controllers/courses/gcse_requirements_controller.rb
  app/controllers/courses_controller.rb
  app/services/courses/copy.rb
  app/services/courses/fetch.rb
  app/views/courses/_related_sidebar.html.erb
  app/views/courses/degrees/subject_requirements/edit.html.erb
  app/views/courses/gcse_requirements/edit.html.erb
  spec/features/courses/degree_spec.rb
  spec/features/courses/gcse_equivalency_spec.rb
Labels: deploy

#1925 [71] Duplicated notification fix
  app/views/layouts/_flash.html.erb
Labels: deploy

#1931 [127] Added Important banner with reminder to publish courses ahead of SoC
  app/views/courses/index.html.erb
  app/views/providers/show.html.erb
  app/views/recruitment_cycles/show.html.erb
  config/settings/review.yml
Labels: deploy

#1926 Content changes for allocations
  app/views/providers/allocations/_allocation_report_confirmed_state.html.erb
  app/views/providers/allocations/_allocation_request_confirmed_state.html.erb
  app/views/recruitment_cycles/_allocations.html.erb
  config/locales/en.yml
  config/settings.yml
  config/settings/review.yml
Labels: do not merge, deploy
