Repository DFE-Digital/publish-teacher-training, pull requests merged in 2021-03, with the labels that each got.

#1792 Add StatusCake check for cloudapps URL
  terraform/workspace_variables/production.tfvars
Labels: Devops

#1796 Alert slack channel on build failures
  .github/workflows/build.yml
Labels: Devops

#1795 Upload PaaS db_dump to Az storage_account
  .github/workflows/database-restore.yml
Labels: Devops

#1798 make console command
  Makefile
Labels: Devops

#1801 Update @channel alert in SLACK_MESSAGE
  .github/workflows/build.yml
  .github/workflows/deploy.yml
  .github/workflows/smoke-test.yml
Labels: Devops

#1802 Add SETTINGS__MAPIT_API_KEY variable for bg container
  azure/template.json
Labels: Devops

#1797 Removing workflow to restore db from Azure
  .github/workflows/restore-azure-db-to-paas.yml
Labels: Devops

#1804 Increase web app memory to 1GB
  terraform/workspace_variables/production.tfvars
Labels: Devops

#1805 Increase instance count for the web app
  terraform/workspace_variables/production.tfvars
Labels: Devops

#1810 Increase web app memory to 1.5 GB per instance
  terraform/workspace_variables/production.tfvars
Labels: Devops

#1811 Increase web app instance count to 2
  terraform/workspace_variables/qa.tfvars
  terraform/workspace_variables/staging.tfvars
Labels: Devops

#1830 Bump mimemagic to 0.3.6
  Gemfile.lock
Labels: dependencies

#1832 Bump mimemagic to 0.3.9
  Dockerfile
  Gemfile.lock
Labels: Devops, dependencies
