Repository DFE-Digital/publish-teacher-training, pull requests merged in 2021-07, with the labels that each got.

#2033 Wait for review app deployment to finish
  .github/workflows/build.yml
Labels: Devops

#2044 Deploy review app only if labelled
  .github/workflows/build.yml
  .github/workflows/delete-review-app.yml
Labels: Devops, deploy

#2038 Update error messages
  app/controllers/api/v2/courses_controller.rb
  app/services/courses/validate_custom_age_range_service.rb
  config/locales/en.yml
  spec/controllers/api/v2/courses_controller_spec.rb
  spec/models/course_spec.rb
  spec/requests/api/v2/build_new_course_spec.rb
  spec/requests/api/v2/providers/courses/create/age_range_in_years_spec.rb
  spec/requests/api/v2/providers/courses/create_spec.rb
  spec/requests/api/v2/providers/courses/publish_spec.rb
  spec/requests/api/v2/providers/courses/publishable_spec.rb
  spec/requests/api/v2/providers/courses/update_additional_gcse_equivalencies_spec.rb
  spec/requests/api/v2/providers/courses/update_degree_subject_requirements_spec.rb
  spec/requests/api/v2/providers/courses/update_gcse_requirements_spec.rb
  spec/requests/api/v2/providers/courses/update_sites_spec.rb
  spec/requests/api/v2/providers/courses/update_subject_spec.rb
  spec/services/courses/validate_custom_age_range_service_spec.rb
Labels: deploy

#2045 [xxx] Upgrade to Ruby 2.7.4
  .github/workflows/smoke-test.yml
  .tool-versions
  Dockerfile
  Gemfile
  Gemfile.lock
  README.md
  docs/.tool-versions
  docs/Gemfile
  docs/Gemfile.lock
Labels: deploy

#2058 Configure load test environment
  Makefile
  config/environments/loadtest.rb
  config/settings/loadtest.yml
  terraform/workspace_variables/app_config.yml
  terraform/workspace_variables/loadtest.sh
  terraform/workspace_variables/loadtest.tfvars
  terraform/workspace_variables/loadtest_backend.tfvars
Labels: Devops

#2028 [2094] Lead schools are required to have a URN and UKPRN
  app/models/provider.rb
  app/models/site.rb
  app/services/providers/create_fake_provider_service.rb
  app/validators/reference_number_format_validator.rb
  db/seeds.rb
  spec/models/provider_spec.rb
  spec/models/site_spec.rb
Labels: deploy, do not merge

#2060 Configure Genv2 storage account for backup
  .github/workflows/database-restore.yml
Labels: Devops

#2062 Remove Rollover environment
  .github/workflows/build.yml
  .github/workflows/deploy.yml
  Makefile
  config/database.yml
  config/environments/rollover.rb
  config/rubocop/rails.yml
  config/settings/rollover.yml
  terraform/workspace_variables/app_config.yml
  terraform/workspace_variables/rollover.sh
  terraform/workspace_variables/rollover.tfvars
  terraform/workspace_variables/rollover_backend.tfvars
Labels: Devops

#2059 2268 add urn ukprn to public api
  app/serializers/api/public/v1/serializable_location.rb
  app/serializers/api/public/v1/serializable_provider.rb
  app/serializers/api/public/v1/serializable_provider_suggestion.rb
  docs/database-diagram.jpg
  spec/controllers/api/public/v1/providers_controller_spec.rb
  swagger/public_v1/api_spec.json
  swagger/public_v1/component_schemas/ProviderAttributes.yml
Labels: deploy

#2078 [2313] Use PR head branch as docker build tag
  .github/workflows/build.yml
  .github/workflows/delete-review-app.yml
  Dockerfile
  docker-compose.yml
Labels: deploy
