Repository DFE-Digital/publish-teacher-training, pull requests merged in 2021-06, with the labels that each got.

#1690 Use GovukComponent::Tag
  app/decorators/application_decorator.rb
  app/views/courses/_basic_details_tab.html.erb
  app/views/courses/_status_panel.html.erb
  app/views/courses/title/edit.html.erb
  app/views/personas/index.html.erb
  app/views/providers/_search.html.erb
  app/views/providers/allocations/_allocation_report_closed_state.html.erb
  app/views/providers/allocations/_request_status.html.erb
  app/views/providers/contact.html.erb
  app/webpacker/stylesheets/_phase-tag.scss
  app/webpacker/stylesheets/_related.scss
  app/webpacker/stylesheets/application.scss
  spec/decorators/course_decorator_spec.rb
Labels: Components

#1693 Use GovukComponent::SummaryList
  app/components/course_level_component.html.erb
  app/components/course_level_component.rb
  app/decorators/course_decorator.rb
  app/helpers/application_helper.rb
  app/helpers/view_helper.rb
  app/views/courses/_basic_details_tab.html.erb
  app/views/courses/_description_content.html.erb
  app/views/courses/confirmation.html.erb
  app/views/providers/allocations/_allocation_report_closed_state.html.erb
  app/views/providers/allocations/_allocation_report_confirmed_state.html.erb
  app/views/providers/allocations/_request_status.html.erb
  app/views/providers/allocations/check_your_information.html.erb
  app/views/providers/details.html.erb
  app/views/providers/edit_initial_allocations/check_answers.html.erb
  app/views/ucas_contacts/_contact.html.erb
  app/views/ucas_contacts/_ucas_contact_list.html.erb
  app/views/ucas_contacts/show.html.erb
  app/webpacker/stylesheets/_overrides.scss
  app/webpacker/stylesheets/_summary-list.scss
  app/webpacker/stylesheets/_tables.scss
  app/webpacker/stylesheets/application.scss
  spec/components/course_level_component_spec.rb
  spec/features/courses/applications_open/edit_spec.rb
  spec/features/courses/apprenticeship/edit_spec.rb
  spec/features/courses/confirmation_spec.rb
  spec/features/courses/details_spec.rb
  spec/features/courses/fee_or_salary/edit_spec.rb
  spec/features/courses/send/edit_spec.rb
  spec/features/courses/sites/edit_spec.rb
  spec/features/courses/start_date/edit_spec.rb
  spec/features/courses/study_mode/edit_spec.rb
  spec/features/courses/subjects/edit_spec.rb
  spec/features/providers/ucas_contacts_spec.rb
  spec/features/providers/update_ucas_contact_spec.rb
  spec/helpers/application_helper_spec.rb
  spec/site_prism/page_objects/page/organisations/course_confirmation.rb
  spec/site_prism/page_objects/page/organisations/course_details.rb
  spec/site_prism/page_objects/page/organisations/ucas_contacts.rb
  spec/site_prism/page_objects/page/providers/allocations/check_your_information_page.rb
  spec/site_prism/page_objects/page/providers/allocations/edit_initial_allocations/check_answers_page.rb
  spec/views/contacts/_ucas_contact_list_spec.rb
  spec/views/courses/_basic_details_tab.html.erb_spec.rb
Labels: Components

#1701 Deploy review app on pull_request
  .github/workflows/build.yml
  .github/workflows/delete-review-app.yml
  .github/workflows/deploy.yml
  .github/workflows/smoke-test.yml
  terraform/modules/paas/variables.tf
  terraform/workspace_variables/review.sh
  terraform/workspace_variables/review.tfvars
Labels: devops

#1705 Read redis credentials from VCAP services
  config/initializers/sidekiq.rb
Labels: devops

#1771 Add structured gcse requirements section
  app/components/gcse_preview_component.html.erb
  app/components/gcse_preview_component.rb
  app/components/gcse_requirements_component.rb
  app/components/gcse_row_content_component.html.erb
  app/components/gcse_row_content_component.rb
  app/controllers/courses/gcse_requirements_controller.rb
  app/form_objects/courses/gcse_requirements_form.rb
  app/models/course.rb
  app/views/courses/_description_content.html.erb
  app/views/courses/gcse_requirements/edit.html.erb
  app/views/courses/preview/_entry_requirements_qualifications.html.erb
  config/routes.rb
  spec/components/gcse_preview_component_spec.rb
  spec/components/gcse_row_content_component_spec.rb
  spec/factories/courses.rb
  spec/features/courses/gcse_equivalency_spec.rb
  spec/features/courses/show_spec.rb
  spec/form_objects/courses/gcse_requirements_form_spec.rb
  spec/models/course_spec.rb
  spec/site_prism/page_objects/page/organisations/courses/gcse_requirements_page.rb
Labels: enhancement
