Repository DFE-Digital/publish-teacher-training, pull requests merged in 2022-06, with the labels that each got.

#2708 108 css tweaks to and around the nav bar
  app/components/header/style.scss
  app/components/header/view.html.erb
  app/components/navigation_bar/view.html.erb
  app/components/navigation_bar/view.rb
  app/components/phase_banner/script.js
  app/components/phase_banner/style.scss
  app/components/phase_banner/view.html.erb
  app/components/phase_banner/view.rb
  app/components/title_bar/view.html.erb
  app/controllers/publish/providers/access_requests_controller.rb
  app/helpers/application_helper.rb
  app/views/layouts/application.html.erb
  app/views/publish/shared/_navigation_bar_with_training_partners.html.erb
  config/settings/qa.yml
  spec/components/phase_banner/view_spec.rb
Labels: deploy

#2720 99 pe courses for next cycle
  app/helpers/provider_helper.rb
  app/views/publish/courses/subjects/new.html.erb
  config/settings.yml
Labels: deploy

#2684 Quick change to support testing
  Makefile
  docs/disaster-recovery.md
Labels: Devops, deploy

#2734 Remove pointless return nils
  app/forms/publish/notification_form.rb
  app/models/course.rb
  app/models/user_notification_preferences.rb
  app/services/courses/copy_to_provider_service.rb
  app/services/sites/copy_to_provider_service.rb
  docs/lib/govuk_tech_docs/open_api/renderer.rb
Labels: deploy

#2736 Change vacancy link text
  app/decorators/course_decorator.rb
  spec/decorators/course_decorator_spec.rb
Labels: deploy

#2724 Upgrade to Rails 7
  .rubocop.yml
  Gemfile
  Gemfile.lock
  README.md
  app/controllers/magic_link_sessions_controller.rb
  app/controllers/magic_links_controller.rb
  app/controllers/sessions_controller.rb
  app/controllers/support/providers_controller.rb
  app/flows/initial_request_flow.rb
  app/lib/api_constraint.rb
  app/models/course_enrichment.rb
  app/services/subjects/creator_service.rb
  app/views/publish/access_requests/_access_request.html.erb
  app/views/publish/providers/allocations/requests/_not_requested.html.erb
  app/views/publish/providers/allocations/requests/_yes_requested.html.erb
  bin/rails
  bin/rake
  bin/setup
  config/application.rb
  config/cable.yml
  config/database.yml
  config/environment.rb
  config/environments/development.rb
  config/environments/production.rb
  config/environments/test.rb
  config/initializers/content_security_policy.rb
  config/initializers/filter_parameter_logging.rb
  config/initializers/inflections.rb
  config/initializers/new_framework_defaults_6_0.rb
  config/initializers/new_framework_defaults_7_0.rb
  config/initializers/permissions_policy.rb
  config/initializers/semantic_logger.rb
  config/routes.rb
  config/storage.yml
  db/schema.rb
  db/seeds.rb
  spec/components/providers/provider_list/view_preview.rb
  spec/components/providers/provider_list/view_spec.rb
  spec/decorators/course_decorator_spec.rb
  spec/models/course_spec.rb
  spec/models/provider_spec.rb
  spec/models/site_spec.rb
  spec/support/page_objects/publish/rollover.rb
  spec/support/page_objects/publish/rollover_recruitment.rb
  spec/support/page_objects/support/provider/location_edit_page.rb
  spec/support/shared_examples/touch_course.rb
Labels: deploy

#2744 Add review database backup content
  Makefile
  bin/backup-review-database
  bin/upload-review-backup
  docs/disaster-recovery.md
Labels: Devops, deploy

#2756 Remove provider personas when going to support
  app/controllers/concerns/authentication.rb
  app/views/sign_in/_default_signin_content.html.erb
  spec/features/auth/persona_spec.rb
Labels: deploy

#2768 [181] Cookie preference form
  app/controllers/cookie_preferences_controller.rb
  app/forms/publish/cookie_preferences_form.rb
  app/views/cookie_preferences/show.html.erb
  config/locales/en.yml
  config/routes.rb
  config/settings.yml
  config/settings/review.yml
  spec/features/publish/cookie_preferences_spec.rb
  spec/requests/send_data_to_big_query_spec.rb
  spec/support/page_objects/publish/cookie_preferences.rb
Labels: deploy

#2662 replace internal BQ code with dfe-analytics gem
  .github/workflows/build-and-deploy.yml
  Gemfile
  Gemfile.lock
  app/controllers/api_controller.rb
  app/controllers/application_controller.rb
  app/controllers/concerns/emits_request_events.rb
  app/controllers/public_api_controller.rb
  app/jobs/send_event_to_big_query_job.rb
  app/models/application_record.rb
  app/models/concerns/emits_entity_events.rb
  config/analytics_blocklist.yml
  config/analytics_pii.yml
  config/initializers/bigquery.rb
  config/initializers/dfe_analytics.rb
  config/settings.yml
  spec/features/publish/dfe_analytics_events_spec.rb
  spec/jobs/send_event_to_big_query_job_spec.rb
  spec/models/concerns/emits_entity_events_spec.rb
  spec/requests/api/dfe_analytics_events_spec.rb
  spec/requests/send_data_to_big_query_spec.rb
  spec/spec_helper.rb
Labels: deploy

#2780 Upgrade Terraform to 0.14.11
  .github/actions/deploy/action.yml
  .github/workflows/delete-review-app.yml
  .tool-versions
  terraform/.terraform.lock.hcl
  terraform/modules/statuscake/providers.tf
  terraform/terraform.tf
Labels: Devops, deploy

#2781 Update Terraform to 1.2.3
  .github/actions/deploy/action.yml
  .github/workflows/delete-review-app.yml
  .tool-versions
  terraform/.terraform.lock.hcl
  terraform/terraform.tf
Labels: Devops, deploy

#2791 Rename ttapi Azure resources to publish
  .github/workflows/database-restore.yml
  Makefile
  terraform/workspace_variables/loadtest.tfvars.json
  terraform/workspace_variables/loadtest_backend.tfvars
  terraform/workspace_variables/production.tfvars.json
  terraform/workspace_variables/production_backend.tfvars
  terraform/workspace_variables/qa.tfvars.json
  terraform/workspace_variables/qa_backend.tfvars
  terraform/workspace_variables/review.tfvars.json
  terraform/workspace_variables/review_backend.tfvars
  terraform/workspace_variables/rollover.tfvars.json
  terraform/workspace_variables/rollover_backend.tfvars
  terraform/workspace_variables/sandbox.tfvars.json
  terraform/workspace_variables/sandbox_backend.tfvars
  terraform/workspace_variables/staging.tfvars.json
  terraform/workspace_variables/staging_backend.tfvars
Labels: Devops, deploy

#2793 Updates for TTAPI rename to Publish
  .github/actions/deploy/action.yml
  .github/actions/smoke-test/action.yml
  .github/workflows/build-and-deploy.yml
  .github/workflows/build-nocache.yml
  .github/workflows/database-restore.yml
  Makefile
  service_unavailable_page/manifest.yml
Labels: deploy

#2790 [180] Add Google tag manager script
  app/views/cookie_preferences/show.html.erb
  app/views/layouts/application.html.erb
  config/settings.yml
  config/settings/production.yml
Labels: deploy

#2801 Remove env2 routes
  Makefile
  terraform/workspace_variables/production.tfvars.json
  terraform/workspace_variables/qa.tfvars.json
  terraform/workspace_variables/sandbox.tfvars.json
  terraform/workspace_variables/staging.tfvars.json
Labels: Devops
