Repository DFE-Digital/publish-teacher-training, pull requests merged in 2022-10, with the labels that each got.

#3034 [0532] End rollover
  Gemfile.lock
  config/settings.yml
  spec/components/gcse_row_content_component/view_preview.rb
  spec/components/providers/provider_list/view_preview.rb
  spec/features/publish/allocations/edit_initial_allocation_spec.rb
  spec/features/publish/allocations/initial_allocation_spec.rb
  spec/features/publish/allocations/repeat_allocation_spec.rb
  spec/features/publish/allocations/view_closed_state_allocation_spec.rb
  spec/features/publish/allocations/view_confirmed_state_allocation_spec.rb
  spec/features/publish/allocations/view_open_state_allocation_spec.rb
  spec/features/publish/course_confirmation_spec.rb
  spec/features/publish/providers_index_spec.rb
  spec/features/support/providers/courses/editing_a_course_spec.rb
  spec/features/support/switching_between_recruitment_cycles_spec.rb
  spec/forms/edit_course_form_spec.rb
  spec/helpers/view_helper_spec.rb
  spec/models/recruitment_cycle_spec.rb
  spec/models/user_spec.rb
  spec/support/feature_helpers/new_course_param_helper.rb
  spec/support/page_objects/publish/title_bar.rb
Labels: deploy

#3040 [xxx] Clear last cycle year in session if we're not in rollover
  app/controllers/publish/publish_controller.rb
Labels: deploy

#3049 Remove terraform from dependabot checks
  .github/dependabot.yml
Labels: Devops

#3050 [xxxx] Fixed bursaries and scholarships is not announced
  app/decorators/course_decorator.rb
  config/settings.yml
  spec/decorators/course_decorator_spec.rb
  spec/features/publish/viewing_a_course_preview_spec.rb
  spec/features/publish/viewing_a_course_spec.rb
  spec/helpers/find/subject_helper_spec.rb
Labels: deploy

#3031 [0531] Added migrations for financial incentives
  config/settings.yml
  db/migrate/20220929172636_add_2023_financial_incentives.rb
  db/schema.rb
  db/seeds.rb
  docs/database-diagram.jpg
  spec/support/reference_data.rb
Labels: do not merge

#3026 Move CF and DB github secrets to Azure keyvault
  .github/workflows/database-restore.yml
Labels: Devops

#3064 Remove GitHub action minor version pinning
  .github/actions/deploy/action.yml
  .github/workflows/build-and-deploy.yml
  .github/workflows/build-nocache.yml
  .github/workflows/delete-review-app.yml
Labels: Devops, deploy, github_actions

#3052 537 engineers teach physics course flow
  Gemfile.lock
  app/controllers/publish/courses/applications_open_controller.rb
  app/controllers/publish/courses/engineers_teach_physics_controller.rb
  app/controllers/publish/courses/subjects_controller.rb
  app/forms/publish/engineers_teach_physics_form.rb
  app/models/concerns/courses/edit_options.rb
  app/models/concerns/courses/edit_options/engineers_teach_physics_concern.rb
  app/models/concerns/publish/course_basic_detail_concern.rb
  app/models/course.rb
  app/policies/course_policy.rb
  app/services/courses/creation_service.rb
  app/services/courses/generate_course_name_service.rb
  app/services/publish/course_creation_step_service.rb
  app/views/publish/courses/_basic_details_tab.html.erb
  app/views/publish/courses/confirmation.html.erb
  app/views/publish/courses/engineers_teach_physics/_edit_form_fields.html.erb
  app/views/publish/courses/engineers_teach_physics/_form_fields.html.erb
  app/views/publish/courses/engineers_teach_physics/edit.html.erb
  app/views/publish/courses/engineers_teach_physics/new.html.erb
  config/analytics_blocklist.yml
  config/initializers/course_enums.rb
  config/locales/en.yml
  config/routes/publish.rb
  config/settings.yml
  db/migrate/20220928150349_add_campaign_name_to_course.rb
  db/migrate/20221010133216_add_master_subject_to_course.rb
  db/schema.rb
  docs/database-diagram.jpg
  spec/factories/courses.rb
  spec/features/publish/courses/editing_engineers_teach_physics_spec.rb
  spec/features/publish/courses/new_engineers_teach_physics_spec.rb
  spec/features/publish/courses/new_subject_spec.rb
  spec/features/publish/e2e/new_course_spec.rb
  spec/features/publish/viewing_a_course_details_spec.rb
  spec/forms/publish/engineers_teach_physics_form_spec.rb
  spec/models/course_spec.rb
  spec/policies/course_policy_spec.rb
  spec/services/courses/generate_course_name_service_spec.rb
  spec/support/page_objects/publish/course_confirmation.rb
  spec/support/page_objects/publish/courses/edit_engineers_teach_physics.rb
  spec/support/page_objects/publish/courses/new_engineers_teach_physics.rb
Labels: deploy

#3066 [xxx] Fix ETP issues
  app/forms/publish/engineers_teach_physics_form.rb
  app/models/course.rb
  db/migrate/20221018084448_update_etp_field.rb
  db/schema.rb
  docs/database-diagram.jpg
  spec/models/course_spec.rb
Labels: deploy

#3070 fix etp new page
  app/controllers/publish/courses/engineers_teach_physics_controller.rb
  spec/features/publish/courses/new_engineers_teach_physics_spec.rb
Labels: deploy

#3069 [0575] Added sitemap setup for Find
  app/controllers/find/sitemaps_controller.rb
  app/views/find/sitemaps/show.xml.builder
  config/routes/find.rb
  spec/requests/find/sitemaps_spec.rb
Labels: deploy

#3073 [735]reset campaign name when changing from ETP
  app/controllers/publish/courses/subjects_controller.rb
  app/views/publish/courses/engineers_teach_physics/_edit_form_fields.html.erb
  app/views/publish/courses/engineers_teach_physics/_form_fields.html.erb
  spec/features/publish/courses/editing_engineers_teach_physics_spec.rb
  spec/features/publish/courses/new_engineers_teach_physics_spec.rb
  spec/features/publish/courses/new_subject_spec.rb
  spec/features/publish/e2e/new_course_spec.rb
Labels: deploy

#3084 Expat vulnerability fix
  Dockerfile
Labels: security, Devops

#3077 Use subject name not course title for qualifications needed
  app/components/find_interface/courses/entry_requirements_component/view.rb
  app/decorators/course_decorator.rb
  spec/components/find_interface/courses/entry_requirements_component/view_preview.rb
  spec/components/find_interface/courses/entry_requirements_component/view_spec.rb
  spec/decorators/course_decorator_spec.rb
Labels: deploy

#3089 [0563] Course search initial form by city javascript version
  Gemfile
  Gemfile.lock
  app/controllers/find/location_suggestions_controller.rb
  app/javascript/find/__snapshots__/autocomplete.spec.js.snap
  app/javascript/find/application.js
  app/javascript/find/autocomplete.js
  app/javascript/find/autocomplete.spec.js
  app/services/location_suggestion.rb
  app/views/find/search/locations/index.html.erb
  config/routes/find.rb
  config/settings.yml
  package.json
  spec/fixtures/api_responses/location-suggestions.json
  spec/requests/find/locations_suggestions_spec.rb
  spec/support/stubbed_requests/location_suggestions.rb
  yarn.lock
Labels: deploy
