Repository DFE-Digital/publish-teacher-training, pull requests merged in 2022-05, with the labels that each got.

#2626 830 update save content
  app/controllers/concerns/success_message.rb
  app/controllers/publish/courses/age_range_controller.rb
  app/controllers/publish/courses/base_funding_type_controller.rb
  app/controllers/publish/courses/course_information_controller.rb
  app/controllers/publish/courses/degrees/grade_controller.rb
  app/controllers/publish/courses/degrees/start_controller.rb
  app/controllers/publish/courses/degrees/subject_requirements_controller.rb
  app/controllers/publish/courses/fees_controller.rb
  app/controllers/publish/courses/gcse_requirements_controller.rb
  app/controllers/publish/courses/outcome_controller.rb
  app/controllers/publish/courses/sites_controller.rb
  app/controllers/publish/courses/study_mode_controller.rb
  app/controllers/publish/courses/subjects_controller.rb
  app/controllers/publish/providers/locations_controller.rb
  app/controllers/publish/publish_controller.rb
  app/models/course.rb
  app/views/publish/courses/age_range/edit.html.erb
  app/views/publish/courses/course_information/edit.html.erb
  app/views/publish/courses/degrees/grade/edit.html.erb
  app/views/publish/courses/degrees/start/edit.html.erb
  app/views/publish/courses/degrees/subject_requirements/edit.html.erb
  app/views/publish/courses/fees/edit.html.erb
  app/views/publish/courses/gcse_requirements/edit.html.erb
  app/views/publish/courses/outcome/edit.html.erb
  app/views/publish/courses/requirements/edit.html.erb
  app/views/publish/courses/salary/edit.html.erb
  app/views/publish/courses/sites/edit.html.erb
  app/views/publish/courses/study_mode/edit.html.erb
  app/views/publish/courses/subjects/edit.html.erb
  app/views/publish/providers/about.html.erb
  app/views/publish/providers/contacts/edit.html.erb
  app/views/publish/providers/locations/edit.html.erb
  app/views/publish/providers/visas/edit.html.erb
  config/locales/en.yml
  spec/features/publish/courses/editing_age_range_spec.rb
  spec/features/publish/courses/editing_course_information_spec.rb
  spec/features/publish/courses/editing_course_locations_spec.rb
  spec/features/publish/courses/editing_course_outcome_spec.rb
  spec/features/publish/courses/editing_course_study_mode_spec.rb
  spec/features/publish/courses/editing_degree_requirements_spec.rb
  spec/features/publish/courses/editing_subject_spec.rb
  spec/features/publish/courses/gcse_equivalency_spec.rb
Labels: deploy

#2635 Add disaster recovery docs
  Makefile
  bin/download-nightly-backup
  bin/restore-nightly-backup
  docs/disaster-recovery.md
  docs/maintenance-mode.md
  service_unavailable_page/web/nginx.conf
Labels: Devops

#2636 Add data corruption to DR docs
  Makefile
  docs/disaster-recovery.md
  terraform/modules/paas/variables.tf
  terraform/terraform.tf
  terraform/variables.tf
Labels: Devops, deploy

#2645 [0942] Amended cookie name
  config/application.rb
Labels: deploy

#2646 Fix some issues in DR documentation
  Makefile
  docs/disaster-recovery.md
Labels: Devops

#2631 [0837] Migrate the PE allocations section open state
  app/controllers/publish/providers/allocations_controller.rb
  app/controllers/publish/providers/edit_initial_allocations_controller.rb
  app/flows/edit_initial_request_flow.rb
  app/flows/initial_request_flow.rb
  app/forms/publish/allocations/edit_initial/number_of_places_form.rb
  app/forms/publish/allocations/edit_initial/request_type_form.rb
  app/forms/publish/initial_request_form.rb
  app/forms/publish/repeat_request_form.rb
  app/policies/allocation_policy.rb
  app/views/publish/providers/allocations/_request_status.html.erb
  app/views/publish/providers/allocations/allocation_report/_confirmed_state.html.erb
  app/views/publish/providers/allocations/allocation_request/_open_state.html.erb
  app/views/publish/providers/allocations/check_your_information.html.erb
  app/views/publish/providers/allocations/edit.html.erb
  app/views/publish/providers/allocations/edit_initial_allocations/check_answers.html.erb
  app/views/publish/providers/allocations/edit_initial_allocations/do_you_want.html.erb
  app/views/publish/providers/allocations/edit_initial_allocations/number_of_places.html.erb
  app/views/publish/providers/allocations/initial_request.html.erb
  app/views/publish/providers/allocations/new_repeat_request.html.erb
  app/views/publish/providers/allocations/number_of_places.html.erb
  app/views/publish/providers/allocations/pick_a_provider.html.erb
  app/views/publish/providers/allocations/requests/_not_requested.html.erb
  app/views/publish/providers/allocations/requests/_yes_requested.html.erb
  app/views/publish/providers/allocations/show.html.erb
  config/routes.rb
  config/settings.yml
  config/settings/review.yml
  spec/factories/allocations.rb
  spec/features/publish/allocations/edit_initial_allocation_spec.rb
  spec/features/publish/allocations/initial_allocation_spec.rb
  spec/features/publish/allocations/repeat_allocation_spec.rb
  spec/features/publish/allocations/view_closed_state_allocation_spec.rb
  spec/features/publish/allocations/view_confirmed_state_allocation_spec.rb
  spec/features/publish/allocations/view_open_state_allocation_spec.rb
  spec/forms/publish/allocations/edit_initial/number_of_places_form_spec.rb
  spec/forms/publish/allocations/edit_initial/request_type_form_spec.rb
  spec/forms/publish/initial_request_form_spec.rb
  spec/support/feature_helpers/publish_pages.rb
  spec/support/page_objects/publish/allocations/allocations_edit_page.rb
  spec/support/page_objects/publish/allocations/allocations_page.rb
  spec/support/page_objects/publish/allocations/allocations_show_page.rb
  spec/support/page_objects/publish/allocations/edit_initial_allocations/check_answers_page.rb
  spec/support/page_objects/publish/allocations/edit_initial_allocations/do_you_want_page.rb
  spec/support/page_objects/publish/allocations/edit_initial_allocations/number_of_places_page.rb
  spec/support/page_objects/publish/allocations/new_repeat_request_page.rb
  spec/support/page_objects/publish/allocations/request/check_your_info_page.rb
  spec/support/page_objects/publish/allocations/request/number_of_places_page.rb
  spec/support/page_objects/publish/allocations/request/pick_a_provider_page.rb
  spec/support/page_objects/publish/allocations/request/who_are_you_requesting_a_course_for_page.rb
  spec/support/page_objects/publish/courses/outcome_edit_page.rb
  spec/support/page_objects/sections/radio_button.rb
Labels: deploy

#2652 [954] Fix breadcrumbs in new publish
  app/helpers/breadcrumb_helper.rb
  app/models/user.rb
  app/views/publish/courses/details.html.erb
  app/views/publish/courses/index.html.erb
  app/views/publish/courses/show.html.erb
  app/views/publish/providers/allocations/allocation_request/_closed_state.html.erb
  app/views/publish/providers/allocations/allocation_request/_confirmed_state.html.erb
  app/views/publish/providers/allocations/allocation_request/_open_state.html.erb
  app/views/publish/providers/details.html.erb
  app/views/publish/providers/locations/edit.html.erb
  app/views/publish/providers/locations/index.html.erb
  app/views/publish/providers/locations/new.html.erb
  app/views/publish/providers/show.html.erb
  app/views/publish/training_providers/courses/index.html.erb
  app/views/publish/training_providers/index.html.erb
  app/views/publish/users/index.html.erb
Labels: deploy

#2651 Dr doc refinements
  .github/workflows/database-restore.yml
  .gitignore
  .tool-versions
  Makefile
  bin/download-nightly-backup
  bin/restore-nightly-backup
  docs/disaster-recovery.md
Labels: Devops, deploy

#2638 Add rollover env
  .github/workflows/build-and-deploy.yml
  Makefile
  config/database.yml
  config/environments/rollover.rb
  config/settings/rollover.yml
  terraform/modules/paas/main.tf
  terraform/modules/paas/variables.tf
  terraform/workspace_variables/app_config.yml
  terraform/workspace_variables/rollover.tfvars.json
  terraform/workspace_variables/rollover_backend.tfvars
Labels: Devops

#2687 Add rollover to deploy workflow dispatch
  .github/workflows/deploy.yml
Labels: Devops

#2682 Remove breadcrumbs
  app/views/layouts/application.html.erb
  config/settings.yml
  config/settings/review.yml
Labels: deploy

#2689 [67] Migrate the access requests section
  app/controllers/publish/access_requests_controller.rb
  app/helpers/user_helper.rb
  app/policies/access_request_policy.rb
  app/views/layouts/_footer.html.erb
  app/views/publish/access_requests/_access_request.html.erb
  app/views/publish/access_requests/confirm.html.erb
  app/views/publish/access_requests/index.html.erb
  app/views/publish/access_requests/inform_publisher.html.erb
  config/routes.rb
  config/settings.yml
  spec/features/support/access_requests/managing_requests_spec.rb
  spec/serializers/api/v3/serializable_course_spec.rb
  spec/support/feature_helpers/publish_pages.rb
  spec/support/feature_helpers/support_pages.rb
  spec/support/page_objects/publish/footer.rb
  spec/support/page_objects/support/access_requests/confirm.rb
  spec/support/page_objects/support/access_requests/index.rb
Labels: deploy

#2703 [85] Application start date is causing issues
  app/decorators/course_decorator.rb
  app/services/courses/copy_to_provider_service.rb
  spec/services/courses/copy_to_provider_service_spec.rb
Labels: deploy
