Repository DFE-Digital/publish-teacher-training, pull requests merged in 2022-04, with the labels that each got.

#2594 Base Image Vulnerability fixes
  Dockerfile
Labels: Devops, deploy

#2581 #622 Migrate Courses - Course show page - Copy content from other course
  app/controllers/concerns/copy_course_content.rb
  app/controllers/publish/courses/course_information_controller.rb
  app/controllers/publish/courses/degrees/subject_requirements_controller.rb
  app/controllers/publish/courses/fees_controller.rb
  app/controllers/publish/courses/gcse_requirements_controller.rb
  app/controllers/publish/courses/requirements_controller.rb
  app/services/courses/copy.rb
  app/services/courses/fetch.rb
  app/views/publish/courses/_copy_content_warning.html.erb
  app/views/publish/courses/_course_length_field.html.erb
  app/views/publish/courses/_course_select_option.html.erb
  app/views/publish/courses/_gcse_requirements.html.erb
  app/views/publish/courses/_markdown_formatting.html.erb
  app/views/publish/courses/_other_course_length_field.html.erb
  app/views/publish/courses/_related_sidebar.html.erb
  app/views/publish/courses/course_information/edit.html.erb
  app/views/publish/courses/degrees/_additional_degree_subject_requirements.html.erb
  app/views/publish/courses/degrees/subject_requirements/edit.html.erb
  app/views/publish/courses/fees/edit.html.erb
  app/views/publish/courses/gcse_requirements/edit.html.erb
  app/views/publish/courses/requirements/edit.html.erb
  spec/features/publish/courses/editing_course_information_spec.rb
  spec/features/publish/courses/editing_course_length_and_funding_type.rb
  spec/features/publish/courses/editing_course_requirements_spec.rb
  spec/features/publish/courses/editing_degree_requirements_spec.rb
  spec/features/publish/courses/gcse_equivalency_spec.rb
  spec/support/page_objects/publish/course_fee_edit.rb
  spec/support/page_objects/publish/course_information_edit.rb
  spec/support/page_objects/publish/course_requirement_edit.rb
  spec/support/page_objects/publish/courses/gcse_requirements_page.rb
  spec/support/page_objects/publish/degree_subject_requirement.rb
  spec/support/page_objects/sections/copy_content.rb
Labels: deploy

#2593 [836] Migrate the training providers list
  app/controllers/publish/training_providers/courses_controller.rb
  app/controllers/publish/training_providers_controller.rb
  app/views/publish/courses/_course_table.html.erb
  app/views/publish/training_providers/courses/index.html.erb
  app/views/publish/training_providers/index.html.erb
  config/routes.rb
  spec/features/publish/viewing_training_providers_and_their_courses_spec.rb
  spec/support/feature_helpers/publish_pages.rb
  spec/support/page_objects/publish/training_provider_index.rb
  spec/support/page_objects/publish/training_providers/course_index.rb
  spec/support/page_objects/sections/training_provider.rb
Labels: deploy

#2597 [854] Migrate the PE allocations section confirmed state
  app/controllers/publish/providers/allocations_controller.rb
  app/view_objects/allocations_view.rb
  app/views/publish/providers/allocations/allocation_report/_confirmed_state.html.erb
  app/views/publish/providers/allocations/allocation_request/_confirmed_state.html.erb
  app/views/publish/providers/allocations/index.html.erb
  config/routes.rb
  config/settings.yml
  docs/allocations.md
  spec/features/publish/allocations/view_allocation_spec.rb
  spec/support/feature_helpers/publish_pages.rb
  spec/support/page_objects/publish/allocations/allocations_page.rb
  spec/view_objects/allocations_view_spec.rb
Labels: deploy

#2607 Use workflow concurrency for build and deploy
  .github/workflows/build-and-deploy.yml
Labels: Devops, deploy

#2609 Add concurency to the deploy workflows
  .github/workflows/deploy.yml
Labels: Devops

#2603 [839] Port the terms interruption page
  app/controllers/publish/publish_controller.rb
  app/controllers/publish/terms_controller.rb
  app/forms/publish/interruption/accept_terms_form.rb
  app/models/user.rb
  app/views/publish/terms/edit.html.erb
  config/locales/en.yml
  config/routes.rb
  spec/features/publish/accepting_terms_spec.rb
  spec/support/feature_helpers/publish_pages.rb
  spec/support/page_objects/publish/terms.rb
Labels: deploy

#2613 [876] Port over rollover interruption screen
  app/controllers/publish/publish_controller.rb
  app/controllers/publish/rollover_controller.rb
  app/helpers/recruitment_cycle_helper.rb
  app/models/user.rb
  app/views/publish/rollover/new.html.erb
  config/routes.rb
  spec/features/publish/accepting_rollover_spec.rb
  spec/models/user_spec.rb
  spec/support/feature_helpers/publish_pages.rb
  spec/support/page_objects/publish/rollover.rb
Labels: deploy

#2619 Delete GitHub environment
  .github/actions/deploy/action.yml
  .github/workflows/build-and-deploy.yml
  .github/workflows/delete-review-app.yml
  .github/workflows/deploy.yml
Labels: Devops, deploy

#2621 [904] Fix accredited body search step
  app/controllers/publish/courses/accredited_body_controller.rb
  app/controllers/publish/courses/applications_open_controller.rb
  app/views/publish/courses/accredited_body/search_new.html.erb
Labels: deploy

#2598 #838 Migrate organisation root pages
  app/controllers/application_controller.rb
  app/controllers/publish/courses/applications_open_controller.rb
  app/controllers/publish/providers_controller.rb
  app/controllers/publish/recruitment_cycles_controller.rb
  app/controllers/sessions_controller.rb
  app/helpers/application_helper.rb
  app/helpers/breadcrumb_helper.rb
  app/models/allocation.rb
  app/models/provider.rb
  app/policies/provider_policy.rb
  app/views/layouts/application.html.erb
  app/views/pagy/_next_page.html.erb
  app/views/pagy/_paginator.html.erb
  app/views/pagy/_previous_page.html.erb
  app/views/publish/courses/index.html.erb
  app/views/publish/providers/_provider.html.erb
  app/views/publish/providers/_search.html.erb
  app/views/publish/providers/details.html.erb
  app/views/publish/providers/index.html.erb
  app/views/publish/providers/locations/index.html.erb
  app/views/publish/providers/no_providers.html.erb
  app/views/publish/providers/show.html.erb
  app/views/publish/recruitment_cycles/_about_organisation.html.erb
  app/views/publish/recruitment_cycles/_allocations.html.erb
  app/views/publish/recruitment_cycles/_courses_accredited_body.html.erb
  app/views/publish/recruitment_cycles/_courses_info.html.erb
  app/views/publish/recruitment_cycles/_locations_info.html.erb
  app/views/publish/recruitment_cycles/_provider_info.html.erb
  app/views/publish/recruitment_cycles/_show_during_rollover.html.erb
  app/views/publish/recruitment_cycles/show.html.erb
  app/views/publish/shared/_aside_information_box.html.erb
  app/views/publish/training_providers/index.html.erb
  app/views/publish/users/index.html.erb
  app/views/sign_in/_default_signin_content.html.erb
  app/webpacker/packs/application.js
  app/webpacker/scripts/autocomplete.js
  app/webpacker/styles/_autocomplete.scss
  app/webpacker/styles/_pagination.scss
  app/webpacker/styles/application.scss
  config/locales/en.yml
  config/routes.rb
  package-lock.json
  package.json
  spec/features/publish/accepting_rollover_recruitment_spec.rb
  spec/features/publish/accepting_rollover_spec.rb
  spec/features/publish/accepting_terms_spec.rb
  spec/features/publish/providers_index_spec.rb
  spec/features/publish/providers_show_spec.rb
  spec/support/feature_helpers/publish_pages.rb
  spec/support/page_objects/publish/providers_index.rb
  spec/support/page_objects/publish/providers_show.rb
  yarn.lock
Labels: deploy

#2622 [909] Mark site and site status relationship correctly
  app/forms/publish/course_location_form.rb
Labels: deploy

#2630 [568] Migrate the notifications page
  app/components/header/view.html.erb
  app/components/header/view.rb
  app/controllers/publish/notifications_controller.rb
  app/forms/publish/notification_form.rb
  app/view_objects/notifications_view.rb
  app/views/publish/notifications/index.html.erb
  config/routes.rb
  spec/components/header/view_spec.rb
  spec/features/publish/editing_notification_preference_spec.rb
  spec/support/feature_helpers/publish_pages.rb
  spec/support/page_objects/publish/header.rb
  spec/support/page_objects/publish/notification.rb
  spec/view_objects/notifications_view_spec.rb
Labels: deploy
