Repository DFE-Digital/publish-teacher-training, pull requests merged in 2022-11, with the labels that each got.

#3094 Stop using set-output in check_sp workflow
  .github/actions/deploy/action.yml
Labels: Devops, deploy, github_actions

#3096 Remove rollover env
  .github/workflows/deploy.yml
  Makefile
  config/database.yml
  config/environments/rollover.rb
  config/settings/rollover.yml
  terraform/workspace_variables/app_config.yml
  terraform/workspace_variables/rollover.tfvars.json
  terraform/workspace_variables/rollover_backend.tfvars
Labels: Devops

#3103 Remove subjects from ignored list
  app/helpers/find/subject_helper.rb
  spec/features/find/course_searches_spec.rb
Labels: deploy

#3106 [779] Display bug for course fee field
  app/views/publish/courses/fees/edit.html.erb
Labels: deploy

#3114 [0803] Update qualifications needed content for ETP courses for newer find
  Gemfile
  app/components/find_interface/courses/entry_requirements_component/view.html.erb
  spec/components/find_interface/courses/entry_requirements_component/view_preview.rb
  spec/components/find_interface/courses/entry_requirements_component/view_spec.rb
Labels: deploy

#3108 [777] Migrate the find feature flags
  Gemfile
  Gemfile.lock
  app/components/find_interface/feature_history_component.html.erb
  app/components/find_interface/feature_history_component.rb
  app/components/find_interface/feature_toggle_component.html.erb
  app/components/find_interface/feature_toggle_component.rb
  app/components/find_interface/maintenance_banner_component.html.erb
  app/components/find_interface/maintenance_banner_component.rb
  app/components/find_interface/utility/summary_card_component.html.erb
  app/components/find_interface/utility/summary_card_component.rb
  app/components/find_interface/utility/summary_card_header_component.html.erb
  app/components/find_interface/utility/summary_card_header_component.rb
  app/components/find_interface/utility/summary_list_component.html.erb
  app/components/find_interface/utility/summary_list_component.rb
  app/controllers/find/application_controller.rb
  app/controllers/find/confirm_environment_controller.rb
  app/controllers/find/feature_flags_controller.rb
  app/controllers/find/pages_controller.rb
  app/forms/find/confirm_environment.rb
  app/helpers/find/view_helper.rb
  app/jobs/find/slack_notification_job.rb
  app/lib/feature_flag.rb
  app/lib/feature_flags.rb
  app/views/find/confirm_environment/new.html.erb
  app/views/find/feature_flags/index.html.erb
  app/views/find/pages/maintenance.html.erb
  app/views/layouts/find_layout.html.erb
  config/locales/en.yml
  config/routes/find.rb
  config/settings.yml
  config/settings/production.yml
  config/settings/test.yml
  spec/components/find_interface/feature_history_component_spec.rb
  spec/components/find_interface/maintenance_banner_component_spec.rb
  spec/features/find/feature_flags_spec.rb
  spec/features/find/maintainance_page_spec.rb
  spec/features/find/maintenance_banner_spec.rb
  spec/jobs/find/slack_notification_job_spec.rb
  spec/lib/feature_flag_spec.rb
  spec/support/mock_redis.rb
  spec/support/page_objects/find/feature_flag.rb
Labels: deploy

#3122 Add campaign_name to CourseFilter
  swagger/public_v1/api_spec.json
  swagger/public_v1/component_schemas/CourseFilter.yml
Labels: deploy

#3131 [813] Clean up find feature flags
  app/components/find_interface/courses/financial_support/bursary_component/view.html.erb
  app/components/find_interface/courses/financial_support/scholarship_and_bursary_component/view.html.erb
  app/decorators/course_decorator.rb
  app/helpers/find/subject_helper.rb
  app/lib/feature_flags.rb
  config/settings.yml
  spec/components/find_interface/courses/financial_support/bursary_component/view_spec.rb
  spec/components/find_interface/courses/financial_support/fees_and_financial_support_component/view_spec.rb
  spec/components/find_interface/courses/financial_support/scholarship_and_bursary_component/view_spec.rb
  spec/decorators/course_decorator_spec.rb
  spec/features/publish/viewing_a_course_preview_spec.rb
  spec/features/publish/viewing_a_course_spec.rb
  spec/helpers/find/subject_helper_spec.rb
Labels: deploy

#3128 [0780] Amended so that courses are order ascending
  app/models/course.rb
  app/services/course_search_service.rb
  spec/models/course_spec.rb
  spec/requests/api/v3/courses/index_spec.rb
  spec/services/course_search_service_spec.rb
Labels: deploy

#3133 [0833] Fixed incorrect URL for info on Maths scholarship
  config/locales/find.yml
Labels: deploy

#3134 Campaign name api fix
  spec/requests/api/v3/providers/courses/index_spec.rb
  swagger/public_v1/api_spec.json
  swagger/public_v1/component_schemas/CourseAttributes.yml
  swagger/public_v1/component_schemas/CourseFilter.yml
Labels: deploy

#3138 [822] Make close filter button more accessible
  app/javascript/find/filter-toggle-button.js
Labels: deploy

#3127 Don't capitalise subjects unless the subject is a language
  app/components/find_interface/courses/entry_requirements_component/view.rb
  app/decorators/course_decorator.rb
  spec/components/find_interface/courses/entry_requirements_component/view_preview.rb
  spec/components/find_interface/courses/entry_requirements_component/view_spec.rb
  spec/decorators/course_decorator_spec.rb
Labels: deploy

#3135 [799] Update privacy notice for Publish and New Find
  app/views/find/pages/privacy.html.erb
  app/views/layouts/_find_footer.html.erb
  app/views/layouts/_footer.html.erb
  app/views/pages/privacy.html.erb
  config/routes/find.rb
  config/routes/publish.rb
  spec/features/find/view_pages_spec.rb
  spec/features/view_pages_spec.rb
Labels: deploy

#3113 781 fix subject order in check your answers and course details page
  app/decorators/course_decorator.rb
  app/models/course.rb
  app/views/publish/courses/_basic_details_tab.html.erb
  app/views/publish/courses/confirmation.html.erb
  spec/decorators/course_decorator_spec.rb
Labels: deploy

#3140 [0827] The sort by field should not auto submit we should provide a submit button
  app/assets/stylesheets/components/find/_search-results.scss
  app/components/find_interface/results/sort_by_component.html.erb
Labels: deploy

#3147 [0824] Fixed mis match page title vs h1
  app/views/find/results/index.html.erb
  app/views/find/search/subjects/index.html.erb
  config/locales/find.yml
Labels: deploy

#3148 Expand qualification abbreviations on first instance eg pgce and qts
  app/models/concerns/with_qualifications.rb
  app/models/course.rb
  app/serializers/api/v3/serializable_course.rb
  spec/requests/api/v3/providers/courses/index_spec.rb
  spec/requests/api/v3/providers/courses/show_spec.rb
Labels: deploy

#3150 [0830] Add additional filter options to the providers api endpoints
  app/controllers/api/public/v1/providers_controller.rb
  app/models/provider.rb
  spec/controllers/api/public/v1/providers_controller_spec.rb
  spec/models/provider_spec.rb
  swagger/public_v1/api_spec.json
  swagger/public_v1/component_schemas/ProviderFilter.yml
Labels: deploy

#3153 Add ETP checkbox UI
  app/view_objects/find/result_filters/filters_view.rb
  app/view_objects/find/results_view.rb
  app/views/find/result_filters/_all.html.erb
  app/views/find/result_filters/_engineers_teach_physics_filter.html.erb
  spec/features/find/result_page_filters/engineers_teach_physics_spec.rb
  spec/support/page_objects/find/results.rb
Labels: deploy
