Repository DFE-Digital/publish-teacher-training, pull requests merged in 2022-01, with the labels that each got.

#2071 Update about.html.erb
  app/views/courses/about.html.erb
  spec/features/courses/about_spec.rb
Labels: deploy

#2075 Update edit.html.erb
  app/views/providers/visas/edit.html.erb
Labels: deploy

#2070 [540] Remove admin features from Publish as migrated to Support Console
  app/controllers/courses/title_controller.rb
  app/views/courses/_basic_details_tab.html.erb
  app/views/courses/title/edit.html.erb
  config/routes.rb
  spec/controllers/courses/title_controller_spec.rb
  spec/features/courses/send/edit_spec.rb
  spec/views/courses/_basic_details_tab.html.erb_spec.rb
Labels: do not merge, deploy

#2077 [0570] Added redirect for the details page to new publish
  app/controllers/application_controller.rb
  app/controllers/providers/visas_controller.rb
  app/controllers/providers_controller.rb
  app/helpers/new_publish_helper.rb
  config/settings/review.yml
  spec/controllers/application_controller_spec.rb
  spec/helpers/new_publish_helper_spec.rb
Labels: deploy

#2100 Use tfvarsjson for workspace variables
  .github/workflows/delete-review-app.yml
  .github/workflows/deploy.yml
  Makefile
  terraform/workspace_variables/local.sh
  terraform/workspace_variables/local.tfvars.json
  terraform/workspace_variables/production.sh
  terraform/workspace_variables/production.tfvars
  terraform/workspace_variables/production.tfvars.json
  terraform/workspace_variables/qa.sh
  terraform/workspace_variables/qa.tfvars
  terraform/workspace_variables/qa.tfvars.json
  terraform/workspace_variables/review.sh
  terraform/workspace_variables/review.tfvars
  terraform/workspace_variables/review.tfvars.json
  terraform/workspace_variables/sandbox.sh
  terraform/workspace_variables/sandbox.tfvars
  terraform/workspace_variables/sandbox.tfvars.json
  terraform/workspace_variables/staging.sh
  terraform/workspace_variables/staging.tfvars
  terraform/workspace_variables/staging.tfvars.json
Labels: devops
