Repository DFE-Digital/publish-teacher-training, pull requests merged in 2022-03, with the labels that each got.

#2141 Update docker base image to ruby:2.7.5-alpine3.15
  .github/workflows/smoke-test.yml
  .tool-versions
  Dockerfile
  Gemfile
  Gemfile.lock
  package.json
Labels: devops

#2145 Update gmp in Dockerfile to fix vulnerability
  Dockerfile
Labels: devops, deploy

#2149 Fix GHCR login for build-no-cache workflow
  .github/workflows/build-nocache.yml
Labels: devops

#2139 Update edit.html.erb
  app/views/courses/sites/edit.html.erb
Labels: deploy

#2151 Fix libretls vulnerability CVE-2022-0778
  Dockerfile
Labels: devops
