Repository DFE-Digital/publish-teacher-training, pull requests merged in 2022-03, with the labels that each got.

#2541 [694] Handle nils in existing_sequential_codes
  app/services/sites/code_generator.rb
Labels: deploy

#2533 Update index.html.erb
  app/views/publish/providers/locations/index.html.erb
  spec/support/page_objects/publish/locations_index.rb
Labels: deploy

#2534 Update new.html.erb
  app/views/publish/providers/locations/new.html.erb
Labels: deploy

#2525 [0698] Migrate courses add course form button
  app/controllers/publish/courses/accredited_body_controller.rb
  app/controllers/publish/courses/applications_open_controller.rb
  app/controllers/publish/courses/modern_languages_controller.rb
  app/controllers/publish/courses/sites_controller.rb
  app/controllers/publish/courses/subjects_controller.rb
  app/controllers/publish/courses_controller.rb
  app/decorators/course_decorator.rb
  app/models/concerns/publish/course_basic_detail_concern.rb
  app/models/site_status.rb
  app/policies/course_policy.rb
  app/services/courses/creation_service.rb
  app/views/publish/courses/accredited_body/_provider_suggestion.html.erb
  app/views/publish/courses/accredited_body/new.html.erb
  app/views/publish/courses/confirmation.html.erb
  app/views/publish/courses/modern_languages/_form_fields.html.erb
  app/views/publish/courses/modern_languages/new.erb
  spec/decorators/course_decorator_spec.rb
  spec/factories/subjects/modern_languages_subjects.rb
  spec/features/publish/course_confirmation_spec.rb
  spec/features/publish/courses/new_accredited_body_spec.rb
  spec/features/publish/courses/new_age_range_spec.rb
  spec/features/publish/courses/new_applications_open_spec.rb
  spec/features/publish/courses/new_apprenticeship_spec.rb
  spec/features/publish/courses/new_course_outcome_spec.rb
  spec/features/publish/courses/new_fee_or_salary_spec.rb
  spec/features/publish/courses/new_level_spec.rb
  spec/features/publish/courses/new_locations_spec.rb
  spec/features/publish/courses/new_mordern_languages_spec.rb
  spec/features/publish/courses/new_start_date_spec.rb
  spec/features/publish/courses/new_study_mode_spec.rb
  spec/features/publish/courses/new_subject.rb
  spec/features/publish/courses/new_subject_spec.rb
  spec/features/publish/e2e/new_course_spec.rb
  spec/features/publish/viewing_courses_spec.rb
  spec/models/concerns/courses/edit_options_spec.rb
  spec/models/site_status_spec.rb
  spec/policies/course_policy_spec.rb
  spec/services/courses/creation_service_spec.rb
  spec/services/courses/generate_course_name_service_spec.rb
  spec/support/feature_helpers/new_course_param_helper.rb
  spec/support/page_objects/publish/course_confirmation.rb
  spec/support/page_objects/publish/course_fee_edit.rb
  spec/support/page_objects/publish/course_information_edit.rb
  spec/support/page_objects/publish/course_salary_edit.rb
  spec/support/page_objects/publish/courses/new_modern_languages_page.rb
  spec/support/page_objects/publish/courses/new_subjects_page.rb
  spec/support/page_objects/publish/provider_courses_index.rb
Labels: deploy

#2530 [0615] Migrate courses show page
  app/models/course.rb
  app/views/publish/courses/_description_status_panel.html.erb
  app/views/publish/courses/show.html.erb
  app/views/publish/courses/status_panel/_published.html.erb
  app/views/publish/courses/status_panel/_unpublished.html.erb
  app/views/publish/courses/status_panel/_withdrawn.html.erb
  spec/features/publish/viewing_a_course_spec.rb
  spec/support/page_objects/publish/provider_courses_show.rb
  spec/support/page_objects/sections/status_sidebar.rb
Labels: deploy

#2544 [614] Port over course requirements flow
  app/controllers/publish/courses/requirements_controller.rb
  app/forms/publish/course_requirement_form.rb
  app/models/course_enrichment.rb
  app/views/publish/courses/_description_content.html.erb
  app/views/publish/courses/requirements/edit.html.erb
  config/locales/en.yml
  config/routes.rb
  spec/features/publish/courses/editing_course_requirements_spec.rb
  spec/support/feature_helpers/publish_pages.rb
  spec/support/page_objects/publish/course_requirement_edit.rb
Labels: deploy

#2545 Update docker base image to ruby:2.7.5-alpine3.15
  .github/workflows/smoke-test.yml
  .tool-versions
  Dockerfile
  Gemfile
  Gemfile.lock
  docs/.tool-versions
  docs/Gemfile
  docs/Gemfile.lock
  package.json
Labels: Devops

#2551 Fix GHCR login for build-no-cache workflow
  .github/workflows/build-nocache.yml
Labels: Devops

#2546 [0629] Migrate courses course show page preview content
  Gemfile
  Gemfile.lock
  app/components/degree_preview_component/view.html.erb
  app/components/degree_preview_component/view.rb
  app/components/gcse_preview_component/view.html.erb
  app/components/gcse_preview_component/view.rb
  app/controllers/publish/courses_controller.rb
  app/decorators/course_decorator.rb
  app/helpers/application_helper.rb
  app/helpers/publish_helper.rb
  app/lib/govuk/markdown_renderer.rb
  app/models/provider.rb
  app/models/site_status.rb
  app/policies/course_policy.rb
  app/views/layouts/application.html.erb
  app/views/publish/courses/preview.html.erb
  app/views/publish/courses/preview/_about_course.html.erb
  app/views/publish/courses/preview/_about_schools.html.erb
  app/views/publish/courses/preview/_about_the_provider.html.erb
  app/views/publish/courses/preview/_advice.html.erb
  app/views/publish/courses/preview/_apply.html.erb
  app/views/publish/courses/preview/_contact_details.html.erb
  app/views/publish/courses/preview/_entry_requirements_qualifications.html.erb
  app/views/publish/courses/preview/_fees.html.erb
  app/views/publish/courses/preview/_fees_and_financial_support.html.erb
  app/views/publish/courses/preview/_international_students.html.erb
  app/views/publish/courses/preview/_interview_process.html.erb
  app/views/publish/courses/preview/_qualification.html.erb
  app/views/publish/courses/preview/_salary.html.erb
  app/views/publish/courses/preview/_train_with_disabilities.html.erb
  app/views/publish/courses/preview/financial_support/_bursary.html.erb
  app/views/publish/courses/preview/financial_support/_loan.html.erb
  app/views/publish/courses/preview/financial_support/_placeholder.html.erb
  app/views/publish/courses/preview/financial_support/_salaried.html.erb
  app/views/publish/courses/preview/financial_support/_scholarship_and_bursary.html.erb
  app/views/publish/courses/preview/placement/_hei.html.erb
  app/views/publish/courses/preview/placement/_scitt.html.erb
  app/views/publish/courses/preview/qualification/_pgce.html.erb
  app/views/publish/courses/preview/qualification/_pgce_with_qts.html.erb
  app/views/publish/courses/preview/qualification/_pgde.html.erb
  app/views/publish/courses/preview/qualification/_pgde_with_qts.html.erb
  app/views/publish/courses/preview/qualification/_qts.html.erb
  app/views/publish/courses/status_panel/_unpublished.html.erb
  app/webpacker/packs/application.js
  app/webpacker/scripts/locations-map.js
  app/webpacker/scripts/map-popup.js
  app/webpacker/styles/_advice.scss
  app/webpacker/styles/_description-list.scss
  app/webpacker/styles/_inset-text.scss
  app/webpacker/styles/_list.scss
  app/webpacker/styles/application.scss
  config/routes.rb
  config/settings.yml
  spec/decorators/course_decorator_spec.rb
  spec/factories/course_enrichments.rb
  spec/factories/subjects/secondary_subjects.rb
  spec/features/publish/viewing_a_course_preview_spec.rb
  spec/support/feature_helpers/publish_pages.rb
  spec/support/page_objects/publish/course_preview.rb
Labels: deploy

#2552 Update gmp in Dockerfile to fix vulnerability
  Dockerfile
Labels: Devops, deploy

#2553 [596] Port over degree requirements flow
  app/components/degree_row_content_component/view.html.erb
  app/controllers/publish/courses/degrees/grade_controller.rb
  app/controllers/publish/courses/degrees/start_controller.rb
  app/controllers/publish/courses/degrees/subject_requirements_controller.rb
  app/forms/publish/degree_grade_form.rb
  app/forms/publish/degree_start_form.rb
  app/forms/publish/subject_requirement_form.rb
  app/models/course.rb
  app/views/publish/courses/_description_content.html.erb
  app/views/publish/courses/degrees/grade/edit.html.erb
  app/views/publish/courses/degrees/start/edit.html.erb
  app/views/publish/courses/degrees/subject_requirements/edit.html.erb
  config/routes.rb
  spec/components/degree_row_content_component/view_preview.rb
  spec/components/degree_row_content_component/view_spec.rb
  spec/features/publish/courses/editing_degree_requirements_spec.rb
  spec/models/course_spec.rb
  spec/support/feature_helpers/publish_pages.rb
  spec/support/page_objects/publish/degree_grade.rb
  spec/support/page_objects/publish/degree_start.rb
  spec/support/page_objects/publish/degree_subject_requirement.rb
Labels: deploy

#2564 [0597] Migrate GCSEs and equivalency tests
  app/components/gcse_preview_component/view.html.erb
  app/components/gcse_row_content_component/view.html.erb
  app/controllers/publish/courses/gcse_requirements_controller.rb
  app/forms/publish/gcse_requirements_form.rb
  app/views/publish/courses/_description_content.html.erb
  app/views/publish/courses/gcse_requirements/edit.html.erb
  config/routes.rb
  spec/components/gcse_row_content_component/view_preview.rb
  spec/components/gcse_row_content_component/view_spec.rb
  spec/features/publish/courses/gcse_equivalency_spec.rb
  spec/forms/publish/gcse_requirements_form_spec.rb
  spec/support/feature_helpers/publish_pages.rb
  spec/support/page_objects/publish/courses/gcse_requirements_page.rb
Labels: deploy

#2547 [618] Migrate Courses - Updating age range
  app/controllers/publish/courses/age_range_controller.rb
  app/forms/publish/age_range_form.rb
  app/policies/course_policy.rb
  app/views/publish/courses/_basic_details_tab.html.erb
  app/views/publish/courses/age_range/edit.html.erb
  config/locales/en.yml
  config/routes.rb
  spec/features/publish/courses/editing_age_range_spec.rb
  spec/forms/publish/age_range_form_spec.rb
  spec/support/feature_helpers/publish_pages.rb
  spec/support/page_objects/publish/courses/course_age_range_edit.rb
Labels: deploy

#2571 [0612] Fixed duplicated page title
  app/views/publish/providers/locations/index.html.erb
Labels: deploy

#2566 [619] Port over outcome editing for course
  app/models/concerns/publish/course_basic_detail_concern.rb
  app/views/publish/courses/_basic_details_tab.html.erb
  app/views/publish/courses/outcome/_form_fields.html.erb
  app/views/publish/courses/outcome/edit.html.erb
  config/routes.rb
  spec/features/publish/courses/editing_course_outcome_spec.rb
  spec/support/feature_helpers/publish_pages.rb
  spec/support/page_objects/publish/courses/outcome_edit_page.rb
  spec/support/page_objects/sections/qualification.rb
Labels: deploy

#2570 [0617] Migrate course updating subjects
  app/controllers/publish/courses/modern_languages_controller.rb
  app/controllers/publish/courses/subjects_controller.rb
  app/decorators/course_decorator.rb
  app/services/courses/assign_program_type_service.rb
  app/services/courses/assign_subjects_service.rb
  app/services/courses/creation_service.rb
  app/views/publish/courses/_basic_details_tab.html.erb
  app/views/publish/courses/modern_languages/edit.html.erb
  app/views/publish/courses/modern_languages/new.html.erb
  app/views/publish/courses/subjects/edit.html.erb
  app/views/publish/courses/subjects/new.html.erb
  config/routes.rb
  spec/features/publish/courses/editing_mordern_languages_spec.rb
  spec/features/publish/courses/editing_subject_spec.rb
  spec/features/publish/courses/new_mordern_languages_spec.rb
  spec/services/courses/assign_subjects_service_spec.rb
  spec/services/courses/creation_service_spec.rb
  spec/support/feature_helpers/publish_pages.rb
  spec/support/page_objects/publish/courses/modern_languages_edit_page.rb
  spec/support/page_objects/publish/courses/subjects_edit_page.rb
Labels: deploy

#2574 [616] Port the withdrawing courses flow
  app/controllers/publish/courses/withdrawals_controller.rb
  app/controllers/publish/publish_controller.rb
  app/controllers/publish/users_controller.rb
  app/forms/publish/course_withdrawal_form.rb
  app/views/publish/courses/_description_status_panel.html.erb
  app/views/publish/courses/withdrawals/edit.html.erb
  app/views/publish/providers/access_requests/new.html.erb
  app/webpacker/styles/_link.scss
  app/webpacker/styles/application.scss
  config/locales/en.yml
  config/routes.rb
  spec/features/publish/courses/withdrawing_a_course_spec.rb
  spec/features/publish/editing_vacancies_spec.rb
  spec/support/feature_helpers/course_steps.rb
  spec/support/feature_helpers/publish_pages.rb
  spec/support/page_objects/publish/courses/withdrawal_page.rb
Labels: deploy

#2575 Fix libretls vulnerability CVE-2022-0778
  Dockerfile
Labels: Devops

#2562 Refactor deployment workflows
  .github/actions/deploy/action.yml
  .github/workflows/build-and-deploy.yml
  .github/workflows/delete-review-app.yml
  .github/workflows/deploy.yml
Labels: Devops, deploy

#2580 Use job environment to update deployment status
  .github/actions/deploy/action.yml
  .github/workflows/build-and-deploy.yml
  .github/workflows/delete-review-app.yml
  .github/workflows/deploy.yml
Labels: Devops, deploy

#2584 Refactor smoke test workflow as a reusable action
  .github/actions/deploy/action.yml
  .github/actions/smoke-test/action.yml
  .github/workflows/smoke-test.yml
Labels: Devops, deploy

#2589 Removed dependabot conditions in build workflows
  .github/workflows/build-and-deploy.yml
  .github/workflows/build-nocache.yml
Labels: deploy

#2591 [0803] Migrate notifications logic for when courses are changed
  app/controllers/publish/courses/modern_languages_controller.rb
  app/controllers/publish/courses/subjects_controller.rb
  app/forms/publish/base_course_form.rb
  app/forms/publish/course_location_form.rb
  app/forms/publish/course_subjects_form.rb
  app/forms/publish/course_vacancies_form.rb
  app/forms/publish/course_withdrawal_form.rb
  config/locales/en.yml
  spec/features/publish/courses/editing_modern_languages_spec.rb
  spec/forms/publish/base_course_form_spec.rb
  spec/forms/publish/course_location_form_spec.rb
  spec/forms/publish/course_subjects_form_spec.rb
  spec/forms/publish/course_vacancies_form_spec.rb
  spec/forms/publish/course_withdrawal_form_spec.rb
Labels: deploy
