Repository DFE-Digital/publish-teacher-training, pull requests merged in 2022-07, with the labels that each got.

#2799 #228 add academic year
  app/models/course.rb
  app/views/publish/courses/_basic_details_tab.html.erb
  spec/features/publish/viewing_a_course_details_spec.rb
  spec/models/course_spec.rb
Labels: deploy

#2804 [xxx] Turn on GA in prod
  app/views/cookie_preferences/show.html.erb
  app/views/publish/users/index.html.erb
  config/settings.yml
  config/settings/development.yml
  config/settings/qa.yml
  spec/support/page_objects/publish/allocations/request/number_of_places.rb
  spec/support/page_objects/publish/allocations/request/who_are_you_requesting_a_course_for.rb
  spec/support/page_objects/publish/provider_contact_details_edit.rb
  spec/support/page_objects/publish/provider_details_edit.rb
  spec/support/page_objects/publish/provider_users.rb
  spec/support/page_objects/publish/provider_visa_sponsorships.rb
  spec/support/page_objects/publish/request_access_new.rb
  spec/support/page_objects/support/allocation_uplift_edit.rb
  spec/support/page_objects/support/allocation_uplift_new.rb
  spec/support/page_objects/support/provider/course_edit.rb
  spec/support/page_objects/support/provider_edit.rb
  spec/support/page_objects/support/provider_new.rb
  spec/support/page_objects/support/user_edit.rb
  spec/support/page_objects/support/user_show.rb
Labels: deploy

#2807 [0237] New guidance content
  app/controllers/pages_controller.rb
  app/views/layouts/_footer.html.erb
  app/views/pages/course_summary_examples.erb
  app/views/pages/guidance.html.erb
  app/views/pages/how_to_use_this_service.html.erb
  app/views/pages/writing_descriptions_for_publish_teacher_training_courses.erb
  app/views/publish/courses/course_information/edit.html.erb
  config/routes.rb
  spec/features/view_pages_spec.rb
Labels: deploy

#2806 [258] Add PE with Ebacc subject
  app/services/subjects/creator_service.rb
  db/migrate/20220705072950_add_pe_with_ebacc_to_subjects.rb
  db/schema.rb
  docs/database-diagram.jpg
  spec/controllers/api/public/v1/subjects_controller_spec.rb
  spec/factories/subjects/secondary_subjects.rb
  spec/models/concerns/courses/edit_options_spec.rb
  spec/requests/api/v3/subjects/index_spec.rb
Labels: deploy

#2813 Update the get-image-tag recipe
  Makefile
Labels: Devops, deploy

#2814 [0272] Amended course summary examples
  app/assets/stylesheets/application.scss
  app/views/pages/course_summary_examples.erb
Labels: deploy

#2819 Activate rollover in production
  config/settings.yml
  config/settings/qa.yml
  config/settings/staging.yml
  spec/components/title_bar/view_spec.rb
  spec/features/publish/accepting_terms_spec.rb
  spec/features/publish/primary_nav_spec.rb
Labels: deploy

#2820 Fix spacing for academic year
  app/views/publish/courses/_basic_details_tab.html.erb
Labels: deploy

#2816 [276] Fix access requests logic
  app/controllers/publish/access_requests_controller.rb
  spec/features/support/access_requests/managing_requests_spec.rb
Labels: deploy

#2825 Update azurerm provider to 3.12.0
  terraform/.terraform.lock.hcl
  terraform/terraform.tf
Labels: Devops, deploy

#2818 Refactor and add separator to title bar items
  app/assets/stylesheets/components/_title-bar.scss
  app/components/title_bar/view.html.erb
  app/components/title_bar/view.rb
Labels: deploy

#2828 [233] Surface financial incentives on course page
  app/decorators/course_decorator.rb
  app/views/publish/courses/_description_content.html.erb
  config/locales/en.yml
  spec/decorators/course_decorator_spec.rb
  spec/factories/subjects/secondary_subjects.rb
  spec/features/publish/viewing_a_course_spec.rb
  spec/support/page_objects/publish/provider_courses_show.rb
Labels: deploy

#2838 [240] Viewing provider users
  app/components/header/view.html.erb
  app/controllers/support/providers/users_controller.rb
  app/models/user.rb
  app/views/layouts/provider_record.html.erb
  app/views/support/providers/users.html.erb
  app/views/support/providers/users/_provider_user_list.html.erb
  app/views/support/providers/users/index.html.erb
  app/views/support/providers/users/show.html.erb
  config/locales/en.yml
  config/routes.rb
  spec/features/support/providers/deleting_user_from_provider_spec.rb
  spec/features/support/providers/viewing_a_user_spec.rb
  spec/models/user_spec.rb
  spec/support/page_objects/support/provider_user_show.rb
Labels: deploy

#2844 [0241] Support removing provider users
  app/controllers/support/providers/users_controller.rb
  app/mailers/remove_user_from_organisation_mailer.rb
  app/services/user_associations_service/delete.rb
  app/views/support/providers/users/delete.html.erb
  app/views/support/providers/users/show.html.erb
  config/locales/en.yml
  config/routes.rb
  config/settings.yml
  spec/features/support/providers/deleting_user_from_provider_spec.rb
  spec/features/support/providers/removing_user_from_provider_spec.rb
  spec/features/support/providers/viewing_a_user_spec.rb
  spec/mailers/remove_user_from_organisation_mailer_spec.rb
  spec/services/user_associations_service/delete_spec.rb
  spec/support/page_objects/support/provider_user_delete.rb
  spec/support/page_objects/support/provider_user_show.rb
  spec/support/page_objects/support/provider_users_index.rb
Labels: deploy

#2829 227 manual draft rollover
  app/assets/stylesheets/_inset-text.scss
  app/controllers/publish/courses/deletions_controller.rb
  app/controllers/publish/courses/draft_rollover_controller.rb
  app/controllers/publish/courses_controller.rb
  app/forms/publish/course_deletion_form.rb
  app/forms/publish/course_rollover_form.rb
  app/models/course.rb
  app/views/publish/courses/_basic_details_tab.html.erb
  app/views/publish/courses/_course_button_panel.html.erb
  app/views/publish/courses/_rolled_over_link.html.erb
  app/views/publish/courses/course_button_panel/_unpublished.html.erb
  app/views/publish/courses/details.html.erb
  app/views/publish/courses/draft_rollover/edit.html.erb
  app/views/publish/courses/show.html.erb
  config/locales/en.yml
  config/routes.rb
  spec/features/publish/viewing_a_course_spec.rb
  spec/forms/publish/course_rollover_form_spec.rb
  spec/spec_helper.rb
  spec/support/page_objects/publish/draft_rollover.rb
  spec/support/page_objects/publish/provider_courses_show.rb
  spec/support/page_objects/sections/course_button_panel.rb
Labels: deploy

#2839 229 add user to org via support
  app/controllers/support/providers/users_check_controller.rb
  app/controllers/support/providers/users_controller.rb
  app/forms/form.rb
  app/forms/support/user_form.rb
  app/services/user_store.rb
  app/views/support/providers/users/delete.html.erb
  app/views/support/providers/users/index.html.erb
  app/views/support/providers/users/new.html.erb
  app/views/support/providers/users/show.html.erb
  app/views/support/providers/users_check/show.html.erb
  config/initializers/redis.rb
  config/locales/en.yml
  config/routes.rb
  spec/features/support/providers/users/adding_user_to_provider_spec.rb
  spec/forms/support/user_form_spec.rb
  spec/services/user_store_spec.rb
  spec/support/page_objects/support/provider/user/users_check.rb
  spec/support/page_objects/support/provider/user/users_new.rb
Labels: deploy

#2849 [0336] Fixed removing user errors out
  app/models/user.rb
  spec/models/user_spec.rb
Labels: deploy

#2850 #325 add preview link to unpublished and withdrawn
  app/views/publish/courses/course_button_panel/_unpublished.html.erb
  app/views/publish/courses/course_button_panel/_withdrawn.html.erb
  spec/features/publish/viewing_a_course_spec.rb
  spec/support/page_objects/sections/course_button_panel.rb
Labels: deploy

#2851 Add edit provider user journey
  app/controllers/support/providers/users_controller.rb
  app/views/support/providers/users/edit.html.erb
  app/views/support/providers/users/show.html.erb
  config/locales/en.yml
  config/routes.rb
  spec/features/support/providers/editing_a_user_from_a_provider_spec.rb
  spec/support/page_objects/support/provider_user_edit.rb
  spec/support/page_objects/support/provider_user_show.rb
Labels: deploy

#2858 Remove StatusCake alerts
  terraform/workspace_variables/production.tfvars.json
  terraform/workspace_variables/qa.tfvars.json
  terraform/workspace_variables/rollover.tfvars.json
  terraform/workspace_variables/sandbox.tfvars.json
  terraform/workspace_variables/staging.tfvars.json
Labels: Devops, deploy

#2856 Update Terraform providers
  docs/disaster-recovery.md
  terraform/.terraform.lock.hcl
  terraform/modules/paas/providers.tf
  terraform/modules/statuscake/providers.tf
  terraform/modules/statuscake/resources.tf
  terraform/terraform.tf
  terraform/workspace_variables/production.tfvars.json
  terraform/workspace_variables/qa.tfvars.json
  terraform/workspace_variables/rollover.tfvars.json
  terraform/workspace_variables/sandbox.tfvars.json
  terraform/workspace_variables/staging.tfvars.json
Labels: deploy

#2868 Configures version updates for GitHub Actions
  .github/dependabot.yml
Labels: Devops

#2867 Scope routes based on recruitment cycle users list
  app/components/filters/view.rb
  app/controllers/support/users_controller.rb
  app/views/layouts/user_record.html.erb
  app/views/support/_menu.html.erb
  app/views/support/users/_users.html.erb
  app/views/support/users/edit.html.erb
  app/views/support/users/index.html.erb
  app/views/support/users/new.html.erb
  app/views/support/users/show.html.erb
  config/routes.rb
  spec/features/support/filters/user_filters_spec.rb
  spec/features/support/users/creating_a_new_user_spec.rb
  spec/features/support/users/deleting_a_user_spec.rb
  spec/features/support/users/deleting_user_from_provider_spec.rb
  spec/features/support/users/editing_a_user_spec.rb
  spec/features/support/users/users_list_spec.rb
  spec/support/page_objects/support/user_edit.rb
  spec/support/page_objects/support/user_new.rb
  spec/support/page_objects/support/user_show.rb
  spec/support/page_objects/support/user_show_providers.rb
  spec/support/page_objects/support/users_index.rb
Labels: deploy

#2878 Scope routes based on recruitment cycle allocations
  app/components/allocation_record_card/view.html.erb
  app/components/allocation_record_card/view.rb
  app/components/filters/view.rb
  app/controllers/support/allocation_uplifts_controller.rb
  app/controllers/support/allocations_controller.rb
  app/views/support/_menu.html.erb
  app/views/support/allocation_uplifts/edit.html.erb
  app/views/support/allocation_uplifts/new.html.erb
  app/views/support/allocations/index.html.erb
  app/views/support/allocations/show.html.erb
  config/routes.rb
  spec/components/allocation_record_card/view_preview.rb
  spec/components/allocation_record_card/view_spec.rb
  spec/features/support/allocations/allocation_uplift_edit_spec.rb
  spec/features/support/allocations/allocation_uplift_new_spec.rb
  spec/features/support/allocations/allocations_list_spec.rb
  spec/features/support/allocations/allocations_show_spec.rb
  spec/features/support/filters/allocation_filter_spec.rb
  spec/support/page_objects/support/allocation_uplift_edit.rb
  spec/support/page_objects/support/allocation_uplift_new.rb
  spec/support/page_objects/support/allocations_index.rb
  spec/support/page_objects/support/allocations_show.rb
Labels: deploy

#2885 342 add cycle switcher to support console
  app/components/support_title_bar/view.html.erb
  app/components/support_title_bar/view.rb
  app/controllers/support/recruitment_cycle_controller.rb
  app/views/layouts/application.html.erb
  app/views/support/recruitment_cycle/index.html.erb
  config/routes.rb
  spec/components/support_title_bar/view_preview.rb
  spec/components/support_title_bar/view_spec.rb
  spec/features/support/switching_between_recruitment_cycles_spec.rb
  spec/support/page_objects/support/recruitment_cycle_index.rb
Labels: deploy
