Repository DFE-Digital/publish-teacher-training, pull requests merged in 2023-04, with the labels that each got.

#3457 236 azure dns migration
  Makefile
  global_config/publish-domain.sh
  terraform/custom_domains/environment_domains/.terraform.lock.hcl
  terraform/custom_domains/environment_domains/main.tf
  terraform/custom_domains/environment_domains/terraform.tf
  terraform/custom_domains/environment_domains/variables.tf
  terraform/custom_domains/environment_domains/workspace_variables/publish_pentest.tfvars.json
  terraform/custom_domains/environment_domains/workspace_variables/publish_pentest_backend.tfvars
  terraform/custom_domains/environment_domains/workspace_variables/publish_production.tfvars.json
  terraform/custom_domains/environment_domains/workspace_variables/publish_production_backend.tfvars
  terraform/custom_domains/environment_domains/workspace_variables/publish_qa.tfvars.json
  terraform/custom_domains/environment_domains/workspace_variables/publish_qa_backend.tfvars
  terraform/custom_domains/environment_domains/workspace_variables/publish_sandbox.tfvars.json
  terraform/custom_domains/environment_domains/workspace_variables/publish_sandbox_backend.tfvars
  terraform/custom_domains/environment_domains/workspace_variables/publish_staging.tfvars.json
  terraform/custom_domains/environment_domains/workspace_variables/publish_staging_backend.tfvars
  terraform/custom_domains/infrastructure/.terraform.lock.hcl
  terraform/custom_domains/infrastructure/main.tf
  terraform/custom_domains/infrastructure/terraform.tf
  terraform/custom_domains/infrastructure/variables.tf
  terraform/custom_domains/infrastructure/workspace_variables/publish.tfvars.json
  terraform/custom_domains/infrastructure/workspace_variables/publish_backend.tfvars
Labels: Devops, terraform

#3478 [1205] Amended the form to ms version
  config/settings.yml
Labels: deploy

#3466 1119 edit locations flow
  app/controllers/publish/providers/schools_check_controller.rb
  app/controllers/publish/providers/schools_controller.rb
  app/models/site.rb
  app/views/publish/providers/schools/_form.html.erb
  app/views/publish/providers/schools/_school.html.erb
  app/views/publish/providers/schools/delete.html.erb
  app/views/publish/providers/schools/edit.html.erb
  app/views/publish/providers/schools/new.html.erb
  app/views/publish/providers/schools/show.html.erb
  app/views/publish/providers/schools_check/show.html.erb
  app/views/support/providers/schools_check/show.html.erb
  app/views/support/schools/_form.html.erb
  config/locales/en.yml
  config/routes/publish.rb
  spec/features/publish/managing_schools_spec.rb
  spec/features/support/providers/schools/add_school_to_provider_spec.rb
  spec/features/support/providers/schools/edit_school_spec.rb
  spec/forms/support/school_form_spec.rb
  spec/models/site_spec.rb
  spec/support/page_objects/publish/provider/schools_check.rb
  spec/support/page_objects/publish/school_delete.rb
  spec/support/page_objects/publish/school_edit.rb
  spec/support/page_objects/publish/school_new.rb
  spec/support/page_objects/publish/school_show.rb
  spec/support/page_objects/sections/edit_school_form.rb
Labels: deploy

#3474 1154 course preview training with disabilities and other needs
  app/components/find/courses/contents_component/view.html.erb
  app/controllers/publish/providers_controller.rb
  app/views/find/courses/_train_with_disabilities.html.erb
  app/views/publish/courses/preview.html.erb
  app/views/publish/providers/about.html.erb
  spec/features/publish/viewing_a_course_preview_spec.rb
Labels: deploy

#3475 [1162] Implement School Non JS search flow
  app/components/publish/schools/search_result_title_component.html.erb
  app/components/publish/schools/search_result_title_component.rb
  app/controllers/publish/providers/school_search_controller.rb
  app/forms/publish/schools/search_form.rb
  app/forms/publish/schools/select_form.rb
  app/helpers/publish/school_helper.rb
  app/models/gias_school.rb
  app/services/publish/schools/search_service.rb
  app/services/strip_punctuation_service.rb
  app/views/publish/providers/school_search/new.html.erb
  app/views/publish/providers/school_search/results.html.erb
  app/views/publish/providers/schools/_form.html.erb
  app/views/publish/providers/schools/edit.html.erb
  app/views/publish/providers/schools/index.html.erb
  app/views/publish/providers/schools/new.html.erb
  app/views/support/schools/_form.html.erb
  config/analytics_blocklist.yml
  config/environments/development.rb
  config/locales/en.yml
  config/routes/publish.rb
  config/settings.yml
  config/settings/development.yml
  config/settings/review.yml
  db/migrate/20230404153345_add_searchable_to_gias_schools.rb
  db/schema.rb
  docs/database-diagram.jpg
  spec/components/publish/schools/search_result_title_component_spec.rb
  spec/components/publish/schools/search_result_title_preview.rb
  spec/factories/gias_schools.rb
  spec/features/publish/searching_for_a_school_spec.rb
  spec/forms/publish/schools/search_form_spec.rb
  spec/forms/publish/schools/select_form_spec.rb
  spec/models/gias_school_spec.rb
  spec/services/publish/schools/search_service_spec.rb
  spec/services/strip_punctuation_service_spec.rb
Labels: deploy

#3491 Add guidance pages to the how to use this service page
  app/controllers/pages_controller.rb
  app/views/pages/add_an_organisation.html.erb
  app/views/pages/add_and_remove_users.html.erb
  app/views/pages/change_an_accredited_provider_relationship.html.erb
  app/views/pages/course_summary_examples.erb
  app/views/pages/help_writing_course_descriptions.html.erb
  app/views/pages/how_to_use_this_service.html.erb
  app/views/pages/roll_over_courses_to_a_new_recruitment_cycle.html.erb
  config/locales/en.yml
  config/routes/publish.rb
  spec/features/publish/how_to_use_this_service_spec.rb
  spec/features/view_pages_spec.rb
Labels: deploy

#3489 [xxx] Update wording based on prototype for training partners
  app/helpers/navigation_bar_helper.rb
  app/views/publish/training_providers/courses/index.html.erb
  app/views/publish/training_providers/index.html.erb
  config/locales/en.yml
  spec/features/publish/primary_nav_spec.rb
  spec/support/page_objects/publish/primary_nav.rb
Labels: deploy

#3497 236 find pub dns fixes
  terraform/custom_domains/environment_domains/workspace_variables/find_pentest.tfvars.json
  terraform/custom_domains/environment_domains/workspace_variables/find_production.tfvars.json
  terraform/custom_domains/environment_domains/workspace_variables/find_qa.tfvars.json
  terraform/custom_domains/environment_domains/workspace_variables/find_sandbox.tfvars.json
  terraform/custom_domains/environment_domains/workspace_variables/find_staging.tfvars.json
  terraform/custom_domains/environment_domains/workspace_variables/publish_pentest.tfvars.json
  terraform/custom_domains/environment_domains/workspace_variables/publish_production.tfvars.json
  terraform/custom_domains/environment_domains/workspace_variables/publish_qa.tfvars.json
  terraform/custom_domains/environment_domains/workspace_variables/publish_sandbox.tfvars.json
  terraform/custom_domains/environment_domains/workspace_variables/publish_staging.tfvars.json
  terraform/custom_domains/infrastructure/workspace_variables/find.tfvars.json
Labels: Devops, terraform

#3500 [xxx] Link selection of GiasSchool to form
  app/controllers/publish/providers/schools_controller.rb
  app/models/gias_school.rb
  docs/database-diagram.jpg
  spec/features/publish/searching_for_a_school_spec.rb
  spec/models/gias_school_spec.rb
Labels: deploy

#3496 [1194] Support new provider form
  app/controllers/support/providers/onboardings_controller.rb
  app/views/support/providers/index.html.erb
  app/views/support/providers/onboardings/new.html.erb
  config/locales/en.yml
  config/routes/support.rb
  config/settings.yml
  config/settings/development.yml
  config/settings/review.yml
  spec/features/support/providers/creating_a_new_provider_spec.rb
  spec/features/support/providers/providers_list_spec.rb
Labels: deploy

#3504 [1222] Plumbing to implement AP search on providers
  app/models/concerns/vector_searchable.rb
  app/models/gias_school.rb
  app/models/provider.rb
  app/services/publish/accredited_providers/search_service.rb
  config/analytics_blocklist.yml
  db/migrate/20230418112219_add_searchable_to_providers.rb
  db/schema.rb
  docs/database-diagram.jpg
  spec/models/provider_spec.rb
  spec/services/publish/accredited_providers/search_service_spec.rb
Labels: deploy

#3505 Tighten UKPRN validation
  app/forms/publish/provider_contact_form.rb
  app/forms/support/provider_form.rb
  app/models/provider.rb
  app/validators/ukprn_format_validator.rb
  config/locales/en.yml
  spec/factories/providers.rb
  spec/forms/support/provider_form_spec.rb
  spec/models/provider_spec.rb
  spec/validators/ukprn_format_validator_spec.rb
Labels: deploy

#3510 Remove incorrectly displayed hint text
  app/views/publish/courses/accredited_body/_provider_search_field.html.erb
Labels: deploy

#3506 1120 js school search
  app/controllers/api/school_suggestions_controller.rb
  app/controllers/publish/providers/school_search_controller.rb
  app/javascript/publish/__snapshots__/autocomplete.spec.js.snap
  app/javascript/publish/application.js
  app/javascript/publish/autocomplete.js
  app/javascript/publish/autocomplete.spec.js
  app/views/publish/providers/school_search/new.html.erb
  config/locales/en.yml
  config/routes/api.rb
  spec/controllers/api/school_suggestions_controller_spec.rb
  spec/features/publish/searching_for_a_school_spec.rb
Labels: deploy

#3519 [xxxx] Amended `course_preview_missing_information` to be true
  config/settings.yml
  config/settings/development.yml
  config/settings/review.yml
  spec/components/find/courses/about_schools_component/view_spec.rb
Labels: deploy

#3520 [xxx] Switch on Gias school search in QA
  app/views/publish/providers/schools/new.html.erb
  config/settings/qa.yml
Labels: deploy

#3518 [1222] Support add edit accrediting provider Step 1 non JS
  app/components/publish/schools/search_result_title_component.rb
  app/components/search_result_title_component.html.erb
  app/components/search_result_title_component.rb
  app/components/tab_navigation.html.erb
  app/controllers/publish/providers/school_search_controller.rb
  app/controllers/support/providers/accredited_provider_search_controller.rb
  app/controllers/support/providers/accredited_providers_controller.rb
  app/forms/accredited_provider_search_form.rb
  app/forms/accredited_provider_select_form.rb
  app/models/provider.rb
  app/services/accredited_providers/search_service.rb
  app/services/publish/accredited_providers/search_service.rb
  app/views/layouts/provider_record.html.erb
  app/views/support/providers/accredited_provider_search/new.html.erb
  app/views/support/providers/accredited_provider_search/results.html.erb
  app/views/support/providers/accredited_providers/index.html.erb
  app/views/support/providers/users/index.html.erb
  config/locales/en.yml
  config/routes/support.rb
  config/settings.yml
  config/settings/development.yml
  config/settings/review.yml
  spec/components/publish/schools/search_result_title_component_spec.rb
  spec/components/publish/schools/search_result_title_preview.rb
  spec/components/search_result_title_component_spec.rb
  spec/components/search_result_title_preview.rb
  spec/features/support/providers/accredited_provider_search/searching_for_an_accredited_provider_spec.rb
  spec/forms/accredited_provider_search_form_spec.rb
  spec/forms/accredited_provider_select_form_spec.rb
  spec/services/accredited_providers/search_service_spec.rb
  spec/services/publish/accredited_providers/search_service_spec.rb
Labels: deploy

#3524 [xxx] Turn on Gias search for prod
  app/javascript/find/autocomplete.js
  app/javascript/find/autocomplete.spec.js
  app/javascript/publish/autocomplete.js
  app/javascript/publish/autocomplete.spec.js
  app/javascript/utils/request_helper.js
  app/javascript/utils/request_helper.spec.js
  app/views/publish/providers/school_search/new.html.erb
  config/settings.yml
  config/settings/development.yml
  config/settings/qa.yml
  config/settings/review.yml
  spec/features/publish/managing_schools_spec.rb
  spec/features/publish/searching_for_a_school_spec.rb
Labels: deploy

#3526 Increase staging webapp memory
  terraform/workspace_variables/staging.tfvars.json
Labels: Devops

#3533 [1257] add validations to form
  app/forms/publish/provider_contact_form.rb
  config/locales/en.yml
  spec/forms/publish/provider_contact_form_spec.rb
Labels: deploy

#3534 [1254] Add guard to prevent rendering on Find
  app/components/course_preview/missing_information_component.rb
  app/components/find/courses/about_schools_component/view.html.erb
  app/components/find/courses/about_schools_component/view.rb
  app/components/find/courses/entry_requirements_component/view.html.erb
  app/components/find/courses/entry_requirements_component/view.rb
  app/components/find/courses/fees_component/view.html.erb
  app/components/find/courses/fees_component/view.rb
  app/helpers/preview_helper.rb
  app/views/find/courses/_about_course.html.erb
  app/views/find/courses/_about_the_provider.html.erb
  app/views/find/courses/_train_with_disabilities.html.erb
  spec/components/course_preview/missing_information_component_preview.rb
  spec/components/course_preview/missing_information_component_spec.rb
Labels: deploy

#3527 Tighten telephone validation
  app/forms/publish/provider_contact_form.rb
  app/forms/support/provider_contact_form.rb
  app/models/provider.rb
  app/validators/phone_validator.rb
  config/locales/en.yml
  spec/forms/publish/provider_contact_form_spec.rb
  spec/forms/support/provider_contact_form_spec.rb
  spec/models/contact_spec.rb
  spec/models/provider/validation_spec.rb
  spec/validators/phone_validator_spec.rb
Labels: deploy
