Repository DFE-Digital/publish-teacher-training, pull requests merged in 2023-10, with the labels that each got.

#3867 Scrub content on search filters relating to FIs - mirroring what we did in 2021 and 2022
  app/helpers/find/subject_helper.rb
  spec/helpers/find/subject_helper_spec.rb
Labels: deploy_v2

#3871 Hide and show find on London timezone
  app/services/find/cycle_timetable.rb
  spec/controllers/find/courses_controller_spec.rb
  spec/features/find/cookie_preferences_spec.rb
  spec/features/find/maintainance_page_spec.rb
  spec/features/find/result_page_filters/applications_open_spec.rb
  spec/features/find/result_page_filters/degree_required_spec.rb
  spec/features/find/result_page_filters/engineers_teach_physics_spec.rb
  spec/features/find/result_page_filters/qualifications_spec.rb
  spec/features/find/result_page_filters/salary_spec.rb
  spec/features/find/result_page_filters/send_spec.rb
  spec/features/find/result_page_filters/study_type_spec.rb
  spec/features/find/result_page_filters/visa_spec.rb
  spec/features/find/search/across_england/further_education_spec.rb
  spec/features/find/search/across_england/primary_spec.rb
  spec/features/find/search/across_england/secondary_spec.rb
  spec/features/find/search/course_results_spec.rb
  spec/features/find/search/editing_a_search_spec.rb
  spec/features/find/search/location_options_spec.rb
  spec/features/find/search/provider_options_spec.rb
  spec/features/find/search/viewing_a_course_spec.rb
  spec/features/find/sorted_by_filter_spec.rb
  spec/features/publish/courses/publishing_a_course_spec.rb
  spec/requests/find/locations_suggestions_spec.rb
  spec/requests/find/sitemaps_spec.rb
Labels: deploy_v2

#3856 [698] End Rollover `2023`
  app/forms/publish/course_fee_form.rb
  app/helpers/navigation_bar_helper.rb
  app/helpers/recruitment_cycle_helper.rb
  app/models/course.rb
  app/models/course_enrichment.rb
  app/services/courses/assign_program_type_current_cycle_service.rb
  app/services/workflow_step_service.rb
  app/views/publish/courses/_basic_details_tab.html.erb
  app/views/publish/courses/confirmation.html.erb
  app/views/publish/courses/fees/edit.html.erb
  app/views/publish/courses/index.html.erb
  config/settings.yml
  spec/features/publish/add_course_button_spec.rb
  spec/features/publish/course_confirmation_spec.rb
  spec/features/publish/courses/editing_study_sites_spec.rb
  spec/features/publish/courses/new_apprenticeship_spec.rb
  spec/features/publish/courses/new_visa_sponsorship_spec.rb
  spec/features/publish/viewing_courses_spec.rb
  spec/features/support/providers/courses/editing_a_course_spec.rb
  spec/models/recruitment_cycle_spec.rb
  spec/services/courses/assign_program_type_current_cycle_service_spec.rb
  spec/services/user_associations_service/create_spec.rb
  spec/services/workflow_step_service_spec.rb
Labels: do not merge, deploy_v2

#3874 Set the financial support banner to use cycle timetable
  app/views/find/search/subjects/_secondary_subjects.html.erb
Labels: deploy_v2

#3875 Remove UCL from grade 5 requirements
  app/models/course.rb
  spec/components/find/courses/entry_requirements_component/view_spec.rb
Labels: deploy_v2

#3880 [2282] Fix provider name mapping for autocomplete
  app/helpers/find/provider_helper.rb
  spec/helpers/find/provider_helper_spec.rb
Labels: deploy_v2

#3881 Update non uk guidance link to not link to withdrawn guidance
  app/components/find/courses/financial_support/bursary_component/view.html.erb
  app/components/find/courses/financial_support/scholarship_and_bursary_component/view.html.erb
  app/views/find/courses/financial_support/_loan.html.erb
  config/locales/find.yml
Labels: deploy_v2

#3886 [723] Reduce AKS pod usage
  terraform/aks/workspace_variables/production_aks.tfvars.json
  terraform/aks/workspace_variables/sandbox_aks.tfvars.json
Labels: Devops

#3887 [2294] Fixed the ordering of conditions
  app/services/workflow_step_service.rb
  spec/services/workflow_step_service_spec.rb
Labels: deploy_v2

#3909 [823] Add visa sponsorship row on Find
  app/components/find/courses/summary_component/view.html.erb
  app/components/find/courses/summary_component/view.rb
  spec/components/find/courses/sumary_component/view_preview.rb
  spec/components/find/courses/sumary_component/view_spec.rb
Labels: deploy_v2
