Repository DFE-Digital/publish-teacher-training, pull requests merged in 2023-08, with the labels that each got.

#3774 Allow accredited providers to publish courses
  app/models/course.rb
  spec/features/publish/courses/2024_itt_provider_market_reform/publishing_a_course_as_an_accredited_provider_spec.rb
Labels: deploy_v2

#3773 [450] Fixes for the add user flow
  app/helpers/recruitment_cycle_helper.rb
  app/services/user_associations_service/create.rb
  spec/services/user_associations_service/create_spec.rb
Labels: deploy_v2

#3780 Add guard to handle no users
  app/services/user_associations_service/create.rb
  spec/services/user_associations_service/create_spec.rb
Labels: deploy_v2

#3765 [504] Production AKS migration prep
  terraform/aks/workspace_variables/production_aks.tfvars.json
  terraform/custom_domains/environment_domains/workspace_variables/find_production.tfvars.json
  terraform/custom_domains/environment_domains/workspace_variables/publish_production.tfvars.json
Labels: Devops, terraform

#3768 [504] Migrate production to AKS
  .github/actions/deploy_v2/action.yml
  .github/workflows/build-and-deploy.yml
  .github/workflows/database-restore.yml
  .github/workflows/deploy.yml
  .github/workflows/scheduled-aks-db-restore.yml
  .github/workflows/smoke-test.yml
  config/settings/production_aks.yml
  terraform/aks/workspace_variables/production_aks.tfvars.json
  terraform/custom_domains/environment_domains/workspace_variables/find_production.tfvars.json
  terraform/custom_domains/environment_domains/workspace_variables/publish_production.tfvars.json
Labels: Devops, github_actions, terraform, deploy_v2

#3778 [433] Enable editing of applications open date for draft courses
  app/controllers/publish/courses/applications_open_controller.rb
  app/views/publish/courses/_basic_details_tab.html.erb
  app/views/publish/courses/applications_open/_form_fields.html.erb
  app/views/publish/courses/applications_open/edit.html.erb
  app/views/publish/courses/applications_open/new.html.erb
  config/initializers/date_formats.rb
  config/locales/en.yml
  config/routes/publish.rb
  spec/features/publish/courses/editing_applications_open_spec.rb
  spec/features/publish/viewing_a_course_details_spec.rb
  spec/forms/edit_course_form_spec.rb
Labels: deploy_v2

#3779 [433] Enable editing of start date for draft courses
  app/controllers/publish/courses/start_date_controller.rb
  app/views/publish/courses/_basic_details_tab.html.erb
  app/views/publish/courses/start_date/edit.html.erb
  config/routes/publish.rb
  spec/features/publish/courses/editing_course_start_spec.rb
  spec/features/publish/viewing_a_course_details_spec.rb
Labels: deploy_v2

#3783 [412] Populate accredited provider list based on recruitment cycle
  app/controllers/api/accredited_provider_suggestions_controller.rb
  app/controllers/publish/providers/accredited_provider_search_controller.rb
  app/controllers/support/providers/accredited_provider_search_controller.rb
  app/forms/accredited_provider_search_form.rb
  app/javascript/publish/autocomplete/__snapshots__/accredited_provider.spec.js.snap
  app/javascript/publish/autocomplete/accredited_provider.js
  app/javascript/publish/autocomplete/accredited_provider.spec.js
  app/services/accredited_providers/search_service.rb
  app/views/publish/providers/accredited_provider_search/new.html.erb
  config/routes/api.rb
  spec/controllers/api/accredited_provider_suggestions_controller_spec.rb
  spec/services/accredited_providers/search_service_spec.rb
Labels: deploy_v2

#3790 [532] Make study sites non mandatory
  app/components/add_course_button.rb
  app/controllers/publish/courses/study_sites_controller.rb
  app/forms/publish/course_study_site_form.rb
  app/models/course.rb
  app/views/publish/courses/_basic_details_tab.html.erb
  app/views/publish/courses/confirmation.html.erb
  spec/components/add_course_button_spec.rb
  spec/features/publish/add_course_button_spec.rb
  spec/features/publish/course_confirmation_spec.rb
  spec/features/publish/courses/editing_study_sites_spec.rb
  spec/forms/publish/course_study_site_form_spec.rb
  spec/support/feature_helpers/new_course_param_helper.rb
Labels: deploy_v2

#3787 Remove front door config used for migration env
  terraform/custom_domains/environment_domains/workspace_variables/find_production.tfvars.json
  terraform/custom_domains/environment_domains/workspace_variables/publish_production.tfvars.json
Labels: Devops

#3793 [542] Fix the persona Susy
  app/views/personas/index.html.erb
Labels: deploy_v2

#3792 [321] Remove the interruption page
  app/controllers/publish/publish_controller.rb
  app/controllers/publish/rollover_recruitment_controller.rb
  app/models/interrupt_page_acknowledgement.rb
  app/models/user.rb
  app/policies/user_policy.rb
  config/analytics.yml
  config/routes/publish.rb
  config/settings.yml
  config/settings/rollover.yml
  db/migrate/20230816103429_delete_interrupt_page_acknowledgement_table.rb
  db/schema.rb
  docs/database-diagram.jpg
  spec/features/publish/accepting_rollover_recruitment_spec.rb
  spec/support/page_objects/publish/rollover_recruitment.rb
Labels: deploy_v2

#3800 Update libpq to fix CVE-2023-39417
  Dockerfile
Labels: deploy_v2

#3801 [232] Remove GOV.UK PaaS related code
  .github/actions/backup_and_restore/action.yml
  .github/actions/deploy/action.yml
  .github/actions/smoke-test/action.yml
  .github/workflows/build-nocache.yml
  .github/workflows/delete-review-app.yml
  .github/workflows/deploy.yml
  .github/workflows/smoke-test-v2.yml
  Makefile
  terraform/custom_domains/environment_domains/workspace_variables/find_pentest.tfvars.json
  terraform/custom_domains/environment_domains/workspace_variables/find_production.tfvars.json
  terraform/custom_domains/environment_domains/workspace_variables/find_qa.tfvars.json
  terraform/custom_domains/environment_domains/workspace_variables/find_sandbox.tfvars.json
  terraform/custom_domains/environment_domains/workspace_variables/find_staging.tfvars.json
  terraform/custom_domains/environment_domains/workspace_variables/publish_pentest.tfvars.json
  terraform/custom_domains/environment_domains/workspace_variables/publish_production.tfvars.json
  terraform/custom_domains/environment_domains/workspace_variables/publish_qa.tfvars.json
  terraform/custom_domains/environment_domains/workspace_variables/publish_sandbox.tfvars.json
  terraform/custom_domains/environment_domains/workspace_variables/publish_staging.tfvars.json
  terraform/modules/paas/data.tf
  terraform/modules/paas/main.tf
  terraform/modules/paas/providers.tf
  terraform/modules/paas/variables.tf
  terraform/modules/statuscake/providers.tf
  terraform/modules/statuscake/resources.tf
  terraform/modules/statuscake/variables.tf
  terraform/paas/.terraform.lock.hcl
  terraform/paas/data.tf
  terraform/paas/terraform.tf
  terraform/paas/variables.tf
  terraform/paas/workspace_variables/app_config.yml
  terraform/paas/workspace_variables/loadtest.tfvars.json
  terraform/paas/workspace_variables/loadtest_backend.tfvars
  terraform/paas/workspace_variables/production.tfvars.json
  terraform/paas/workspace_variables/production_backend.tfvars
  terraform/paas/workspace_variables/qa.tfvars.json
  terraform/paas/workspace_variables/qa_backend.tfvars
  terraform/paas/workspace_variables/review.tfvars.json
  terraform/paas/workspace_variables/review_backend.tfvars
  terraform/paas/workspace_variables/rollover.tfvars.json
  terraform/paas/workspace_variables/rollover_backend.tfvars
  terraform/paas/workspace_variables/sandbox.tfvars.json
  terraform/paas/workspace_variables/sandbox_backend.tfvars
  terraform/paas/workspace_variables/staging.tfvars.json
  terraform/paas/workspace_variables/staging_backend.tfvars
Labels: deploy_v2

#3802 [549] Update deadline banners/pages and fix cycle switcher
  app/components/find/deadline_banner_component.html.erb
  app/controllers/find/pages_controller.rb
  app/services/find/cycle_timetable.rb
  app/views/find/pages/cycle_has_ended.html.erb
  spec/features/find/view_pages_spec.rb
Labels: deploy_v2

#3809 Revert "Update events links in Find as there are no events currently"
  app/components/find/results/results_component.html.erb
  app/views/find/search/locations/_form.html.erb
  config/locales/find.yml
  spec/components/find/results/results_component_spec.rb
Labels: deploy_v2
