Repository DFE-Digital/publish-teacher-training, pull requests merged in 2023-06, with the labels that each got.

#3576 1236 providers modify course flow based on ap availability
  app/controllers/publish/courses/accredited_provider_controller.rb
  app/services/courses/creation_service.rb
  app/services/publish/course_creation_step_service.rb
  app/services/workflow_step_service.rb
  app/views/publish/courses/_basic_details_tab.html.erb
  app/views/publish/courses/accredited_provider/edit.html.erb
  app/views/publish/courses/confirmation.html.erb
  app/views/publish/providers/about.html.erb
  app/views/publish/providers/details.html.erb
  config/locales/en.yml
  config/routes/publish.rb
  spec/features/publish/courses/new_accredited_provider_spec.rb
  spec/features/publish/edit_provider_details_spec.rb
  spec/features/publish/viewing_a_course_preview_spec.rb
  spec/services/workflow_step_service_spec.rb
Labels: deploy

#3601 Add rollover env
  .github/workflows/deploy.yml
  Makefile
  config/database.yml
  config/environments/rollover.rb
  config/settings/rollover.yml
  terraform/paas/workspace_variables/app_config.yml
  terraform/paas/workspace_variables/rollover.tfvars.json
  terraform/paas/workspace_variables/rollover_backend.tfvars
Labels: Devops

#3604 [1288] Updated course withdrawal
  app/controllers/publish/courses/withdrawals_controller.rb
  app/forms/publish/course_withdrawal_form.rb
  app/views/publish/courses/application_status/new.html.erb
  app/views/publish/courses/withdrawals/edit.html.erb
  spec/features/publish/courses/withdrawing_a_course_spec.rb
  spec/forms/publish/course_withdrawal_form_spec.rb
Labels: deploy

#3605 [1284] Expose application status on the API
  app/serializers/api/public/v1/serializable_course.rb
  docs/source/release-notes.html.md.erb
  spec/controllers/api/public/v1/courses_controller_spec.rb
  spec/serializers/api/public/v1/serializable_course_spec.rb
  swagger/public_v1/api_spec.json
  swagger/public_v1/component_schemas/CourseAttributes.yml
Labels: deploy

#3615 Bump libcurl version to fix CVE-2023-28322
  Dockerfile
Labels: Devops

#3619 Bump libcrypto1.1 version to fix CVE-2023-2650
  Dockerfile
Labels: deploy

#3596 238 add aks review apps
  .github/actions/deploy_v2/action.yml
  .github/actions/smoke-test_v2/action.yml
  .github/workflows/build-and-deploy.yml
  .github/workflows/delete-v2-review-app.yml
  .github/workflows/deploy-v2-review-app.yml
  .github/workflows/deploy-v2.yml
  .gitignore
  Makefile
  README.md
  app/lib/find_constraint.rb
  app/lib/publish_constraint.rb
  config/cable.yml
  config/environments/review_aks.rb
  config/initializers/redis.rb
  config/initializers/sidekiq.rb
  config/settings/review_aks.yml
  docker-compose.yml
  global_config/dv_review_aks.sh
  global_config/review_aks.sh
  guides/aks-cheatsheet.md
  guides/aks_modules.md
  terraform/aks/.terraform.lock.hcl
  terraform/aks/application.tf
  terraform/aks/cluster_data.tf
  terraform/aks/databases.tf
  terraform/aks/locals.tf
  terraform/aks/providers.tf
  terraform/aks/variables.tf
  terraform/aks/workspace_variables/app_config.yml
  terraform/aks/workspace_variables/dv_review_aks.tfvars.json
  terraform/aks/workspace_variables/dv_review_aks_backend.tfvars
  terraform/aks/workspace_variables/review_aks.tfvars.json
  terraform/aks/workspace_variables/review_aks_backend.tfvars
  terraform/paas/terraform.tf
  terraform/paas/variables.tf
Labels: deploy, deploy_v2

#3616 [1332] add study sites
  app/controllers/publish/providers/study_site_search_controller.rb
  app/controllers/publish/providers/study_sites_check_controller.rb
  app/controllers/publish/providers/study_sites_controller.rb
  app/forms/support/school_form.rb
  app/helpers/breadcrumb_helper.rb
  app/helpers/navigation_bar_helper.rb
  app/models/site.rb
  app/views/publish/providers/study_site_search/new.html.erb
  app/views/publish/providers/study_sites/_form.html.erb
  app/views/publish/providers/study_sites/_study_site.html.erb
  app/views/publish/providers/study_sites/index.html.erb
  app/views/publish/providers/study_sites/new.html.erb
  app/views/publish/providers/study_sites/show.html.erb
  app/views/publish/providers/study_sites_check/show.html.erb
  config/locales/en.yml
  config/routes/publish.rb
  config/settings.yml
  config/settings/development.yml
  config/settings/review.yml
  docs/database-diagram.jpg
  spec/features/publish/managing_study_sites_spec.rb
  spec/forms/support/school_form_spec.rb
  spec/models/site_spec.rb
Labels: deploy

#3621 [1361] Update dates in line with Apply timetable
  app/components/find/courses/apply_component/view.html.erb
  app/components/find/deadline_banner_component.rb
  app/services/cycle_timetable.rb
  app/services/find/cycle_timetable.rb
  app/views/find/courses/show.html.erb
  app/views/find/pages/cycle_has_ended.html.erb
  app/views/find/switcher/cycles.html.erb
  app/views/publish/courses/preview.html.erb
  spec/components/find/courses/apply_component/view_spec.rb
  spec/features/find/search/viewing_a_course_spec.rb
Labels: deploy

#3629 Add Terrafile module management support
  .gitignore
  Makefile
  global_config/dv_review_aks.sh
  global_config/find-domain.sh
  global_config/publish-domain.sh
  global_config/review_aks.sh
  guides/aks_modules.md
  terraform/aks/application.tf
  terraform/aks/cluster_data.tf
  terraform/aks/databases.tf
  terraform/aks/workspace_variables/dv_review_aks_Terrafile
  terraform/aks/workspace_variables/review_aks_Terrafile
Labels: Devops, deploy, terraform, deploy_v2

#3633 [1366] Prevent updates to cycle switcher in prod
  app/views/find/switcher/cycles.html.erb
Labels: deploy

#3625 [1325] update study sites
  app/controllers/publish/providers/study_sites_controller.rb
  app/forms/publish/school_form.rb
  app/forms/support/school_form.rb
  app/views/publish/providers/study_sites/_form.html.erb
  app/views/publish/providers/study_sites/edit.html.erb
  app/views/publish/providers/study_sites/new.html.erb
  config/locales/en.yml
  spec/features/publish/managing_study_sites_spec.rb
Labels: deploy

#3634 [1366] Fix point in recruitment cycle switcher
  app/helpers/recruitment_cycle_helper.rb
  app/views/find/switcher/cycles.html.erb
  config/locales/find.yml
  spec/features/find/switcher_cycles_spec.rb
Labels: deploy

#3636 [1362] Fix apply button logic
  app/components/find/courses/apply_component/view.html.erb
  app/components/find/courses/apply_component/view.rb
  app/components/find/courses/contents_component/view.html.erb
  app/models/course.rb
  app/views/publish/courses/_course_table_row.html.erb
  app/views/publish/courses/preview.html.erb
  spec/components/find/courses/apply_component/view_spec.rb
  spec/components/find/courses/contents_component/view_preview.rb
  spec/components/find/courses/contents_component/view_spec.rb
  spec/factories/courses.rb
  spec/features/publish/viewing_a_course_preview_spec.rb
  spec/models/course_spec.rb
Labels: deploy

#3640 [1332] Remove `vacancies controller` and related
  app/controllers/publish/courses/vacancies_controller.rb
  app/forms/publish/course_vacancies_form.rb
  app/mailers/course_vacancies/updated_mailer.rb
  app/policies/course_policy.rb
  app/services/notification_service/course_vacancies_updated.rb
  app/views/publish/courses/vacancies/_multiple_sites.html.erb
  app/views/publish/courses/vacancies/_single_site.html.erb
  app/views/publish/courses/vacancies/_site_status_checkbox.html.erb
  app/views/publish/courses/vacancies/edit.html.erb
  config/locales/en.yml
  config/rubocop/rspec.yml
  config/settings.yml
  spec/forms/publish/course_vacancies_form_spec.rb
  spec/mailers/course_vacancies/updated_mailer_spec.rb
  spec/services/notification_service/course_vacancies_updated_spec.rb
Labels: deploy

#3646 [1323] Implement study site removal
  app/helpers/study_sites_helper.rb
  app/models/study_site_placement.rb
  app/views/publish/providers/study_sites/delete.html.erb
  app/views/publish/providers/study_sites/index.html.erb
  config/locales/en.yml
  config/routes/publish.rb
  config/rubocop/rspec.yml
  config/settings/review_aks.yml
  spec/factories/study_site_placements.rb
  spec/features/publish/managing_study_sites_spec.rb
  spec/features/publish/searching_for_a_study_site_spec.rb
  spec/models/study_site_placement_spec.rb
Labels: deploy_v2

#3657 [1375] return draft if enrichment is blank
  app/models/course.rb
  app/services/courses/content_status_service.rb
  spec/features/publish/viewing_a_course_spec.rb
  spec/models/course_spec.rb
  spec/services/courses/content_status_service_spec.rb
  spec/services/courses/copy_to_provider_service_spec.rb
Labels: deploy

#3664 Bump pkgconf version to fix CVE-2023-24056
  Dockerfile
Labels: Devops, deploy, deploy_v2

#3658 [1326] Add study sites to find course show page
  app/components/find/courses/about_schools_component/view.html.erb
  app/components/find/courses/about_schools_component/view.rb
  app/components/find/courses/contents_component/view.html.erb
  config/rubocop/rspec.yml
  spec/components/find/courses/about_schools_component/view_preview.rb
  spec/components/find/courses/about_schools_component/view_spec.rb
  spec/components/find/courses/contents_component/view_spec.rb
  spec/decorators/course_decorator_spec.rb
  spec/features/publish/viewing_a_course_preview_spec.rb
  spec/support/page_objects/publish/course_preview.rb
Labels: deploy_v2

#3644 [235] add qa aks env
  .github/actions/deploy_v2/action.yml
  .github/actions/restore/action.yml
  .github/workflows/build-and-deploy.yml
  .github/workflows/database-restore-aks.yml
  Makefile
  config/environments/qa_aks.rb
  config/settings/qa_aks.yml
  global_config/qa_aks.sh
  terraform/aks/.terraform.lock.hcl
  terraform/aks/application.tf
  terraform/aks/databases.tf
  terraform/aks/locals.tf
  terraform/aks/variables.tf
  terraform/aks/workspace_variables/app_config.yml
  terraform/aks/workspace_variables/dv_review_aks.tfvars.json
  terraform/aks/workspace_variables/qa_aks.tfvars.json
  terraform/aks/workspace_variables/qa_aks_Terrafile
  terraform/aks/workspace_variables/qa_aks_backend.tfvars
  terraform/aks/workspace_variables/review_aks.tfvars.json
  terraform/custom_domains/environment_domains/main.tf
  terraform/custom_domains/environment_domains/workspace_variables/find_qa.tfvars.json
  terraform/custom_domains/environment_domains/workspace_variables/publish_qa.tfvars.json
Labels: deploy, deploy_v2

#3651 [1328] study sites course step
  app/controllers/publish/courses/applications_open_controller.rb
  app/controllers/publish/courses/study_sites_controller.rb
  app/controllers/publish/courses_controller.rb
  app/decorators/course_decorator.rb
  app/models/concerns/publish/course_basic_detail_concern.rb
  app/models/course.rb
  app/services/courses/creation_service.rb
  app/services/workflow_step_service.rb
  app/views/publish/courses/confirmation.html.erb
  app/views/publish/courses/study_sites/new.html.erb
  config/locales/en.yml
  config/routes/publish.rb
  spec/controllers/publish/courses_controller_spec.rb
  spec/features/publish/course_confirmation_spec.rb
  spec/features/publish/courses/new_schools_spec.rb
  spec/features/publish/courses/new_visa_sponsorship_spec.rb
  spec/features/publish/courses/publishing_a_course_spec.rb
  spec/features/publish/e2e/new_course_spec.rb
  spec/models/course/publishable_spec.rb
  spec/services/courses/creation_service_spec.rb
  spec/support/feature_helpers/new_course_param_helper.rb
  spec/support/page_objects/publish/course_confirmation.rb
  spec/support/page_objects/publish/courses/new_study_sites.rb
Labels: deploy_v2

#3669 [263] Add a notification banner to publish
  app/views/publish/courses/details.html.erb
  app/views/publish/courses/index.html.erb
  app/views/publish/courses/show.html.erb
Labels: deploy_v2

#3670 [268] Downgrade data_migrate to version 9
  Gemfile
  Gemfile.lock
Labels: deploy_v2

#3671 [14] Enforce study sites post rollover
  app/controllers/publish/courses/study_sites_controller.rb
  app/helpers/navigation_bar_helper.rb
  app/helpers/recruitment_cycle_helper.rb
  app/helpers/view_helper.rb
  app/models/course.rb
  app/services/workflow_step_service.rb
  app/views/publish/courses/_basic_details_tab.html.erb
  app/views/publish/courses/confirmation.html.erb
  app/views/publish/courses/index.html.erb
  app/views/publish/courses/study_sites/edit.html.erb
  config/locales/en.yml
  spec/features/publish/add_course_button_spec.rb
  spec/features/publish/course_confirmation_spec.rb
  spec/features/publish/courses/editing_study_sites_spec.rb
  spec/features/publish/e2e/new_course_spec.rb
  spec/models/course/update_valid_spec.rb
Labels: deploy_v2

#3679 [302] Fix study sites snags
  app/controllers/publish/courses/study_sites_controller.rb
  app/helpers/view_helper.rb
  app/views/publish/courses/_basic_details_tab.html.erb
  app/views/publish/courses/index.html.erb
  app/views/publish/providers/study_sites_check/show.html.erb
  config/locales/en.yml
  spec/features/publish/add_course_button_spec.rb
  spec/features/publish/courses/editing_study_sites_spec.rb
Labels: deploy_v2
