Repository DFE-Digital/publish-teacher-training, pull requests merged in 2023-07, with the labels that each got.

#3677 [235] Add sandbox AKS env
  .github/workflows/build-and-deploy.yml
  .github/workflows/database-restore-aks.yml
  .github/workflows/deploy-v2.yml
  Makefile
  config/environments/sandbox_aks.rb
  config/settings/sandbox_aks.yml
  global_config/sandbox_aks.sh
  terraform/aks/.terraform.lock.hcl
  terraform/aks/application.tf
  terraform/aks/workspace_variables/app_config.yml
  terraform/aks/workspace_variables/sandbox_aks.tfvars.json
  terraform/aks/workspace_variables/sandbox_aks_Terrafile
  terraform/aks/workspace_variables/sandbox_aks_backend.tfvars
  terraform/custom_domains/environment_domains/workspace_variables/find_sandbox.tfvars.json
  terraform/custom_domains/environment_domains/workspace_variables/publish_sandbox.tfvars.json
Labels: Devops, deploy, terraform, deploy_v2

#3690 [319] Update financial support row in Find search results
  app/components/find/courses/summary_component/view.html.erb
  app/components/find/results/search_result_component.html.erb
  app/decorators/course_decorator.rb
  spec/components/find/courses/sumary_component/view_spec.rb
  spec/features/find/search/course_results_spec.rb
Labels: deploy_v2

#3695 [320] Make international fees mandatory for providers sponsoring student visas
  app/controllers/publish/providers_controller.rb
  app/forms/publish/course_fee_form.rb
  app/helpers/recruitment_cycle_helper.rb
  app/helpers/rollover_helper.rb
  app/helpers/view_helper.rb
  app/models/course_enrichment.rb
  app/models/user.rb
  app/views/publish/courses/fees/edit.html.erb
  config/locales/en.yml
  spec/forms/publish/course_fee_form_spec.rb
  spec/models/course_enrichment_spec.rb
Labels: deploy_v2

#3678 [434] GOV.UK PaaS to AKS daily database refresh
  .github/actions/backup_and_restore/action.yml
  .github/workflows/database-restore-aks.yml
  .github/workflows/database-restore.yml
  .github/workflows/scheduled-aks-db-restore.yml
Labels: Devops, github_actions

#3701 [434] Add dependency on backup for AKS QA and staging
  .github/workflows/database-restore.yml
Labels: Devops

#3712 Activate study sites in all environments
  config/settings.yml
  config/settings/development.yml
  config/settings/review.yml
  config/settings/review_aks.yml
  spec/features/publish/add_course_button_spec.rb
Labels: deploy_v2

#3705 [353] Fix study sites validation bug
  app/controllers/publish/courses/study_sites_controller.rb
  app/forms/publish/course_study_site_form.rb
  app/models/course.rb
  app/views/publish/courses/study_sites/edit.html.erb
  config/locales/en.yml
  spec/forms/publish/course_study_site_form_spec.rb
Labels: deploy_v2

#3697 [318] Hide add course button when organisation details are missing (next cycle only)
  app/components/add_course_button.html.erb
  app/components/add_course_button.rb
  app/views/publish/courses/index.html.erb
  spec/components/add_course_button_preview.rb
  spec/components/add_course_button_spec.rb
  spec/features/publish/add_course_button_spec.rb
Labels: deploy_v2

#3703 [434] Add production to the daily paas to aks db restore
  .github/workflows/scheduled-aks-db-restore.yml
Labels: Devops, github_actions

#3715 Make sandbox AKS depend on prod AKS
  .github/workflows/build-and-deploy.yml
Labels: Devops, github_actions

#3714 Skip before action on study_sites guidance page
  app/controllers/pages_controller.rb
Labels: deploy_v2

#3691 Fix the Publish course information bug
  app/components/find/courses/about_schools_component/view.html.erb
  app/components/find/courses/about_schools_component/view.rb
  app/controllers/concerns/copy_course_content.rb
  app/controllers/publish/courses/course_information_controller.rb
  app/controllers/publish/courses/fees_controller.rb
  app/controllers/publish/courses/requirements_controller.rb
  app/decorators/course_decorator.rb
  app/models/course.rb
  app/services/courses/content_status_service.rb
  app/services/courses/copy.rb
  app/views/find/courses/_about_course.html.erb
  app/views/find/courses/_interview_process.html.erb
  app/views/find/courses/show.html.erb
  app/views/publish/courses/_course_length_field.html.erb
  app/views/publish/courses/course_information/edit.html.erb
  app/views/publish/courses/fees/edit.html.erb
  app/views/publish/courses/requirements/edit.html.erb
  config/locales/en.yml
  spec/components/find/courses/about_schools_component/view_preview.rb
  spec/factories/course_enrichments.rb
  spec/features/publish/courses/copy_from_list_spec.rb
  spec/features/publish/courses/publishing_a_course_spec.rb
  spec/models/course_spec.rb
  spec/services/courses/copy_spec.rb
Labels: deploy_v2

#3717 [362] A few rollover snags
  app/components/add_course_button.rb
  app/views/publish/courses/course_button_panel/_published.html.erb
  spec/components/add_course_button_spec.rb
  spec/features/publish/add_course_button_spec.rb
  spec/features/publish/viewing_a_course_spec.rb
Labels: deploy_v2

#3722 Activate rollover in all envs
  config/settings.yml
  config/settings/qa.yml
Labels: deploy_v2

#3721 [366] Fix editing AP in next cycle
  app/forms/accredited_provider_form.rb
  spec/forms/accredited_provider_form_spec.rb
Labels: deploy_v2

#3720 [358] Add degree subject requirement validation
  app/forms/publish/subject_requirement_form.rb
  app/views/publish/courses/degrees/_additional_degree_subject_requirements.html.erb
  app/views/publish/courses/degrees/subject_requirements/edit.html.erb
  config/locales/en.yml
  spec/forms/publish/subject_requirement_form_spec.rb
Labels: deploy_v2

#3724 [374] Destroy StudySitePlacements with Course
  app/models/course.rb
  spec/models/course_spec.rb
Labels: deploy_v2

#3719 [489] QA AKS add monitoring and logging
  Makefile
  global_config/find-domain.sh
  global_config/publish-domain.sh
  terraform/aks/.terraform.lock.hcl
  terraform/aks/locals.tf
  terraform/aks/providers.tf
  terraform/aks/secrets.tf
  terraform/aks/statuscake.tf
  terraform/aks/workspace_variables/qa_aks.tfvars.json
Labels: Devops

#3729 Remove validation for code
  app/forms/support/school_form.rb
Labels: deploy_v2

#3726 Find visa status page
  app/controllers/concerns/filter_parameters.rb
  app/controllers/find/search/age_groups_controller.rb
  app/controllers/find/search/subjects_controller.rb
  app/controllers/find/search/visa_status_controller.rb
  app/forms/find/visa_status_form.rb
  app/views/find/result_filters/location/_form.html.erb
  app/views/find/search/locations/_form.html.erb
  app/views/find/search/subjects/_primary_subjects.html.erb
  app/views/find/search/subjects/_secondary_subjects.html.erb
  app/views/find/search/visa_status/new.html.erb
  config/locales/find.yml
  config/routes/find.rb
  spec/features/find/result_page_filters/engineers_teach_physics_spec.rb
  spec/features/find/search/across_england/further_education_spec.rb
  spec/features/find/search/across_england/primary_spec.rb
  spec/features/find/search/across_england/secondary_spec.rb
  spec/features/find/search/editing_a_search_spec.rb
  spec/features/find/search/location_options_spec.rb
Labels: deploy_v2

#3730 [379] Ensure accredited provider tab appears
  app/helpers/navigation_bar_helper.rb
  spec/helpers/navigation_bar_helper_spec.rb
Labels: deploy, deploy_v2

#3735 Migrate QA env to AKS
  .github/workflows/build-and-deploy.yml
  .github/workflows/database-restore.yml
  .github/workflows/deploy.yml
  .github/workflows/smoke-test.yml
  config/settings/qa_aks.yml
  terraform/aks/workspace_variables/qa_aks.tfvars.json
  terraform/custom_domains/environment_domains/workspace_variables/find_qa.tfvars.json
  terraform/custom_domains/environment_domains/workspace_variables/publish_qa.tfvars.json
Labels: Devops, deploy_v2

#3738 [504] Make PaaS prod depend on AKS
  .github/workflows/build-and-deploy.yml
Labels: Devops, github_actions

#3723 Remove SASSC gem
  Gemfile
  Gemfile.lock
Labels: deploy_v2

#3739 [388] Fix adding new ap's in the new cycle
  app/forms/accredited_provider_form.rb
  spec/forms/accredited_provider_form_spec.rb
Labels: deploy_v2

#3736 [378] Remove validation for code
  app/models/site.rb
  spec/models/site_spec.rb
Labels: deploy_v2

#3744 [504] Prepare front door, DNS for staging AKS migration
  terraform/custom_domains/environment_domains/workspace_variables/find_staging.tfvars.json
  terraform/custom_domains/environment_domains/workspace_variables/publish_staging.tfvars.json
Labels: Devops

#3737 Filter for discarded providers in public API
  app/controllers/api/public/v1/providers_controller.rb
  app/serializers/api/public/v1/serializable_provider.rb
  docs/source/release-notes.html.md.erb
  spec/controllers/api/public/v1/providers_controller_spec.rb
  spec/rails_helper.rb
  swagger/public_v1/api_spec.json
  swagger/public_v1/component_schemas/ProviderAttributes.yml
  swagger/public_v1/component_schemas/ProviderFilter.yml
Labels: deploy_v2

#3746 Fix incomplete accredited provider preview link
  app/components/course_preview/missing_information_component.rb
  spec/components/course_preview/missing_information_component_spec.rb
Labels: deploy_v2

#3748 [392] Enable reclassified providers to add AP's
  app/views/publish/courses/_basic_details_tab.html.erb
  spec/features/publish/courses/adding_an_accredited_provider_to_an_unpublished_course_spec.rb
Labels: deploy_v2

#3745 [504] Migrate staging env to AKS
  .github/workflows/build-and-deploy.yml
  .github/workflows/database-restore.yml
  .github/workflows/deploy.yml
  .github/workflows/smoke-test.yml
  config/settings/staging_aks.yml
  terraform/aks/workspace_variables/staging_aks.tfvars.json
  terraform/custom_domains/environment_domains/workspace_variables/find_staging.tfvars.json
  terraform/custom_domains/environment_domains/workspace_variables/publish_staging.tfvars.json
Labels: Devops, github_actions, terraform, deploy_v2

#3752 [504] Sandbox AKS migration prep
  terraform/aks/workspace_variables/sandbox_aks.tfvars.json
  terraform/custom_domains/environment_domains/workspace_variables/find_sandbox.tfvars.json
  terraform/custom_domains/environment_domains/workspace_variables/publish_sandbox.tfvars.json
Labels: Devops, terraform

#3756 Remove staging 2 front door configuration
  terraform/custom_domains/environment_domains/workspace_variables/find_staging.tfvars.json
  terraform/custom_domains/environment_domains/workspace_variables/publish_staging.tfvars.json
Labels: Devops, terraform

#3747 Invalidate incomplete course on publish
  app/components/accredited_provider.html.erb
  app/controllers/publish/courses/accredited_provider_controller.rb
  app/helpers/view_helper.rb
  app/models/course.rb
  app/models/provider.rb
  app/views/publish/courses/accredited_provider/edit.html.erb
  app/views/publish/providers/accredited_providers/index.html.erb
  config/locales/en.yml
  spec/controllers/publish/courses_controller_spec.rb
  spec/features/publish/courses/add_accredited_provider_when_publishing_a_course_spec.rb
  spec/features/publish/courses/publishing_a_course_spec.rb
  spec/helpers/application_helper_spec.rb
  spec/models/course/publishable_spec.rb
  spec/models/provider_spec.rb
  spec/support/page_objects/publish/courses/accredited_providers.rb
  spec/support/page_objects/publish/courses/new_accredited_provider.rb
  spec/support/page_objects/publish/provider_accredited_providers_index.rb
  spec/support/page_objects/publish/provider_accredited_providers_search.rb
  spec/support/page_objects/publish/provider_courses_show.rb
Labels: deploy_v2

#3751 [504] Migrate sandbox to AKS
  .github/workflows/build-and-deploy.yml
  .github/workflows/deploy.yml
  .github/workflows/scheduled-aks-db-restore.yml
  .github/workflows/smoke-test.yml
  config/settings/sandbox_aks.yml
  terraform/aks/workspace_variables/sandbox_aks.tfvars.json
  terraform/custom_domains/environment_domains/workspace_variables/find_sandbox.tfvars.json
  terraform/custom_domains/environment_domains/workspace_variables/publish_sandbox.tfvars.json
Labels: Devops, github_actions, terraform, deploy_v2

#3764 [504] Remove sandbox2 front door configuration
  terraform/custom_domains/environment_domains/workspace_variables/find_sandbox.tfvars.json
  terraform/custom_domains/environment_domains/workspace_variables/publish_sandbox.tfvars.json
Labels: Devops, terraform

#3767 Fix adding user in next cycle
  app/services/user_associations_service/create.rb
  spec/services/user_associations_service/create_spec.rb
Labels: deploy_v2

#3755 Update events links in Find as there are no events currently
  app/components/find/results/results_component.html.erb
  app/views/find/search/locations/_form.html.erb
  spec/components/find/results/results_component_spec.rb
Labels: deploy_v2

#3754 Update URLs on Find and Publish to reflect new GIT Links
  app/views/find/courses/_advice.html.erb
  config/locales/en.yml
  config/locales/find.yml
Labels: deploy_v2

#3761 Fix accrediting provider error text on Course
  app/models/course.rb
  config/locales/en.yml
  spec/features/publish/courses/add_accredited_provider_when_publishing_a_course_spec.rb
  spec/models/course/publishable_spec.rb
Labels: deploy_v2

#3766 Add accredited provider button changed to link
  app/views/publish/courses/accredited_provider/edit.html.erb
  app/views/publish/providers/accredited_providers/index.html.erb
  spec/features/publish/courses/add_accredited_provider_when_publishing_a_course_spec.rb
  spec/support/page_objects/publish/courses/accredited_providers.rb
Labels: deploy_v2

#3769 [414] Update rollover script to handle the correct `application_open_from` date
  app/services/courses/copy_to_provider_service.rb
  spec/services/courses/copy_to_provider_service_spec.rb
Labels: deploy_v2
