Repository DFE-Digital/publish-teacher-training, pull requests merged in 2023-01, with the labels that each got.

#3214 [0908] Amended apply filters button to top of filters panel
  app/assets/stylesheets/components/find/_filter.scss
  app/views/find/result_filters/_all.html.erb
Labels: deploy

#3205 577 migrate find cycles feature
  app/controllers/find/switcher_controller.rb
  app/forms/find/change_cycle_form.rb
  app/models/site_setting.rb
  app/views/find/switcher/cycles.html.erb
  config/locales/en.yml
  config/routes/find.rb
  spec/features/find/switcher_cycles_spec.rb
Labels: deploy

#3234 [934] Fix campaign name filter
  app/services/course_search_service.rb
Labels: deploy

#3235 Alphabetize users list
  app/controllers/publish/users_controller.rb
  app/models/user.rb
  spec/models/user_spec.rb
Labels: deploy

#3238 Activate user management in production
  config/settings.yml
  config/settings/qa.yml
  config/settings/review.yml
  spec/features/publish/viewing_provider_users_spec.rb
Labels: deploy

#3224 Migrate find cycles feature (part 2)
  app/controllers/find/application_controller.rb
  app/controllers/find/pages_controller.rb
  app/controllers/find/switcher_controller.rb
  app/services/cycle_timetable.rb
  app/views/find/pages/cycle_has_ended.html.erb
  app/views/find/switcher/cycles.html.erb
  config/routes/find.rb
  spec/features/find/switcher_cycles_spec.rb
Labels: deploy

#3243 [xxxx] Fixed case sensitivity
  app/controllers/publish/users_check_controller.rb
  app/controllers/publish/users_controller.rb
  app/controllers/support/providers/users_check_controller.rb
  app/controllers/support/providers/users_controller.rb
Labels: deploy

#3246 Add find2 route for review apps
  terraform/modules/paas/variables.tf
Labels: Devops, deploy

#3247 Update results page ordering options
  app/components/find/results/sort_by_component.html.erb
  app/models/course.rb
  app/services/course_search_service.rb
  app/view_objects/find/results_view.rb
  spec/features/find/sorted_by_filter_spec.rb
  spec/models/course_spec.rb
  spec/requests/api/v3/courses/index_spec.rb
  spec/services/course_search_service_spec.rb
  spec/view_objects/find/results_view_spec.rb
Labels: deploy

#3261 [0896] Add provider name to ProviderFilter
  app/controllers/api/public/v1/providers_controller.rb
  app/models/provider.rb
  docs/source/release-notes.html.md.erb
  spec/controllers/api/public/v1/providers_controller_spec.rb
  spec/models/provider_spec.rb
  swagger/public_v1/api_spec.json
  swagger/public_v1/component_schemas/ProviderFilter.yml
Labels: deploy

#3262 Remove full stops
  app/components/find/results/search_result_component.rb
Labels: deploy

#3248 939 old find params
  app/controllers/find/results_controller.rb
  app/services/find/match_old_params.rb
  app/views/find/result_filters/_hidden_fields.html.erb
  spec/services/find/match_old_params_spec.rb
Labels: deploy

#3263 [0958] Amended documentation typos
  spec/docs/providers/locations_spec.rb
  swagger/public_v1/api_spec.json
Labels: deploy

#3276 [xxx] Enable the sidekiq dashboard for admins
  app/lib/system_admin_constraint.rb
  config/routes/publish.rb
Labels: deploy

#3264 Update 404 page content
  app/views/errors/not_found.html.erb
Labels: deploy

#3266 Update 500 page content
  app/views/errors/internal_server_error.html.erb
Labels: deploy

#3267 Update 503 page content
  service_unavailable_page/web/public/internal/index.html
Labels: deploy

#3279 Content tweak
  app/components/find/location_subject_filter_component.html.erb
Labels: deploy

#3272 Add find qa routes to terraform state and code
  terraform/data.tf
  terraform/modules/paas/data.tf
  terraform/modules/paas/main.tf
  terraform/modules/paas/variables.tf
  terraform/terraform.tf
  terraform/variables.tf
  terraform/workspace_variables/qa.tfvars.json
Labels: Devops

#3292 reset SNYK default app scan setting
  .github/workflows/build-and-deploy.yml
  .github/workflows/build-nocache.yml
Labels: Devops

#3295 Fix review app
  terraform/modules/paas/data.tf
  terraform/modules/paas/main.tf
  terraform/modules/paas/variables.tf
  terraform/terraform.tf
  terraform/variables.tf
  terraform/workspace_variables/qa.tfvars.json
Labels: Devops, deploy

#3297 Enable find route for review apps
  terraform/workspace_variables/review.tfvars.json
Labels: Devops, deploy

#3275 929 update content
  app/components/find/courses/about_schools_component/view.html.erb
  app/views/publish/courses/course_information/edit.html.erb
Labels: deploy

#3299 Increase QA app instance memory
  terraform/workspace_variables/qa.tfvars.json
Labels: Devops

#3285 956 update subjects v1
  app/decorators/course_decorator.rb
  app/helpers/publish/subject_helper.rb
  app/views/publish/courses/_new_fields_holder.html.erb
  app/views/publish/courses/subjects/_primary_form.html.erb
  app/views/publish/courses/subjects/_secondary_form.html.erb
  app/views/publish/courses/subjects/edit.html.erb
  app/views/publish/courses/subjects/new.html.erb
  spec/decorators/course_decorator_spec.rb
  spec/features/publish/course_confirmation_spec.rb
  spec/features/publish/courses/editing_engineers_teach_physics_spec.rb
  spec/features/publish/courses/editing_subject_spec.rb
  spec/features/publish/courses/new_engineers_teach_physics_spec.rb
  spec/features/publish/courses/new_level_spec.rb
  spec/features/publish/courses/new_subject_spec.rb
  spec/features/publish/e2e/new_course_spec.rb
  spec/helpers/publish/subject_helper_spec.rb
  spec/support/page_objects/publish/courses/new_subjects.rb
  spec/support/page_objects/publish/courses/subjects_edit.rb
Labels: deploy

#3306 Add find routes to staging and increase memory
  terraform/workspace_variables/staging.tfvars.json
Labels: Devops

#3303 Downcase non language subjects
  app/services/courses/generate_course_name_service.rb
  spec/services/courses/assign_subjects_service_spec.rb
  spec/services/courses/generate_course_name_service_spec.rb
Labels: deploy

#3310 Comply with rubocop (lint.yml)
  config/rubocop/lint.yml
Labels: deploy
