Repository DFE-Digital/publish-teacher-training, pull requests merged in 2023-05, with the labels that each got.

#3536 [1196] Added provider check your answers page
  app/controllers/support/providers/onboarding/checks_controller.rb
  app/controllers/support/providers/onboarding/contacts_controller.rb
  app/controllers/support/providers/onboardings_controller.rb
  app/forms/support/provider_contact_form.rb
  app/forms/support/provider_form.rb
  app/helpers/support/goto_confirmation_helper.rb
  app/models/provider.rb
  app/views/support/providers/onboarding/checks/show.html.erb
  app/views/support/providers/onboarding/contacts/new.html.erb
  app/views/support/providers/onboardings/new.html.erb
  config/locales/en.yml
  config/routes/support.rb
  spec/features/support/providers/onboarding_a_new_provider_spec.rb
  spec/forms/support/provider_contact_form_spec.rb
  spec/forms/support/provider_form_spec.rb
  spec/helpers/support/goto_confimation_helper_spec.rb
  spec/models/provider_spec.rb
Labels: deploy

#3541 [xxxx] Prevent H3 from rendering if no content
  app/views/find/courses/_about_the_provider.html.erb
Labels: deploy

#3542 [1269] Added accredited body summary card component
  app/components/accredited_provider.html.erb
  app/components/accredited_provider.rb
  spec/components/accredited_provider_preview.rb
  spec/components/accredited_provider_spec.rb
Labels: deploy

#3540 [1234] Add accredited providers tab (on navbar) and index page
  app/controllers/publish/providers/accredited_providers_controller.rb
  app/helpers/navigation_bar_helper.rb
  app/views/publish/providers/accredited_providers/index.html.erb
  config/locales/en.yml
  config/routes/publish.rb
  config/settings/qa.yml
  config/settings/test.yml
  spec/components/navigation_bar_preview.rb
  spec/features/publish/accredited_provider_spec.rb
Labels: deploy

#3547 [1227] Providers add accredited provider (step 1 non js)
  app/controllers/publish/providers/accredited_providers_controller.rb
  app/views/publish/providers/accredited_providers/index.html.erb
  app/views/publish/providers/accredited_providers/new.html.erb
  app/views/publish/providers/accredited_providers/results.html.erb
  config/routes/publish.rb
  spec/features/publish/accredited_provider_spec.rb
Labels: deploy

#3551 Revert Find TTL, remove environment_tag
  terraform/custom_domains/environment_domains/workspace_variables/find_pentest.tfvars.json
  terraform/custom_domains/environment_domains/workspace_variables/find_production.tfvars.json
  terraform/custom_domains/environment_domains/workspace_variables/find_qa.tfvars.json
  terraform/custom_domains/environment_domains/workspace_variables/find_sandbox.tfvars.json
  terraform/custom_domains/environment_domains/workspace_variables/find_staging.tfvars.json
Labels: Devops, terraform

#3537 [1197] edit contact details
  app/components/providers/provider_list/view.html.erb
  app/components/providers/provider_list/view.rb
  app/controllers/support/contact_details_controller.rb
  app/controllers/support/providers_controller.rb
  app/decorators/provider_decorator.rb
  app/forms/support/contact_details_form.rb
  app/helpers/publish/course_helper.rb
  app/helpers/publish/value_helper.rb
  app/models/provider.rb
  app/validators/accredited_provider_id_format_validator.rb
  app/views/publish/courses/_description_content.html.erb
  app/views/publish/providers/schools/_school.html.erb
  app/views/publish/providers/schools/show.html.erb
  app/views/support/contact_details/edit.html.erb
  app/views/support/providers/edit.html.erb
  app/views/support/schools/index.html.erb
  config/locales/en.yml
  config/routes/support.rb
  spec/factories/providers.rb
  spec/features/support/providers/editing_a_provider_spec.rb
  spec/forms/support/contact_details_form_spec.rb
  spec/helpers/publish/course_helper_spec.rb
  spec/helpers/publish/value_helper_spec.rb
  spec/models/provider_spec.rb
  spec/support/page_objects/support/provider_show.rb
  spec/validators/accredited_provider_id_format_validator_spec.rb
Labels: deploy

#3553 [1277] Providers render the accredited provider summary component
  app/views/publish/providers/accredited_providers/index.html.erb
  spec/features/publish/accredited_provider_spec.rb
Labels: deploy

#3495 Restructure project to support AKS platform code
  .github/actions/deploy/action.yml
  .github/workflows/build-and-deploy.yml
  .github/workflows/build-nocache.yml
  .github/workflows/database-restore.yml
  .github/workflows/delete-review-app.yml
  .gitignore
  Makefile
  terraform/paas/.terraform.lock.hcl
  terraform/paas/data.tf
  terraform/paas/terraform.tf
  terraform/paas/variables.tf
  terraform/paas/workspace_variables/app_config.yml
  terraform/paas/workspace_variables/loadtest.tfvars.json
  terraform/paas/workspace_variables/loadtest_backend.tfvars
  terraform/paas/workspace_variables/production.tfvars.json
  terraform/paas/workspace_variables/production_backend.tfvars
  terraform/paas/workspace_variables/qa.tfvars.json
  terraform/paas/workspace_variables/qa_backend.tfvars
  terraform/paas/workspace_variables/review.tfvars.json
  terraform/paas/workspace_variables/review_backend.tfvars
  terraform/paas/workspace_variables/sandbox.tfvars.json
  terraform/paas/workspace_variables/sandbox_backend.tfvars
  terraform/paas/workspace_variables/staging.tfvars.json
  terraform/paas/workspace_variables/staging_backend.tfvars
Labels: Devops, deploy, github_actions, terraform

#3550 [1272] Realign accrediting provider enrichment to be accredited bodies
  app/models/provider.rb
  app/views/publish/providers/accredited_providers/index.html.erb
  spec/features/publish/courses/new_accredited_provider_spec.rb
  spec/features/publish/edit_provider_details_spec.rb
  spec/features/publish/viewing_a_course_preview_spec.rb
  spec/models/provider/accredited_providers_spec.rb
  spec/models/provider_spec.rb
  spec/policies/provider_policy_spec.rb
Labels: deploy

#3556 [1272] Fixed broken merge
  app/views/publish/providers/accredited_providers/index.html.erb
  spec/features/publish/accredited_provider_spec.rb
Labels: deploy

#3535 [873] Port GTM work from old ticket
  app/controllers/cookie_preferences_controller.rb
  app/controllers/find/cookie_preferences_controller.rb
  app/forms/find/cookie_preferences_form.rb
  app/forms/publish/cookie_preferences_form.rb
  app/helpers/cookies_helper.rb
  app/javascript/cookie_banner.js
  app/javascript/cookie_banner.spec.js
  app/javascript/jestGlobalMocks.js
  app/views/cookie_preferences/show.html.erb
  app/views/find/cookie_preferences/show.html.erb
  app/views/find/pages/accessibility.html.erb
  app/views/find/pages/privacy.html.erb
  app/views/find/pages/terms.html.erb
  app/views/layouts/_add_js_enabled_class_to_body.html.erb
  app/views/layouts/_cookie_banner.html.erb
  app/views/layouts/_gtm.html.erb
  app/views/layouts/application.html.erb
  app/views/layouts/find_layout.html.erb
  app/views/pages/accessibility.html.erb
  app/views/pages/performance_dashboard.html.erb
  app/views/pages/privacy.html.erb
  app/views/pages/terms.html.erb
  config/initializers/content_security_policy.rb
  config/locales/en.yml
  config/settings.yml
  config/settings/production.yml
  jest.config.js
  package.json
  spec/features/find/cookie_preferences_spec.rb
  spec/features/publish/cookie_preferences_spec.rb
  spec/support/page_objects/find/cookie_preferences.rb
  spec/support/page_objects/publish/cookie_preferences.rb
Labels: deploy

#3558 [1279] Update school placement copy
  app/components/find/courses/about_schools_component/view.html.erb
Labels: deploy

#3559 [1230] Providers: About Accredited Provider - Step 2
  app/controllers/publish/providers/accredited_provider_search_controller.rb
  app/controllers/publish/providers/accredited_providers/checks_controller.rb
  app/controllers/publish/providers/accredited_providers_controller.rb
  app/forms/publish/accredited_provider_form.rb
  app/helpers/goto_confirmation_helper.rb
  app/helpers/support/goto_confirmation_helper.rb
  app/views/publish/providers/accredited_provider_search/new.html.erb
  app/views/publish/providers/accredited_provider_search/results.html.erb
  app/views/publish/providers/accredited_providers/checks/show.html.erb
  app/views/publish/providers/accredited_providers/index.html.erb
  app/views/publish/providers/accredited_providers/new.html.erb
  config/locales/en.yml
  config/routes/publish.rb
  spec/features/publish/accredited_provider_spec.rb
Labels: deploy

#3567 [1292] Fix school search bug
  Gemfile.lock
  Procfile.dev
  app/controllers/publish/providers/school_search_controller.rb
  app/javascript/publish/application.js
  app/javascript/publish/autocomplete.js
  app/views/publish/providers/school_search/new.html.erb
Labels: deploy

#3563 [1232] Providers add edit accrediting provider step 1 js version
  app/controllers/publish/providers/accredited_provider_search_controller.rb
  app/javascript/publish/application.js
  app/javascript/publish/autocomplete.js
  app/javascript/publish/autocomplete/__snapshots__/accredited_provider.spec.js.snap
  app/javascript/publish/autocomplete/__snapshots__/autocomplete.spec.js.snap
  app/javascript/publish/autocomplete/__snapshots__/provider.spec.js.snap
  app/javascript/publish/autocomplete/__snapshots__/school.spec.js.snap
  app/javascript/publish/autocomplete/accredited_provider.js
  app/javascript/publish/autocomplete/accredited_provider.spec.js
  app/javascript/publish/autocomplete/autocomplete.js
  app/javascript/publish/autocomplete/autocomplete.spec.js
  app/javascript/publish/autocomplete/index.js
  app/javascript/publish/autocomplete/provider.js
  app/javascript/publish/autocomplete/provider.spec.js
  app/javascript/publish/autocomplete/school.js
  app/javascript/publish/autocomplete/school.spec.js
  app/views/publish/providers/accredited_provider_search/new.html.erb
Labels: deploy

#3560 [1221] Handle saving of AP in support Flow
  app/components/accredited_provider.html.erb
  app/controllers/publish/providers/accredited_provider_search_controller.rb
  app/controllers/publish/providers/accredited_providers_controller.rb
  app/controllers/publish/providers/school_search_controller.rb
  app/controllers/support/providers/accredited_provider_search_controller.rb
  app/controllers/support/providers/accredited_providers/checks_controller.rb
  app/controllers/support/providers/accredited_providers_controller.rb
  app/forms/accredited_provider_form.rb
  app/forms/publish/accredited_provider_form.rb
  app/forms/support/accredited_provider_form.rb
  app/javascript/publish/autocomplete/__snapshots__/school.spec.js.snap
  app/javascript/publish/autocomplete/school.js
  app/views/layouts/application.html.erb
  app/views/layouts/provider_record.html.erb
  app/views/publish/providers/accredited_provider_search/new.html.erb
  app/views/publish/providers/accredited_providers/index.html.erb
  app/views/publish/providers/accredited_providers/new.html.erb
  app/views/publish/providers/school_search/new.html.erb
  app/views/support/providers/accredited_provider_search/new.html.erb
  app/views/support/providers/accredited_providers/index.html.erb
  config/locales/en.yml
  spec/features/publish/searching_for_a_school_spec.rb
  spec/features/support/providers/accredited_provider_search/searching_for_an_accredited_provider_spec.rb
  spec/forms/accredited_provider_form_spec.rb
  spec/forms/publish/accredited_provider_form_spec.rb
Labels: deploy

#3575 1228 support edit accrediting provider
  app/controllers/support/providers/accredited_providers_controller.rb
  app/views/support/providers/accredited_providers/edit.html.erb
  app/views/support/providers/accredited_providers/index.html.erb
  config/locales/en.yml
  config/routes/support.rb
  spec/features/support/providers/accredited_providers_edit_spec.rb
Labels: deploy

#3574 [1235] Remove a accredited provider (providers)
  app/controllers/publish/providers/accredited_providers_controller.rb
  app/views/publish/providers/accredited_providers/_can_remove.html.erb
  app/views/publish/providers/accredited_providers/_cannot_remove.html.erb
  app/views/publish/providers/accredited_providers/delete.html.erb
  app/views/publish/providers/accredited_providers/index.html.erb
  config/locales/en.yml
  config/routes/publish.rb
  spec/features/publish/accredited_provider_spec.rb
Labels: deploy

#3578 [1283] Add `application_status` to `course` table
  app/models/course.rb
  config/analytics.yml
  db/migrate/20230522132741_add_application_status_to_course.rb
  db/schema.rb
  docs/database-diagram.jpg
  spec/models/course_spec.rb
Labels: deploy

#3579 [1229] delete support accredited provider
  app/controllers/publish/providers/accredited_providers_controller.rb
  app/controllers/support/providers/accredited_providers_controller.rb
  app/views/support/providers/accredited_providers/_can_remove.html.erb
  app/views/support/providers/accredited_providers/_cannot_remove.html.erb
  app/views/support/providers/accredited_providers/delete.html.erb
  app/views/support/providers/accredited_providers/edit.html.erb
  app/views/support/providers/accredited_providers/index.html.erb
  config/locales/en.yml
  config/routes/support.rb
  spec/features/support/providers/accredited_providers_spec.rb
Labels: deploy

#3588 [1321] Remove change vacancies from course show page
  app/services/feature_service.rb
  app/views/publish/courses/course_button_panel/_published.html.erb
Labels: deploy

#3587 [1287] Remove vacancies on Find
  app/components/find/courses/about_schools_component/view.html.erb
  app/views/find/courses/_course_closed.html.erb
  app/views/find/courses/show.html.erb
Labels: deploy

#3592 [1314] rm vacancies on course index
  app/views/publish/courses/_course_table.html.erb
  app/views/publish/courses/_course_table_row.html.erb
Labels: deploy

#3593 [1315] Add applications open confirm page
  app/controllers/publish/courses/application_status_controller.rb
  app/views/publish/courses/application_status/new.html.erb
  config/locales/en.yml
  config/routes/publish.rb
  spec/features/publish/courses/editing_application_status_spec.rb
Labels: deploy

#3591 [1302] Add floodlight tags to CSP
  app/views/cookie_preferences/show.html.erb
  app/views/find/cookie_preferences/show.html.erb
  config/initializers/content_security_policy.rb
  config/settings.yml
  config/settings/production.yml
Labels: deploy

#3597 [1317] close course page
  app/controllers/publish/courses/application_status_controller.rb
  app/views/publish/courses/application_status/_body_text.html.erb
  app/views/publish/courses/application_status/_headline.html.erb
  app/views/publish/courses/application_status/new.html.erb
  config/locales/en.yml
  config/routes/publish.rb
  spec/features/publish/courses/editing_application_status_spec.rb
Labels: deploy

#3600 [1324] Add study site schema
  app/models/course.rb
  app/models/provider.rb
  app/models/site.rb
  app/models/study_site_placement.rb
  config/analytics.yml
  db/migrate/20230530113037_create_study_site_placement.rb
  db/migrate/20230530125755_add_type_to_site.rb
  db/schema.rb
  docs/database-diagram.jpg
  spec/factories/sites.rb
  spec/factories/study_site_placements.rb
  spec/models/course_spec.rb
  spec/models/provider_spec.rb
  spec/models/site_spec.rb
  spec/models/study_site_placement_spec.rb
Labels: deploy

#3603 [1318] `status_tag` depend on `application_status`
  app/decorators/application_decorator.rb
  spec/features/publish/courses/editing_application_status_spec.rb
Labels: deploy
