Repository DFE-Digital/publish-teacher-training, pull requests merged in 2023-11, with the labels that each got.

#3906 [859] Update content on visa question
  app/views/find/search/visa_status/new.html.erb
  config/locales/find.yml
  spec/features/find/search/across_england/further_education_spec.rb
  spec/features/find/search/across_england/primary_spec.rb
  spec/features/find/search/across_england/secondary_spec.rb
  spec/features/find/search/editing_a_search_spec.rb
Labels: deploy_v2

#3910 [890] Add visa sponsorship edit functionality to support
  app/controllers/support/courses_controller.rb
  app/forms/support/edit_course_form.rb
  app/views/support/courses/edit.html.erb
  spec/features/support/providers/courses/editing_visa_sponsorship_spec.rb
Labels: deploy_v2

#3912 [891] Enable support to search by UKPRN
  app/models/provider.rb
  app/views/support/providers/_list.html.erb
  config/locales/en.yml
  spec/components/filter/provider_attributes/view_spec.rb
  spec/features/support/providers/providers_filter_spec.rb
Labels: deploy_v2

#3918 Update width on provider index support page
  app/views/support/providers/_list.html.erb
Labels: deploy_v2

#3921 Fix the editing of visa sponsorship and SEND in support
  app/views/support/courses/edit.html.erb
Labels: deploy_v2

#3923 Add missing full stop
  app/views/publish/courses/subjects/_secondary_form.html.erb
Labels: deploy_v2

#3940 Fix CI
  Gemfile
  Gemfile.lock
Labels: do not merge, deploy_v2

#3933 [924] Revert withdrawals (support)
  app/controllers/support/revert_withdrawal_controller.rb
  app/services/support/courses/revert_withdrawal_service.rb
  app/views/support/courses/edit.html.erb
  app/views/support/revert_withdrawal/edit.html.erb
  config/routes/support.rb
  guides/support_playbook.md
  spec/factories/courses.rb
  spec/features/support/providers/courses/reverting_a_withdrawal_spec.rb
  spec/services/support/courses/revert_withdrawal_service_spec.rb
Labels: deploy_v2

#3926 Add dependabot review apps
  .github/workflows/build-and-deploy.yml
Labels: Devops, deploy_v2

#3812 Remove free of charge
  app/views/find/courses/_advice.html.erb
  app/views/layouts/_find_footer.html.erb
Labels: deploy_v2

#3945 Add evaluation_total_count to postgres
  terraform/aks/.terraform.lock.hcl
  terraform/aks/databases.tf
  terraform/aks/variables.tf
  terraform/aks/workspace_variables/staging_aks.tfvars.json
Labels: Devops

#3947 Revert "Add alert_window_size to postgres and redis modules"
  terraform/aks/.terraform.lock.hcl
  terraform/aks/databases.tf
  terraform/aks/variables.tf
  terraform/aks/workspace_variables/staging_aks.tfvars.json
Labels: Devops

#3949 Allow providers to change the visa sponsorship value
  README.md
  app/views/publish/courses/_basic_details_tab.html.erb
  app/views/publish/courses/details.html.erb
  spec/features/publish/viewing_a_course_details_spec.rb
Labels: deploy_v2
