Repository DFE-Digital/publish-teacher-training, pull requests merged in 2024-07, with the labels that each got.

#4324 Change and remove a required A level
  app/components/a_level_subject_requirement_row_component.rb
  app/controllers/publish/courses/a_level_requirements/a_level_requirements_controller.rb
  app/controllers/publish/courses/a_level_requirements/remove_a_level_subject_confirmation_controller.rb
  app/controllers/publish/courses/a_level_requirements/what_a_level_is_required_controller.rb
  app/models/course.rb
  app/views/publish/courses/a_level_requirements/add_a_level_to_a_list/new.html.erb
  app/views/publish/courses/a_level_requirements/remove_a_level_subject_confirmation/new.html.erb
  app/views/publish/courses/a_level_requirements/what_a_level_is_required/new.html.erb
  app/wizards/a_level_steps/remove_a_level_subject_confirmation.rb
  app/wizards/a_levels_wizard.rb
  app/wizards/a_levels_wizard_store.rb
  app/wizards/remove_a_level_subject_confirmation_store.rb
  app/wizards/what_a_level_is_required_store.rb
  config/locales/en.yml
  config/routes/publish.rb
  spec/controllers/publish/courses/a_level_requirements/what_a_level_is_required_controller_spec.rb
  spec/features/publish/courses/editing_a_levels_tda_course_spec.rb
  spec/models/course_spec.rb
  spec/wizards/a_level_steps/remove_a_level_subject_confirmation_spec.rb
  spec/wizards/a_levels_wizard_store_spec.rb
  spec/wizards/remove_a_level_subject_confirmation_store_spec.rb
  spec/wizards/what_a_level_is_required_store_spec.rb
Labels: deploy_v2

#4313 [453] Omit course start day field on support
  app/views/support/courses/edit.html.erb
  spec/features/support/providers/courses/editing_a_course_spec.rb
  spec/support/page_objects/support/provider/course_edit.rb
Labels: deploy_v2

#4320 Change the content of the course view
  app/components/find/courses/contents_component/view.html.erb
  app/components/find/courses/entry_requirements_component/view.html.erb
  app/components/find/courses/international_students_component/view.html.erb
  app/views/find/courses/show.html.erb
  app/views/publish/courses/preview.html.erb
  config/locales/find.yml
  spec/components/find/courses/entry_requirements_component/view_spec.rb
  spec/components/find/courses/international_students_component/view_spec.rb
  spec/features/find/search/viewing_a_course_spec.rb
  spec/features/publish/viewing_a_course_preview_spec.rb
Labels: deploy_v2

#4326 Edge case - Redirect away from adding more A level subjects when maximum A levels
  app/controllers/publish/courses/a_level_requirements/what_a_level_is_required_controller.rb
  spec/controllers/publish/courses/a_level_requirements/what_a_level_is_required_controller_spec.rb
Labels: deploy_v2

#4331 Move school placements into its own view
  app/components/find/courses/about_schools_component/view.html.erb
  app/components/find/courses/about_schools_component/view.rb
  app/controllers/find/placements_controller.rb
  app/controllers/publish/courses/school_placements_controller.rb
  app/models/course.rb
  app/views/find/placements/index.html.erb
  app/views/publish/courses/school_placements/index.html.erb
  app/views/shared/courses/_placements.html.erb
  config/locales/en.yml
  config/locales/find.yml
  config/routes/find.rb
  config/routes/publish.rb
  spec/components/find/courses/about_schools_component/view_spec.rb
  spec/controllers/find/placements_controller_spec.rb
  spec/features/find/search/viewing_a_course_spec.rb
  spec/features/publish/viewing_a_course_preview_spec.rb
  spec/models/course_spec.rb
Labels: deploy_v2

#4327 A levels - Add find preview for TDA courses on publish
  app/components/a_level_row_component.rb
  app/components/a_level_subject_requirement_row_component.rb
  app/components/find/courses/a_level_component/grouped_a_level_subject_requirements.rb
  app/components/find/courses/a_level_component/view.html.erb
  app/components/find/courses/a_level_component/view.rb
  app/components/find/courses/entry_requirements_component/view.html.erb
  app/components/find/courses/teacher_degree_apprenticeship_entry_requirements/view.html.erb
  app/components/find/courses/teacher_degree_apprenticeship_entry_requirements/view.rb
  config/locales/en.yml
  config/locales/find.yml
  spec/components/find/courses/a_level_component/grouped_a_level_subject_requirements_spec.rb
  spec/components/find/courses/a_level_component/view_spec.rb
  spec/components/find/courses/entry_requirements_component/view_preview.rb
  spec/components/find/courses/entry_requirements_component/view_spec.rb
  spec/components/find/courses/teacher_degree_apprenticeship_entry_requirements/view_spec.rb
  spec/features/publish/preview_teacher_degree_apprenticeship_course_spec.rb
Labels: deploy_v2

#4334 Add send_traffic for maintenace page
  terraform/aks/.terraform.lock.hcl
  terraform/aks/application.tf
  terraform/aks/variables.tf
Labels: Devops

#4339 Validating A levels when publishing for teacher degree apprenticeship courses
  app/components/a_level_row_component.html.erb
  app/components/a_level_row_component.rb
  app/controllers/publish/courses/a_level_requirements/a_level_requirements_controller.rb
  app/helpers/application_helper.rb
  app/helpers/view_helper.rb
  app/models/course.rb
  app/validators/a_level_course_validator.rb
  app/views/publish/courses/_description_content.html.erb
  config/locales/en.yml
  spec/components/a_level_row_component_spec.rb
  spec/features/publish/courses/new_tda_course_spec.rb
  spec/features/publish/courses/publishing_a_teacher_degree_apprenticeship_course_with_validation_errors_spec.rb
  spec/models/course/publishable_spec.rb
  spec/support/page_objects/publish/provider_courses_show.rb
Labels: deploy_v2

#4338 Update github actions versions
  .github/actions/deploy_v2/action.yml
  .github/actions/restore/action.yml
Labels: Devops, deploy_v2

#4346 [225] Update wording to reflect multiple study sites
  app/components/find/courses/about_schools_component/view.html.erb
Labels: deploy_v2

#4330 Rollout workload identity federation to all environments
  config/initializers/dfe_analytics.rb
  terraform/aks/application.tf
Labels: deploy_v2

#4348 Remove first page of the A levels
  app/components/a_level_row_component.html.erb
  app/components/a_level_row_component.rb
  app/components/find/courses/a_level_component/view.html.erb
  app/components/find/courses/a_level_component/view.rb
  app/components/find/courses/teacher_degree_apprenticeship_entry_requirements/view.html.erb
  app/controllers/publish/courses/a_level_requirements/are_any_a_levels_required_for_this_course_controller.rb
  app/decorators/course_decorator.rb
  app/helpers/view_helper.rb
  app/validators/a_level_course_validator.rb
  app/views/publish/courses/_description_content.html.erb
  app/views/publish/courses/a_level_requirements/add_a_level_to_a_list/new.html.erb
  app/views/publish/courses/a_level_requirements/are_any_a_levels_required_for_this_course/new.html.erb
  app/views/publish/courses/a_level_requirements/what_a_level_is_required/new.html.erb
  app/wizards/a_level_steps/are_any_a_levels_required_for_this_course.rb
  app/wizards/a_levels_wizard.rb
  app/wizards/a_levels_wizard_store.rb
  app/wizards/are_any_a_levels_required_store.rb
  app/wizards/remove_a_level_subject_confirmation_store.rb
  config/locales/en.yml
  config/locales/find.yml
  config/routes/publish.rb
  spec/components/a_level_row_component_spec.rb
  spec/components/find/courses/a_level_component/view_spec.rb
  spec/components/find/courses/teacher_degree_apprenticeship_entry_requirements/view_spec.rb
  spec/controllers/publish/courses/a_level_requirements/are_any_a_levels_required_for_this_course_controller_spec.rb
  spec/decorators/course_decorator_spec.rb
  spec/factories/courses.rb
  spec/features/publish/courses/editing_a_levels_tda_course_spec.rb
  spec/features/publish/courses/new_tda_course_spec.rb
  spec/features/publish/courses/publishing_a_teacher_degree_apprenticeship_course_with_validation_errors_spec.rb
  spec/models/course/publishable_spec.rb
  spec/wizards/a_level_steps/are_any_a_levels_required_for_this_course_spec.rb
  spec/wizards/a_levels_wizard_store_spec.rb
  spec/wizards/are_any_a_levels_required_store_spec.rb
  spec/wizards/remove_a_level_subject_confirmation_store_spec.rb
Labels: deploy_v2

#4352 Don't show the A level change link when the course is withdrawn
  app/decorators/course_decorator.rb
  spec/decorators/course_decorator_spec.rb
Labels: deploy_v2

#4355 [2016] Prevent the creation of a user which already exists under the same provider
  app/controllers/publish/users_controller.rb
  app/controllers/support/providers/users_controller.rb
  app/forms/user_form.rb
  spec/features/publish/managing_users_spec.rb
  spec/features/support/providers/users/adding_user_to_provider_spec.rb
Labels: deploy_v2

#4343 Add provider & accrediting_provider views course
  app/components/course_preview/missing_information_component.rb
  app/components/find/courses/about_schools_component/view.rb
  app/components/find/courses/contact_details_component/view.html.erb
  app/components/find/courses/contents_component/view.html.erb
  app/components/find/courses/qualifications_summary_component/view.html.erb
  app/components/find/courses/summary_component/view.html.erb
  app/components/find/courses/summary_component/view.rb
  app/controllers/concerns/goto_preview.rb
  app/controllers/find/courses/accrediting_providers_controller.rb
  app/controllers/find/courses/providers_controller.rb
  app/controllers/publish/courses/accredited_provider_controller.rb
  app/controllers/publish/courses/providers_controller.rb
  app/controllers/publish/providers_controller.rb
  app/helpers/find/goto_preview_helper.rb
  app/helpers/preview_helper.rb
  app/views/find/courses/_about_accrediting_provider.html.erb
  app/views/find/courses/_about_the_provider.html.erb
  app/views/find/courses/accrediting_providers/show.html.erb
  app/views/find/courses/providers/show.html.erb
  app/views/find/courses/show.html.erb
  app/views/publish/courses/accredited_provider/show.html.erb
  app/views/publish/courses/preview.html.erb
  app/views/publish/courses/providers/show.html.erb
  app/views/publish/providers/about.html.erb
  config/locales/en.yml
  config/locales/find.yml
  config/routes/find.rb
  config/routes/publish.rb
  spec/components/course_preview/missing_information_component_spec.rb
  spec/components/find/courses/about_schools_component/view_spec.rb
  spec/components/find/courses/sumary_component/view_preview.rb
  spec/components/find/courses/sumary_component/view_spec.rb
  spec/components/find/results/results_component_spec.rb
  spec/controllers/concerns/goto_preview_spec.rb
  spec/features/find/search/viewing_a_course_spec.rb
  spec/features/publish/viewing_a_course_preview_spec.rb
  spec/helpers/find/goto_preview_helper_spec.rb
  spec/support/page_objects/find/course_show.rb
  spec/support/page_objects/publish/course_preview.rb
Labels: deploy_v2

#4357 Increase alert_window_size to 1h for stg monitors
  terraform/aks/workspace_variables/staging_aks.tfvars.json
Labels: Devops

#4360 [2027] Update apply deadline banner in publish
  app/components/find/deadline_banner_component.html.erb
  app/components/find/deadline_banner_component.rb
  config/locales/deadline_banner_component.yml
  spec/components/find/deadline_banner_component_preview.rb
  spec/components/find/deadline_banner_component_spec.rb
  spec/features/find/switcher_cycles_spec.rb
Labels: deploy_v2

#4359 [1755] Remove redundant code relating to personal qualities and other requirements
  app/controllers/publish/courses/requirements_controller.rb
  app/controllers/publish/courses_controller.rb
  app/forms/publish/course_requirement_form.rb
  app/helpers/publish_helper.rb
  app/models/provider.rb
  app/services/courses/copy.rb
  app/views/publish/courses/_description_content.html.erb
  app/views/publish/courses/confirmation.html.erb
  app/views/publish/courses/requirements/edit.html.erb
  config/locales/en.yml
  config/routes/publish.rb
  spec/components/find/courses/entry_requirements_component/view_preview.rb
  spec/factories/course_enrichments.rb
  spec/features/find/search/viewing_a_course_spec.rb
  spec/features/publish/courses/editing_course_requirements_2024_spec.rb
  spec/features/publish/courses/editing_course_requirements_2025_spec.rb
  spec/features/publish/viewing_a_course_2025_spec.rb
  spec/features/publish/viewing_a_course_spec.rb
  spec/support/page_objects/find/course_show.rb
  spec/support/page_objects/publish/course_preview.rb
  spec/support/page_objects/publish/course_requirement_edit.rb
  spec/support/page_objects/publish/provider_courses_show.rb
Labels: deploy_v2

#4363 [1996] Update validation error message for `applications_open_from`
  app/models/course.rb
  spec/forms/edit_course_form_spec.rb
  spec/models/course_spec.rb
Labels: deploy_v2

#4358 Training with disabilities view on courses
  app/components/course_preview/missing_information_component.rb
  app/components/find/courses/contents_component/view.html.erb
  app/controllers/concerns/goto_preview.rb
  app/controllers/find/courses/training_with_disabilities_controller.rb
  app/controllers/publish/courses/training_with_disabilities_controller.rb
  app/controllers/publish/providers_controller.rb
  app/forms/publish/about_your_organisation_form.rb
  app/helpers/find/goto_preview_helper.rb
  app/helpers/preview_helper.rb
  app/views/find/courses/_train_with_disabilities.html.erb
  app/views/find/courses/show.html.erb
  app/views/find/courses/training_with_disabilities/show.html.erb
  app/views/publish/courses/preview.html.erb
  app/views/publish/courses/training_with_disabilities/show.html.erb
  app/views/publish/providers/about.html.erb
  config/locales/en.yml
  config/locales/find.yml
  config/routes/find.rb
  config/routes/publish.rb
  spec/components/course_preview/missing_information_component_spec.rb
  spec/controllers/concerns/goto_preview_spec.rb
  spec/features/find/search/viewing_a_course_spec.rb
  spec/features/publish/viewing_a_course_preview_spec.rb
  spec/forms/publish/about_your_organisation_form_spec.rb
  spec/helpers/find/goto_preview_helper_spec.rb
Labels: deploy_v2

#4366 Redesign visa sponsorship on course page
  app/components/find/courses/contents_component/view.html.erb
  app/components/find/courses/international_students_component/view.html.erb
  app/components/find/courses/international_students_component/view.rb
  app/components/find/courses/summary_component/view.html.erb
  app/components/find/courses/summary_component/view.rb
  app/helpers/view_helper.rb
  app/views/find/courses/show.html.erb
  app/views/publish/courses/preview.html.erb
  config/locales/find.yml
  spec/components/find/courses/international_students_component/view_spec.rb
  spec/features/find/search/viewing_a_course_spec.rb
  spec/features/publish/viewing_a_course_preview_spec.rb
  spec/helpers/view_helper_spec.rb
  spec/support/page_objects/find/course_show.rb
Labels: deploy_v2

#4365 Increase alert_window_size to 6h for stg monitors
  terraform/aks/workspace_variables/staging_aks.tfvars.json
Labels: Devops

#4369 Redesign support and advice section on course page
  app/assets/stylesheets/components/shared/_advice.scss
  app/views/find/courses/_advice.html.erb
  app/views/find/courses/show.html.erb
  app/views/publish/courses/preview.html.erb
  config/locales/find.yml
Labels: deploy_v2

#4367 Change tda to non tda and vice versa
  app/controllers/concerns/study_mode_vacancy_mapper.rb
  app/controllers/publish/courses/outcome_controller.rb
  app/models/concerns/courses/edit_options/qualification_concern.rb
  app/models/course.rb
  app/policies/course_policy.rb
  app/views/publish/courses/_basic_details_tab.html.erb
  spec/controllers/publish/courses/outcome_controller_spec.rb
  spec/features/publish/courses/publishing_a_teacher_degree_apprenticeship_course_with_validation_errors_spec.rb
  spec/models/concerns/courses/edit_options/qualification_concern_spec.rb
  spec/models/concerns/courses/edit_options_spec.rb
  spec/models/course_spec.rb
  spec/policies/course_policy_spec.rb
Labels: deploy_v2

#4364 Give a course with no enrichments being rolled over an enrichment
  app/services/courses/copy_to_provider_service.rb
  spec/features/publish/viewing_a_course_spec.rb
Labels: deploy_v2

#4361 Added Radius filter to Search results
  app/forms/find/location_filter_form.rb
  app/view_objects/find/result_filters/filters_view.rb
  app/view_objects/find/results_view.rb
  app/views/find/result_filters/_all.html.erb
  app/views/find/result_filters/_radius.html.erb
  config/locales/find.yml
  spec/features/find/search/location_options_spec.rb
  spec/view_objects/find/result_filters/filters_view_spec.rb
Labels: deploy_v2

#4379 Update next cycle open date
  config/settings.yml
Labels: deploy_v2

#4381 Added age range to course summary in search results
  app/components/find/results/search_result_component.html.erb
  app/components/find/results/search_result_component.rb
  app/decorators/course_decorator.rb
  spec/components/find/results/search_result_component_spec.rb
  spec/decorators/course_decorator_spec.rb
Labels: deploy_v2

#4374 New format for Course show entry requirements
  app/components/find/courses/a_level_component/view.html.erb
  app/components/find/courses/entry_requirements_component/view.html.erb
  app/components/find/courses/entry_requirements_component/view.rb
  app/components/find/courses/summary_component/view.html.erb
  app/components/find/courses/teacher_degree_apprenticeship_entry_requirements/view.html.erb
  app/components/find/courses/teacher_degree_apprenticeship_entry_requirements/view.rb
  app/models/course.rb
  config/locales/find.yml
  spec/components/find/courses/a_level_component/view_spec.rb
  spec/components/find/courses/entry_requirements_component/view_preview.rb
  spec/components/find/courses/entry_requirements_component/view_spec.rb
  spec/components/find/courses/sumary_component/view_spec.rb
  spec/components/find/courses/teacher_degree_apprenticeship_entry_requirements/view_spec.rb
  spec/features/find/search/viewing_a_course_spec.rb
  spec/features/publish/viewing_a_course_preview_spec.rb
  spec/models/course_spec.rb
Labels: deploy_v2

#4382 Change Find service name now that we are accepting undersgraduate courses
  app/components/find/phase_banner/view.html.erb
  app/jobs/find/slack_notification_job.rb
  app/views/find/pages/accessibility.html.erb
  app/views/find/pages/privacy.html.erb
  app/views/find/pages/terms.html.erb
  app/views/pages/add_an_organisation.html.erb
  app/views/pages/add_schools_and_study_sites.html.erb
  app/views/pages/course_summary_examples.erb
  app/views/pages/help_writing_course_descriptions.html.erb
  app/views/pages/how_to_use_this_service.html.erb
  app/views/pages/privacy.html.erb
  app/views/pages/roll_over_courses_to_a_new_recruitment_cycle.html.erb
  app/views/pages/terms.html.erb
  app/views/publish/courses/_course_table.html.erb
  app/views/publish/courses/course_button_panel/_published.html.erb
  app/views/publish/notifications/index.html.erb
  app/views/publish/shared/_aside_information_box.html.erb
  config/locales/en.yml
  service_unavailable_page/web/public/internal/find.html
  spec/components/find/phase_banner/view_spec.rb
  spec/features/find/view_pages_spec.rb
  swagger/public_v1/template.yml
Labels: deploy_v2

#4392 Update section headers for courses
  app/components/find/courses/about_schools_component/view.html.erb
  app/components/find/courses/contents_component/view.html.erb
  app/components/find/courses/summary_component/view.html.erb
  app/views/find/courses/_about_course.html.erb
  app/views/find/courses/_advice.html.erb
  app/views/find/courses/show.html.erb
  app/views/publish/courses/preview.html.erb
  config/locales/en.yml
  config/locales/find.yml
  spec/components/course_preview/missing_information_component_spec.rb
  spec/components/find/courses/about_schools_component/view_spec.rb
  spec/components/find/courses/contents_component/view_spec.rb
  spec/features/publish/courses/editing_course_about_this_course_from_preview_page_spec.rb
Labels: deploy_v2

#4393 Reformat summary course
  app/components/find/courses/fees_component/view.html.erb
  app/components/find/courses/summary_component/view.html.erb
  app/components/find/courses/summary_component/view.rb
  config/locales/find.yml
  spec/components/find/courses/fees_component/view_spec.rb
  spec/components/find/courses/sumary_component/view_spec.rb
  spec/features/find/search/viewing_a_course_spec.rb
  spec/features/publish/viewing_a_course_preview_spec.rb
Labels: deploy_v2

#4395 Accordion for non UK citizen section course page
  app/assets/stylesheets/components/shared/_accordion.scss
  app/assets/stylesheets/find_application.scss
  app/assets/stylesheets/publish_application.scss
  app/components/find/courses/entry_requirements_component/view.html.erb
  config/locales/find.yml
  spec/components/find/courses/entry_requirements_component/view_spec.rb
Labels: deploy_v2

#4396 Entry requirements before contents list on course
  app/components/find/courses/contents_component/view.html.erb
  app/views/find/courses/show.html.erb
  app/views/publish/courses/preview.html.erb
Labels: deploy_v2

#4399 Change back link when user comes from the course page while trying to publish the course
  app/views/publish/courses/a_level_requirements/a_level_equivalencies/new.html.erb
  app/views/publish/courses/a_level_requirements/consider_pending_a_level/new.html.erb
  spec/features/publish/courses/publishing_a_teacher_degree_apprenticeship_course_with_validation_errors_spec.rb
Labels: deploy_v2

#4403 Move salary before fees on course show pages
  app/components/find/courses/contents_component/view.html.erb
  app/views/find/courses/show.html.erb
  app/views/publish/courses/preview.html.erb
Labels: deploy_v2

#4398 Update results format for the course index page
  app/assets/stylesheets/components/find/_search-results.scss
  app/assets/stylesheets/components/find/_summary-card.scss
  app/components/find/courses/entry_requirements_component/view.html.erb
  app/components/find/courses/entry_requirements_component/view.rb
  app/components/find/courses/summary_component/view.html.erb
  app/components/find/courses/summary_component/view.rb
  app/components/find/results/results_component.html.erb
  app/components/find/results/search_result_component.html.erb
  app/components/find/results/search_result_component.rb
  app/decorators/course_decorator.rb
  app/view_objects/find/results_view.rb
  app/views/find/results/_non_university.html.erb
  app/views/find/results/_university.html.erb
  config/locales/en.yml
  config/locales/find.yml
  spec/components/find/courses/entry_requirements_component/view_preview.rb
  spec/components/find/courses/entry_requirements_component/view_spec.rb
  spec/components/find/courses/sumary_component/view_spec.rb
  spec/components/find/results/results_component_spec.rb
  spec/components/find/results/search_result_component_spec.rb
  spec/decorators/course_decorator_spec.rb
  spec/features/find/search/course_results_spec.rb
Labels: deploy_v2

#4397 Change Find domain links in all of our services
  README.md
  config/initializers/canonical_rails.rb
  config/initializers/content_security_policy.rb
  config/locales/en.yml
  config/settings/production.yml
  config/settings/production_aks.yml
  config/settings/qa.yml
  config/settings/qa_aks.yml
  config/settings/review.yml
  config/settings/review_aks.yml
  config/settings/sandbox.yml
  config/settings/sandbox_aks.yml
  config/settings/staging.yml
  config/settings/staging_aks.yml
  config/settings/test.yml
  maintenance_page/manifests/production_aks/ingress_external_to_main.yml
  maintenance_page/manifests/production_aks/ingress_external_to_maintenance.yml
  maintenance_page/manifests/qa_aks/ingress_external_to_main.yml
  maintenance_page/manifests/qa_aks/ingress_external_to_maintenance.yml
  public/robots.txt
  service_unavailable_page/web/nginx.conf
Labels: deploy_v2

#4406 Add google to content security policy
  config/initializers/content_security_policy.rb
Labels: deploy_v2

#4407 Add google double click to content security policy
  config/initializers/content_security_policy.rb
Labels: deploy_v2

#4404 [1876] Ensure `program_type` is updated when `provider_type` changes
  app/models/provider.rb
  app/services/courses/assign_program_type_service.rb
  spec/features/publish/courses/new_tda_course_spec.rb
  spec/models/course/assign_program_type_spec.rb
  spec/models/course_spec.rb
  spec/models/provider_spec.rb
  spec/services/courses/copy_to_provider_service_spec.rb
Labels: deploy_v2

#4410 [1876] Ensure `program_type_service` correctly handles TDA courses
  app/services/courses/assign_program_type_service.rb
  spec/models/course/assign_program_type_spec.rb
Labels: deploy_v2

#4414 Add qualification tda content
  app/components/find/courses/qualifications_summary_component/view.html.erb
  config/locales/find.yml
  spec/components/find/courses/qualifications_summary_component/view_spec.rb
Labels: deploy_v2
