Repository DFE-Digital/publish-teacher-training, pull requests merged in 2024-01, with the labels that each got.

#3986 Update download-artifact to v4
  .github/actions/restore/action.yml
Labels: Devops

#3983 Enable entity_table_check_job
  Gemfile
  Gemfile.lock
  config/initializers/dfe_analytics.rb
  config/settings/production.yml
Labels: deploy_v2

#4003 Refactor references to provider codes in view templates
  app/components/find/courses/about_schools_component/view.html.erb
  app/components/find/courses/about_schools_component/view.rb
  app/components/find/courses/contact_details_component/view.html.erb
  app/components/find/courses/contact_details_component/view.rb
  app/controllers/publish/courses/course_information_controller.rb
  app/services/configs/course_information.rb
  app/views/publish/courses/course_information/edit.html.erb
  config/course_information.yml
  spec/components/find/courses/about_schools_component/view_preview.rb
  spec/components/find/courses/contact_details_component/view_spec.rb
  spec/features/publish/courses/editing_course_information_guidance_spec.rb
  spec/services/configs/course_information_spec.rb
Labels: deploy_v2

#4019 Fix production check
  app/controllers/find/feature_flags_controller.rb
  app/services/find/cycle_timetable.rb
  app/views/find/switcher/cycles.html.erb
  config/application.rb
  spec/rails_helper.rb
Labels: deploy_v2

#4020 Refactor production check
  app/controllers/find/feature_flags_controller.rb
  app/services/find/cycle_timetable.rb
  app/views/find/switcher/cycles.html.erb
  config/application.rb
  config/rubocop/rails.yml
  spec/rails_helper.rb
Labels: deploy_v2

#4026 [937] Enable Azure RBAC authentication on AKS
  .github/actions/deploy_v2/action.yml
  .github/actions/restore/action.yml
  .github/workflows/build-and-deploy.yml
  .github/workflows/database-restore.yml
  .github/workflows/delete-v2-review-app.yml
  .github/workflows/deploy-v2-review-app.yml
  .github/workflows/deploy-v2.yml
  .gitignore
  .tool-versions
  Makefile
  app/views/pages/privacy.html.erb
  bin/backup-review-database
  bin/dev
  bin/restore-nightly-backup
  global_config/dv_review_aks.sh
  global_config/find-domain.sh
  global_config/production_aks.sh
  global_config/publish-domain.sh
  global_config/qa_aks.sh
  global_config/review_aks.sh
  global_config/sandbox_aks.sh
  global_config/staging_aks.sh
  guides/aks-cheatsheet.md
  guides/authentication.md
  guides/disaster-recovery.md
  guides/maintenance-mode.md
  guides/setup-development.md
  terraform/aks/.terraform.lock.hcl
  terraform/aks/providers.tf
  terraform/aks/variables.tf
  terraform/custom_domains/infrastructure/terraform.tf
Labels: deploy, deploy_v2

#4033 [937] Add missing kubelogin to DB restore workflow
  .github/actions/restore/action.yml
  .github/workflows/database-restore.yml
Labels: Devops
