Repository DFE-Digital/publish-teacher-training, pull requests merged in 2024-05, with the labels that each got.

#4187 Make sure apply button on Find searches for case insensitive codes
  app/controllers/concerns/apply_redirect.rb
  app/models/provider.rb
  spec/controllers/find/courses_controller_spec.rb
Labels: deploy_v2

#4193 [1558] Authenticate before displaying the terms and conditions
  app/controllers/publish/terms_controller.rb
  spec/features/publish/accepting_terms_spec.rb
Labels: deploy_v2

#4200 Statuscake SSL alerts removed qa,sandbox,staging and prod
  terraform/aks/statuscake.tf
Labels: Devops

#4203 Execute a connection to the database on healtcheck
  app/controllers/heartbeat_controller.rb
Labels: deploy_v2

#4197 1563 publish move send onto its own page in the publish flow and change to radio buttons
  app/controllers/publish/courses/level_controller.rb
  app/models/course.rb
  app/views/publish/courses/level/new.html.erb
  app/views/publish/courses/send/_form_fields.html.erb
  config/locales/en.yml
  db/migrate/20240513145101_remove_default_from_course_is_send.rb
  db/schema.rb
  db/seeds.rb
  docs/database-diagram.jpg
  spec/features/publish/courses/new_level_spec.rb
  spec/features/publish/e2e/new_course_spec.rb
  spec/support/page_objects/publish/courses/new_level.rb
Labels: deploy_v2

#4206 [1671] Add course flow TDA changes
  app/controllers/publish/courses/outcome_controller.rb
  app/decorators/course_decorator.rb
  app/models/concerns/courses/edit_options/qualification_concern.rb
  app/models/concerns/with_qualifications.rb
  app/models/course.rb
  app/services/courses/creation_service.rb
  app/services/workflow_step_service.rb
  app/views/publish/courses/_basic_details_tab.html.erb
  app/views/publish/courses/confirmation.html.erb
  config/locales/en.yml
  spec/decorators/course_decorator_spec.rb
  spec/factories/courses.rb
  spec/features/publish/courses/new_tda_course_spec.rb
  spec/models/concerns/courses/edit_options/qualification_concern_spec.rb
  spec/models/course_spec.rb
  spec/requests/reporting_spec.rb
  spec/services/course_reporting_service_spec.rb
  spec/services/workflow_step_service_spec.rb
  spec/support/page_objects/publish/course_confirmation.rb
  spec/support/page_objects/publish/courses/new_outcome.rb
Labels: deploy_v2

#4211 Add test for teacher degree apprentice and further education
  spec/features/publish/courses/new_tda_course_spec.rb
Labels: deploy_v2

#4212 Set default degree requirements for TDA courses
  app/services/courses/creation_service.rb
  spec/features/publish/courses/new_tda_course_spec.rb
  spec/services/courses/creation_service_spec.rb
Labels: deploy_v2

#4213 Don't show the degree requirements section on TDA courses
  app/decorators/course_decorator.rb
  app/views/publish/courses/_description_content.html.erb
  spec/features/publish/courses/new_tda_course_spec.rb
Labels: deploy_v2

#4207 [1567] full-time part-time study change from radio buttons to checkboxes
  app/controllers/publish/courses/study_mode_controller.rb
  app/controllers/publish/courses_controller.rb
  app/forms/publish/course_study_mode_form.rb
  app/models/concerns/courses/edit_options/study_mode_concern.rb
  app/models/concerns/publish/course_basic_detail_concern.rb
  app/services/courses/creation_service.rb
  app/views/publish/courses/_basic_details_tab.html.erb
  app/views/publish/courses/confirmation.html.erb
  app/views/publish/courses/study_mode/_form_fields.html.erb
  app/views/publish/courses/study_mode/edit.html.erb
  app/views/publish/courses/study_mode/new.html.erb
  config/locales/en.yml
  spec/features/publish/courses/editing_course_study_mode_spec.rb
  spec/features/publish/courses/new_funding_type_spec.rb
  spec/features/publish/courses/new_study_mode_spec.rb
  spec/features/publish/e2e/new_course_spec.rb
  spec/forms/publish/course_study_mode_form_spec.rb
  spec/services/courses/creation_service_spec.rb
  spec/support/feature_helpers/new_course_param_helper.rb
  spec/support/page_objects/publish/course_study_mode_edit.rb
  spec/support/page_objects/publish/courses/new_study_mode.rb
Labels: deploy_v2

#4221 1675 add 4 year default for tda courses
  app/services/courses/creation_service.rb
  spec/features/publish/courses/new_tda_course_spec.rb
  spec/services/courses/creation_service_spec.rb
Labels: deploy_v2

#4222 [1576] Move Course Length to its own page
  app/controllers/publish/courses/fees_controller.rb
  app/controllers/publish/courses/length_controller.rb
  app/controllers/publish/courses/salary_controller.rb
  app/forms/publish/course_fee_form.rb
  app/forms/publish/course_length_form.rb
  app/forms/publish/course_salary_form.rb
  app/forms/publish/funding_type_form_methods.rb
  app/services/courses/copy.rb
  app/views/publish/courses/_course_length_field.html.erb
  app/views/publish/courses/_description_content.html.erb
  app/views/publish/courses/_other_course_length_field.html.erb
  app/views/publish/courses/fees/edit.html.erb
  app/views/publish/courses/length/edit.html.erb
  app/views/publish/courses/salary/edit.html.erb
  config/locales/en.yml
  config/routes/publish.rb
  spec/features/publish/courses/editing_course_funding_type_spec.rb
  spec/features/publish/courses/editing_course_length_spec.rb
  spec/features/publish/viewing_a_course_preview_spec.rb
  spec/forms/publish/course_fee_form_spec.rb
  spec/forms/publish/course_length_form_spec.rb
  spec/forms/publish/course_salary_form_spec.rb
  spec/support/page_objects/publish/course_fee_edit.rb
Labels: deploy_v2

#4231 Upgrade ruby patch version
  .github/actions/smoke-test_v2/action.yml
  .tool-versions
  Dockerfile
  Gemfile
  Gemfile.lock
Labels: deploy_v2

#4234 Pin hasicorp-azurerm version to 3.104.2
  terraform/aks/providers.tf
  terraform/custom_domains/environment_domains/terraform.tf
  terraform/custom_domains/infrastructure/terraform.tf
Labels: deploy_v2

#4226 Add spec for back links when TDA
  spec/features/publish/courses/new_tda_course_spec.rb
  spec/support/page_objects/base.rb
Labels: deploy_v2

#4224 Fix duplicate subject validation on secondary course selection
  app/controllers/publish/courses/applications_open_controller.rb
  app/controllers/publish/courses/modern_languages_controller.rb
  app/controllers/publish/courses/subjects_controller.rb
  app/decorators/course_decorator.rb
  app/forms/publish/course_subjects_form.rb
  app/models/course.rb
  app/policies/course_policy.rb
  app/services/courses/assign_program_type_service.rb
  app/services/courses/assign_subjects_service.rb
  app/services/courses/creation_service.rb
  app/services/courses/generate_course_name_service.rb
  app/views/publish/courses/subjects/_secondary_form.html.erb
  config/analytics_blocklist.yml
  config/locales/en.yml
  spec/features/publish/course_confirmation_spec.rb
  spec/features/publish/courses/editing_subject_spec.rb
  spec/features/publish/courses/new_engineers_teach_physics_spec.rb
  spec/features/publish/courses/new_modern_languages_spec.rb
  spec/features/publish/courses/new_primary_subject_spec.rb
  spec/features/publish/courses/new_secondary_subject_spec.rb
  spec/features/publish/courses/new_subject_spec.rb
  spec/models/course_spec.rb
  spec/policies/course_policy_spec.rb
  spec/services/courses/assign_program_type_service_spec.rb
  spec/services/courses/assign_subjects_service_spec.rb
  spec/services/courses/creation_service_spec.rb
  spec/support/page_objects/publish/courses/new_subjects.rb
Labels: deploy_v2

#4241 Enable logit for nonprod environments
  terraform/aks/.terraform.lock.hcl
  terraform/aks/application.tf
  terraform/aks/variables.tf
  terraform/aks/workspace_variables/dv_review_aks.tfvars.json
  terraform/aks/workspace_variables/qa_aks.tfvars.json
  terraform/aks/workspace_variables/review_aks.tfvars.json
  terraform/aks/workspace_variables/staging_aks.tfvars.json
Labels: deploy, deploy_v2
