Repository DFE-Digital/publish-teacher-training, pull requests merged in 2024-12, with the labels that each got.

#4723 Enable ActiveJob in skylight
  config/application.rb
Labels: deploy

#4610 Propose ADR to formalise the Accredited/Training provider relationships
  .adr-dir
  guides/adr/0012-formalize-accredited-provider-relationships.md
  guides/adr/index.md
Labels: ADR

#4729 Replace terrafile
  Makefile
  global_config/dv_review.sh
  global_config/find-domain.sh
  global_config/production.sh
  global_config/publish-domain.sh
  global_config/qa.sh
  global_config/review.sh
  global_config/sandbox.sh
  global_config/staging.sh
  terraform/aks/workspace_variables/dv_review_Terrafile
  terraform/aks/workspace_variables/production_Terrafile
  terraform/aks/workspace_variables/qa_Terrafile
  terraform/aks/workspace_variables/review_Terrafile
  terraform/aks/workspace_variables/sandbox_Terrafile
  terraform/aks/workspace_variables/staging_Terrafile
  terraform/custom_domains/environment_domains/main.tf
  terraform/custom_domains/infrastructure/main.tf
Labels: Devops

#4737 Fix Dockerfile warnings
  Dockerfile
Labels: deploy

#4742 Revert "Use JSON arguments for Dockerfile CMD"
  Dockerfile
Labels: deploy

#4706 Partially disable semantic logger in development
  config/environments/development.rb
Labels: deploy

#4760 Rename SupportController to Support::ApplicationController
  app/controllers/support/application_controller.rb
  app/controllers/support/contact_details_controller.rb
  app/controllers/support/courses_controller.rb
  app/controllers/support/data_exports_controller.rb
  app/controllers/support/providers/accredited_provider_search_controller.rb
  app/controllers/support/providers/accredited_providers/checks_controller.rb
  app/controllers/support/providers/accredited_providers_controller.rb
  app/controllers/support/providers/copy_courses_controller.rb
  app/controllers/support/providers/onboarding/checks_controller.rb
  app/controllers/support/providers/onboarding/contacts_controller.rb
  app/controllers/support/providers/onboardings_controller.rb
  app/controllers/support/providers/schools/check_multiple_controller.rb
  app/controllers/support/providers/schools/multiple_controller.rb
  app/controllers/support/providers/schools/new_multiple_controller.rb
  app/controllers/support/providers/schools_check_controller.rb
  app/controllers/support/providers/users_check_controller.rb
  app/controllers/support/providers/users_controller.rb
  app/controllers/support/providers_controller.rb
  app/controllers/support/recruitment_cycle_controller.rb
  app/controllers/support/revert_withdrawal_controller.rb
  app/controllers/support/schools_controller.rb
  app/controllers/support/user_permissions_controller.rb
  app/controllers/support/users/providers_controller.rb
  app/controllers/support/users_controller.rb
  app/helpers/layout_helper.rb
Labels: deploy

#4775 Remove the cloudfront-rails gem
  Gemfile
  Gemfile.lock
Labels: deploy

#4776 Move TrainingProviders to Providers module
  app/controllers/publish/providers/training_providers/course_exports_controller.rb
  app/controllers/publish/providers/training_providers/courses_controller.rb
  app/controllers/publish/providers/training_providers_controller.rb
  app/controllers/publish/training_providers/course_exports_controller.rb
  app/controllers/publish/training_providers/courses_controller.rb
  app/controllers/publish/training_providers_controller.rb
  app/views/publish/providers/training_providers/courses/index.html.erb
  app/views/publish/providers/training_providers/index.html.erb
  config/routes/publish.rb
Labels: deploy

#4782 Remove includes course sites on provider courses page
  app/controllers/publish/courses_controller.rb
Labels: deploy

#4789 PART 1 - Add secondary filter to the v2 results page
  app/controllers/find/v2/results_controller.rb
  app/forms/search_courses_form.rb
  app/services/courses_query.rb
  app/views/find/v2/results/index.html.erb
  config/locales/find.yml
  spec/features/find/v2/results/search_results_enabled_spec.rb
  spec/services/courses_query_spec.rb
Labels: deploy
