Repository DFE-Digital/publish-teacher-training, pull requests merged in 2024-06, with the labels that each got.

#4223 [1697] TDA edge cases
  app/controllers/publish/courses/funding_type_controller.rb
  app/controllers/publish/courses/outcome_controller.rb
  app/controllers/publish/courses/study_mode_controller.rb
  app/forms/publish/course_funding_form.rb
  app/models/concerns/publish/course_basic_detail_concern.rb
  app/models/course.rb
  app/services/courses/creation_service.rb
  app/services/publish/courses/assign_tda_attributes_service.rb
  app/views/publish/courses/funding_type/_form_fields.html.erb
  app/views/publish/courses/outcome/new.html.erb
  app/views/publish/courses/study_mode/edit.html.erb
  app/views/publish/courses/study_mode/new.html.erb
  config/settings/review_aks.yml
  spec/features/publish/courses/editing_course_outcome_spec.rb
  spec/features/publish/courses/new_tda_course_spec.rb
  spec/services/courses/creation_service_spec.rb
  spec/services/publish/courses/assign_tda_attributes_service_spec.rb
  spec/support/page_objects/publish/courses/outcome_edit.rb
  spec/support/test_data_cache.rb
Labels: deploy_v2

#4243 [1577, 1575] Remove financial support, move fees to own page
  app/components/find/courses/about_schools_component/view.html.erb
  app/components/find/utility/advice_component/view.rb
  app/components/shared/advice_component/view.html.erb
  app/components/shared/advice_component/view.rb
  app/components/shared/courses/financial_support/bursary_component/view.html.erb
  app/components/shared/courses/financial_support/bursary_component/view.rb
  app/components/shared/courses/financial_support/fees_and_financial_support_component/view.html.erb
  app/components/shared/courses/financial_support/fees_and_financial_support_component/view.rb
  app/components/shared/courses/financial_support/scholarship_and_bursary_component/view.html.erb
  app/components/shared/courses/financial_support/scholarship_and_bursary_component/view.rb
  app/controllers/publish/courses/fees_and_financial_support_controller.rb
  app/controllers/publish/courses/interview_process_controller.rb
  app/forms/publish/course_fees_and_financial_support_form.rb
  app/services/courses/copy.rb
  app/views/find/courses/show.html.erb
  app/views/publish/courses/_description_content.html.erb
  app/views/publish/courses/fees/edit.html.erb
  app/views/publish/courses/fees_and_financial_support/_guidance.html.erb
  app/views/publish/courses/fees_and_financial_support/edit.html.erb
  app/views/publish/courses/preview.html.erb
  app/views/publish/courses/school_placements/_guidance.html.erb
  app/views/shared/courses/financial_support/_loan.html.erb
  app/views/shared/courses/financial_support/_salaried.html.erb
  config/locales/en.yml
  config/routes/publish.rb
  spec/components/shared/courses/financial_support/bursary_component/view_preview.rb
  spec/components/shared/courses/financial_support/bursary_component/view_spec.rb
  spec/components/shared/courses/financial_support/fees_and_financial_support_component/view_preview.rb
  spec/components/shared/courses/financial_support/fees_and_financial_support_component/view_spec.rb
  spec/components/shared/courses/financial_support/scholarship_and_bursary_component/view_preview.rb
  spec/components/shared/courses/financial_support/scholarship_and_bursary_component/view_spec.rb
  spec/features/publish/courses/editing_course_funding_type_spec.rb
  spec/features/publish/editing_fees_and_financial_support_spec.rb
  spec/forms/publish/course_fee_form_spec.rb
  spec/forms/publish/course_fees_and_financial_support_form_spec.rb
  spec/support/page_objects/publish/course_fee_edit.rb
Labels: deploy_v2

#4251 [1579] Remove personal qualities and other requirements from publish
  app/controllers/publish/courses_controller.rb
  app/models/provider.rb
  app/models/recruitment_cycle.rb
  app/views/publish/courses/_description_content.html.erb
  config/routes/publish.rb
  config/settings.yml
  config/settings/development.yml
  config/settings/qa_aks.yml
  config/settings/review_aks.yml
  spec/features/publish/courses/editing_course_requirements_2024_spec.rb
  spec/features/publish/courses/editing_course_requirements_2025_spec.rb
  spec/features/publish/viewing_a_course_2024_spec.rb
  spec/features/publish/viewing_a_course_2025_spec.rb
  spec/models/recruitment_cycle_spec.rb
  spec/support/feature_flags.rb
  swagger/public_v1/api_spec.json
Labels: deploy_v2

#4260 [1720] Replace tabs with secondary navigation component
  app/assets/stylesheets/components/publish/_secondary-navigation.scss
  app/assets/stylesheets/publish_application.scss
  app/components/secondary_navigation_component.html.erb
  app/components/secondary_navigation_component.rb
  app/views/publish/courses/_course_navigation.html.erb
  app/views/publish/courses/_description_content.html.erb
  app/views/publish/courses/details.html.erb
  app/views/publish/courses/show.html.erb
  config/locales/en.yml
  spec/support/page_objects/publish/provider_courses_show.rb
Labels: deploy_v2

#4262 [1638] publish amends to course description tab
  app/decorators/course_decorator.rb
  app/helpers/application_helper.rb
  app/services/courses/copy.rb
  app/views/publish/courses/_description_content.html.erb
  app/views/publish/courses/details.html.erb
  app/views/publish/courses/show.html.erb
  app/views/publish/providers/details.html.erb
  config/locales/en.yml
  spec/components/course_preview/missing_information_component_spec.rb
  spec/components/find/courses/about_schools_component/view_preview.rb
  spec/components/find/courses/about_schools_component/view_spec.rb
  spec/features/find/search/viewing_a_course_spec.rb
  spec/features/publish/courses/editing_course_school_placements_copy_content_spec.rb
  spec/features/publish/courses/editing_course_school_placements_spec.rb
  spec/features/publish/courses/new_tda_course_spec.rb
  spec/features/publish/courses/publishing_a_course_spec.rb
  spec/features/publish/viewing_a_course_preview_spec.rb
  spec/helpers/application_helper_spec.rb
  spec/models/course/publishable_spec.rb
Labels: deploy_v2

#4266 [1695] publish: move and amend formatting panel also add to pages its missing from
  app/components/accredited_provider.html.erb
  app/components/accredited_provider.rb
  app/components/degree_row_content.html.erb
  app/components/degree_row_content.rb
  app/components/gcse_row_content.html.erb
  app/components/gcse_row_content.rb
  app/helpers/publish_helper.rb
  app/views/publish/courses/_additional_gcse_requirements_hint.html.erb
  app/views/publish/courses/_description_content.html.erb
  app/views/publish/courses/_gcse_requirements.html.erb
  app/views/publish/courses/_markdown_formatting.html.erb
  app/views/publish/courses/_related_sidebar.html.erb
  app/views/publish/courses/about_this_course/edit.html.erb
  app/views/publish/courses/degrees/_additional_degree_subject_requirements.html.erb
  app/views/publish/courses/fees_and_financial_support/edit.html.erb
  app/views/publish/courses/interview_process/edit.html.erb
  app/views/publish/courses/school_placements/edit.html.erb
  app/views/publish/providers/about.html.erb
  app/views/publish/providers/accredited_providers/_hint.html.erb
  app/views/publish/providers/accredited_providers/checks/show.html.erb
  app/views/publish/providers/accredited_providers/edit.html.erb
  app/views/publish/providers/accredited_providers/new.html.erb
  app/views/publish/providers/details.html.erb
  config/locales/en.yml
  spec/features/publish/courses/editing_course_about_this_course_spec.rb
  spec/features/publish/courses/editing_course_interview_process_spec.rb
  spec/features/publish/courses/editing_course_school_placements_spec.rb
  spec/features/publish/courses/editing_degree_requirements_spec.rb
  spec/features/publish/courses/gcse_equivalency_spec.rb
  spec/features/publish/editing_fees_and_financial_support_spec.rb
  spec/features/publish/viewing_a_course_preview_spec.rb
Labels: deploy_v2

#4269 [1750] Reset previously defaulted enrichment attributes back to nil (TDA courses)
  app/controllers/publish/courses/outcome_controller.rb
  spec/features/publish/courses/editing_course_outcome_spec.rb
Labels: deploy_v2

#4275 [1734] bug copy content drop down disappears after validation, broken links in copy content warning
  app/components/providers/copy_course_content_warning_component.html.erb
  app/components/providers/copy_course_content_warning_component.rb
  app/controllers/publish/courses/about_this_course_controller.rb
  app/controllers/publish/courses/degrees/subject_requirements_controller.rb
  app/controllers/publish/courses/gcse_requirements_controller.rb
  app/controllers/publish/courses/interview_process_controller.rb
  app/controllers/publish/courses/school_placements_controller.rb
  app/services/courses/copy.rb
  app/views/publish/courses/about_this_course/_copy_about_course_content_warning.html.erb
  app/views/publish/courses/about_this_course/edit.html.erb
  app/views/publish/courses/degrees/subject_requirements/edit.html.erb
  app/views/publish/courses/fees/edit.html.erb
  app/views/publish/courses/gcse_requirements/edit.html.erb
  app/views/publish/courses/interview_process/_copy_interview_process_content_warning.html.erb
  app/views/publish/courses/interview_process/edit.html.erb
  app/views/publish/courses/school_placements/_copy_school_placements_content_warning.html.erb
  app/views/publish/courses/school_placements/edit.html.erb
  config/locales/en.yml
  spec/components/providers/copy_course_content_warning_component_preview.rb
  spec/components/providers/copy_course_content_warning_component_spec.rb
  spec/features/publish/courses/editing_course_about_this_course_copy_content_spec.rb
  spec/features/publish/courses/editing_course_gcse_requirements_copy_content_spec.rb
  spec/features/publish/courses/editing_course_interview_process_copy_content_spec.rb
  spec/features/publish/courses/editing_course_school_placements_copy_content_spec.rb
  spec/features/publish/courses/editing_course_subject_requirements_copy_content_spec.rb
Labels: deploy_v2

#4277 [1719] Add Blazer to Publish
  Gemfile
  Gemfile.lock
  app/lib/blazer_admin_constraint.rb
  app/models/user.rb
  config/analytics_blocklist.yml
  config/blazer.yml
  config/environments/development.rb
  config/environments/production.rb
  config/environments/test.rb
  config/initializers/blazer.rb
  config/routes/publish.rb
  config/rubocop/rails.yml
  db/migrate/20240605133343_install_blazer.rb
  db/migrate/20240612194755_add_blazer_access_to_user.rb
  db/schema.rb
  docs/database-diagram.jpg
  spec/features/publish/blazer_spec.rb
Labels: deploy_v2

#4283 Hide Financial support in 2025
  app/views/publish/courses/_description_content.html.erb
Labels: deploy_v2

#4280 Hiding Other Requirements doesn't prevent course from being published in 2025
  app/controllers/publish/courses_controller.rb
  app/helpers/publish_helper.rb
  app/models/provider.rb
  app/views/publish/courses/_description_content.html.erb
  config/settings.yml
  config/settings/development.yml
  config/settings/qa_aks.yml
  config/settings/review_aks.yml
  spec/features/publish/courses/editing_course_requirements_2024_spec.rb
  spec/features/publish/courses/editing_course_requirements_2025_spec.rb
  spec/features/publish/courses/publishing_a_course_2025_spec.rb
  spec/features/publish/viewing_a_course_2024_spec.rb
  spec/features/publish/viewing_a_course_2025_spec.rb
Labels: deploy_v2

#4299 Find Domain change - We will have to sustain 2 domains until the domain redirect is applied
  app/lib/find_constraint.rb
  config/environments/production.rb
  config/initializers/cors.rb
  config/settings.yml
  config/settings/production.yml
  config/settings/production_aks.yml
  config/settings/qa.yml
  config/settings/qa_aks.yml
  config/settings/review.yml
  config/settings/review_aks.yml
  config/settings/rollover.yml
  config/settings/sandbox.yml
  config/settings/sandbox_aks.yml
  config/settings/staging.yml
  config/settings/staging_aks.yml
  spec/lib/find_constraint_spec.rb
Labels: do not merge, deploy_v2

#4294 TDA A level requirements. - part 2 (second page in the wizard)
  app/views/publish/courses/a_level_requirements/are_any_a_levels_required_for_this_course/new.html.erb
  app/views/publish/courses/a_level_requirements/what_a_level_is_required/new.html.erb
  app/wizards/a_level_steps/what_a_level_is_required.rb
  config/initializers/a_and_as_level_subjects.rb
  config/locales/en.yml
  spec/features/publish/courses/editing_a_levels_tda_course_spec.rb
  spec/wizards/a_level_steps/what_a_level_is_required_spec.rb
Labels: deploy_v2

#4301 Change overnight backup to run at 0100 UTC
  .github/workflows/database-restore.yml
Labels: Devops

#4303 Add update image tag for failback maintenance page
  maintenance_page/scripts/failback.sh
Labels: Devops

#4305 [1782] Update recruitment cycle/academic cycle period
  app/helpers/recruitment_cycle_helper.rb
  app/views/pages/roll_over_courses_to_a_new_recruitment_cycle.html.erb
Labels: deploy_v2

#4304 Add script hash to rails CSP configuration
  app/views/layouts/_add_js_enabled_class_to_body.html.erb
  config/initializers/content_security_policy.rb
Labels: deploy_v2

#4306 A levels part 3 - add list of required a levels page
  app/components/a_level_row_component.html.erb
  app/components/a_level_subject_requirement_row_component.html.erb
  app/components/a_level_subject_requirement_row_component.rb
  app/controllers/publish/courses/a_level_requirements/a_level_requirements_controller.rb
  app/controllers/publish/courses/a_level_requirements/add_a_level_to_a_list_controller.rb
  app/controllers/publish/courses/a_level_requirements/are_any_a_levels_required_for_this_course_controller.rb
  app/controllers/publish/courses/a_level_requirements/what_a_level_is_required_controller.rb
  app/decorators/course_decorator.rb
  app/views/publish/courses/a_level_requirements/add_a_level_to_a_list/new.html.erb
  app/views/publish/courses/a_level_requirements/are_any_a_levels_required_for_this_course/new.html.erb
  app/views/publish/courses/a_level_requirements/what_a_level_is_required/new.html.erb
  app/wizards/a_level_steps/add_a_level_to_a_list.rb
  app/wizards/a_level_steps/are_any_a_levels_required_for_this_course.rb
  app/wizards/a_level_steps/what_a_level_is_required.rb
  app/wizards/a_levels_wizard.rb
  app/wizards/a_levels_wizard_store.rb
  app/wizards/are_any_a_levels_required_store.rb
  app/wizards/what_a_level_is_required_store.rb
  config/analytics.yml
  config/locales/en.yml
  config/routes/publish.rb
  db/migrate/20240625124649_add_a_level_subjects_to_courses.rb
  db/schema.rb
  docs/database-diagram.jpg
  spec/components/a_level_subject_requirement_row_component_spec.rb
  spec/controllers/publish/courses/a_level_requirements/add_a_level_to_a_list_controller_spec.rb
  spec/decorators/course_decorator_spec.rb
  spec/factories/courses.rb
  spec/features/publish/courses/editing_a_levels_tda_course_spec.rb
  spec/wizards/a_level_steps/add_a_level_to_a_list_spec.rb
  spec/wizards/a_level_steps/are_any_a_levels_required_for_this_course_spec.rb
  spec/wizards/a_level_steps/what_a_level_is_required_spec.rb
  spec/wizards/a_levels_wizard_store_spec.rb
  spec/wizards/are_any_a_levels_required_store_spec.rb
  spec/wizards/what_a_level_is_required_store_spec.rb
Labels: deploy_v2

#4312 [1873] Render 404 if course should not be on Find
  app/controllers/find/courses_controller.rb
  spec/features/find/viewing_courses_in_various_states_spec.rb
Labels: deploy_v2

#4314 A levels - Add a levels equivalency tests
  app/controllers/publish/courses/a_level_requirements/a_level_equivalencies_controller.rb
  app/controllers/publish/courses/a_level_requirements/consider_pending_a_level_controller.rb
  app/views/publish/courses/a_level_requirements/a_level_equivalencies/new.html.erb
  app/wizards/a_level_equivalencies_store.rb
  app/wizards/a_level_steps/a_level_equivalencies.rb
  app/wizards/a_levels_wizard.rb
  app/wizards/a_levels_wizard_store.rb
  app/wizards/are_any_a_levels_required_store.rb
  config/analytics.yml
  config/locales/en.yml
  config/routes/publish.rb
  config/rubocop/rails.yml
  db/migrate/20240626152030_add_accept_a_level_equivalency_to_course.rb
  db/migrate/20240626152102_add_additional_a_level_equivalencies_to_course.rb
  db/schema.rb
  docs/database-diagram.jpg
  spec/controllers/publish/courses/a_level_requirements/a_level_equivalencies_controller_spec.rb
  spec/factories/courses.rb
  spec/features/publish/courses/editing_a_levels_tda_course_spec.rb
  spec/wizards/a_level_equivalencies_store_spec.rb
  spec/wizards/a_level_steps/a_level_equivalencies_spec.rb
  spec/wizards/a_levels_wizard_store_spec.rb
  spec/wizards/are_any_a_levels_required_store_spec.rb
Labels: deploy_v2

#4319 A levels add max character length validation to minimum grade required
  app/validators/chars_count_validator.rb
  app/wizards/a_level_steps/what_a_level_is_required.rb
  config/locales/en.yml
  spec/wizards/a_level_steps/what_a_level_is_required_spec.rb
Labels: deploy_v2

#4318 Display A levels on publish summary page
  app/components/a_level_row_component.html.erb
  app/components/a_level_row_component.rb
  config/locales/en.yml
  spec/components/a_level_row_component_spec.rb
  spec/features/publish/courses/editing_a_levels_tda_course_spec.rb
Labels: deploy_v2
