Repository DFE-Digital/publish-teacher-training, pull requests merged in 2024-04, with the labels that each got.

#4123 Hide relocation information if policy has been rolled back
  .gitignore
  app/components/find/courses/international_students_component/view.html.erb
  app/components/find/courses/international_students_component/view.rb
  spec/components/find/courses/international_students_component/view_spec.rb
Labels: deploy_v2

#4071 Decrease the find radius search range to 50 miles
  app/view_objects/find/results_view.rb
  spec/features/find/search/location_options_spec.rb
Labels: deploy_v2

#4130 Update open-api-rswag to v0.2.0
  Gemfile
  Gemfile.lock
Labels: deploy_v2

#4129 1487 reflect the ske policy changes in our services
  app/components/find/courses/entry_requirements_component/view.html.erb
  app/components/find/courses/entry_requirements_component/view.rb
  db/seeds.rb
  guides/setup-development.md
  spec/components/find/courses/entry_requirements_component/view_spec.rb
Labels: do not merge, deploy_v2

#4158 Add TDA feature flag
  config/settings.yml
  config/settings/development.yml
  config/settings/qa_aks.yml
  config/settings/review_aks.yml
Labels: deploy_v2

#4151 Replace 'PGCE with QTS' with 'QTS with PGCE'
  app/components/find/courses/qualifications_summary_component/view.html.erb
  app/decorators/course_decorator.rb
  app/models/concerns/with_qualifications.rb
  app/views/find/result_filters/_qualifications_filter.html.erb
  config/locales/en.yml
  config/locales/find.yml
  spec/components/find/courses/qualifications_summary_component/view_spec.rb
  spec/decorators/course_decorator_spec.rb
  spec/features/find/result_page_filters/qualifications_spec.rb
  spec/features/find/search/course_results_spec.rb
  spec/features/find/search/viewing_a_course_spec.rb
  spec/features/publish/courses/editing_course_outcome_spec.rb
  spec/features/publish/viewing_a_course_details_spec.rb
  spec/features/publish/viewing_a_course_preview_spec.rb
  spec/services/course_attribute_formatter_service_spec.rb
Labels: deploy_v2

#4163 [1530] Update content on international qualifications section (Find)
  app/components/find/courses/international_students_component/view.html.erb
  config/locales/find.yml
  spec/components/find/courses/international_students_component/view_spec.rb
Labels: deploy_v2

#4168 [1654] Add infra team StatusCake contact group
  terraform/aks/statuscake.tf
  terraform/aks/variables.tf
  terraform/aks/workspace_variables/production_aks.tfvars.json
  terraform/aks/workspace_variables/qa_aks.tfvars.json
  terraform/aks/workspace_variables/sandbox_aks.tfvars.json
  terraform/aks/workspace_variables/staging_aks.tfvars.json
Labels: Devops

#4159 Makefile environment names to be equal to Apply
  Makefile
Labels: deploy_v2

#4156 Upgrade rails to v7.1
  Gemfile
  Gemfile.lock
  app/assets/config/manifest.js
  app/controllers/api/system/application_controller.rb
  app/models/course.rb
  app/models/provider.rb
  app/views/layouts/application.html.erb
  app/views/layouts/component_preview.html.erb
  bin/setup
  config/application.rb
  config/boot.rb
  config/environment.rb
  config/environments/development.rb
  config/environments/production.rb
  config/environments/test.rb
  config/initializers/assets.rb
  config/initializers/content_security_policy.rb
  config/initializers/new_framework_defaults_7_0.rb
  config/initializers/permissions_policy.rb
  config/initializers/semantic_logger.rb
  config/rubocop/style.yml
  docker-compose.yml
  spec/controllers/api/system/application_controller_spec.rb
  spec/spec_helper_smoke.rb
  spec/support/feature_helpers/page_objects/auth.rb
  spec/view_objects/find/results_view_spec.rb
Labels: deploy_v2
