Repository DFE-Digital/publish-teacher-training, pull requests merged in 2024-11, with the labels that each got.

#4643 Add feature flag for the API summary content change
  config/settings.yml
Labels: deploy_v2

#4655 Add QA acronym to inflections
  config/initializers/inflections.rb
Labels: deploy_v2

#4660 Add "Component" suffix to AccreditedProvider component
  app/components/accredited_provider_component.html.erb
  app/components/accredited_provider_component.rb
  app/views/publish/providers/accredited_providers/index.html.erb
  app/views/support/providers/accredited_providers/index.html.erb
  spec/components/accredited_provider_component_spec.rb
  spec/components/accredited_provider_preview.rb
Labels: deploy_v2

#4673 Increase max uri length
  config/initializers/webrick.rb
Labels: deploy_v2

#4678 Add new statuscake contact group
  terraform/aks/workspace_variables/production_aks.tfvars.json
  terraform/aks/workspace_variables/qa_aks.tfvars.json
  terraform/aks/workspace_variables/sandbox_aks.tfvars.json
  terraform/aks/workspace_variables/staging_aks.tfvars.json
Labels: Devops

#4686 Update filter default: uncheck Study type & Qualifications checkboxes
  app/views/find/result_filters/_qualifications_filter.html.erb
  app/views/find/result_filters/_study_type_filter.html.erb
  spec/features/find/result_page_filters/applications_open_spec.rb
  spec/features/find/result_page_filters/degree_required_spec.rb
  spec/features/find/result_page_filters/qualifications_spec.rb
  spec/features/find/result_page_filters/salary_spec.rb
  spec/features/find/result_page_filters/send_spec.rb
  spec/features/find/result_page_filters/study_type_spec.rb
  spec/features/find/result_page_filters/visa_spec.rb
  spec/support/filters_feature_specs_helper.rb
Labels: deploy_v2

#4695 Remove www2 route redirection
  config/routes.rb
Labels: deploy

#4688 Add accredited provider number / id to Support Provider list
  app/views/support/providers/_list.html.erb
Labels: deploy

#4699 Remove local SSL configurations
  config/puma.rb
  config/settings.yml
  config/settings/development.yml
Labels: deploy

#4707 Don't log DfE analytics events
  config/environments/production.rb
Labels: deploy

#4719 Use azure storage account for all backups
  .github/actions/restore/action.yml
  .github/workflows/database-restore.yml
  guides/setup-development.md
Labels: Devops

#4722 Update review app seed to use azure backup file
  .github/actions/deploy/action.yml
  .github/workflows/build-and-deploy.yml
  .github/workflows/deploy-review-app.yml
Labels: Devops, deploy
