Repository DFE-Digital/publish-teacher-training, pull requests merged in 2024-08, with the labels that each got.

#4413 Git and provider website redirects
  app/components/find/courses/contact_details_component/view.html.erb
  app/controllers/concerns/get_into_teaching_redirect.rb
  app/controllers/concerns/provider_website_redirect.rb
  app/controllers/find/courses_controller.rb
  app/views/find/courses/_advice.html.erb
  config/locales/en.yml
  config/locales/find.yml
  config/routes/find.rb
  spec/components/find/courses/contact_details_component/view_preview.rb
  spec/features/find/search/viewing_a_course_spec.rb
Labels: deploy_v2

#4417 Move field from pii to hidden pii
  config/analytics_hidden_pii.yml
  config/analytics_pii.yml
Labels: deploy_v2

#4418 Fix the course summary for TDA
  app/models/course.rb
  spec/models/course_spec.rb
Labels: deploy_v2

#4415 [2114] Add `course_type` column
  config/analytics.yml
  db/migrate/20240731175623_add_course_type_to_courses.rb
  db/schema.rb
  docs/database-diagram.jpg
Labels: deploy_v2

#4420 [2114] Add `course_type` enum
  app/models/course.rb
  spec/models/course_spec.rb
Labels: deploy_v2

#4421 [2116] Add `funding` column to `course`
  config/analytics.yml
  db/migrate/20240801170318_add_funding_type_to_courses.rb
  db/schema.rb
  docs/database-diagram.jpg
Labels: deploy_v2

#4430 [1957] Upgrade staging database
  terraform/aks/workspace_variables/staging_aks.tfvars.json
Labels: Devops

#4422 [2116] Add `funding` enum
  app/models/course.rb
  spec/models/course_spec.rb
Labels: deploy_v2

#4433 [2112] Update guidance page content
  app/views/pages/add_schools_and_study_sites.html.erb
Labels: deploy_v2

#4434 [2123] Update `course_type` to `undergraduate` for Teacher Degree Apprenticeship courses
  app/controllers/publish/courses/outcome_controller.rb
  app/services/publish/courses/assign_tda_attributes_service.rb
  spec/features/publish/courses/editing_course_outcome_spec.rb
  spec/services/publish/courses/assign_tda_attributes_service_spec.rb
Labels: deploy_v2

#4436 [2124] Add `funding` feature flag
  app/models/course.rb
  config/settings.yml
Labels: deploy_v2

#4443 [1884] Add 2026 cycle dates to codebase
  app/services/find/cycle_timetable.rb
Labels: deploy_v2

#4428 TDA find - Add undergraduate courses to find (for 2025 cycle)
  app/controllers/concerns/filter_parameters.rb
  app/controllers/find/application_controller.rb
  app/controllers/find/search/no_degree_and_requires_visa_sponsorship_controller.rb
  app/controllers/find/search/subjects_controller.rb
  app/controllers/find/search/university_degree_status_controller.rb
  app/controllers/find/search/visa_status_controller.rb
  app/forms/find/university_degree_status_form.rb
  app/models/course.rb
  app/services/course_search_service.rb
  app/services/find/course_type_answer_determiner.rb
  app/view_objects/find/result_filters/filters_view.rb
  app/views/find/result_filters/_all.html.erb
  app/views/find/result_filters/_hidden_fields.html.erb
  app/views/find/search/no_degree_and_requires_visa_sponsorship/new.html.erb
  app/views/find/search/university_degree_status/new.html.erb
  app/views/find/search/visa_status/new.html.erb
  config/locales/en.yml
  config/locales/find.yml
  config/routes/find.rb
  spec/factories/courses.rb
  spec/features/find/search/undergraduate/course_results_spec.rb
  spec/forms/find/university_degree_status_form_spec.rb
  spec/services/course_search_service_spec.rb
  spec/services/find/course_type_answer_determiner_spec.rb
Labels: deploy_v2

#4459 [2208] Activate the `db_backed_funding` feature flag in all envs
  config/settings.yml
Labels: deploy_v2

#4458 Add specific support and advice content for TDA courses
  app/views/find/courses/_advice.html.erb
  config/locales/find.yml
  spec/factories/courses.rb
  spec/features/find/search/undergraduate/viewing_a_course_spec.rb
Labels: deploy_v2

#4462 Update terraform providers
  terraform/aks/.terraform.lock.hcl
  terraform/aks/providers.tf
  terraform/custom_domains/environment_domains/.terraform.lock.hcl
  terraform/custom_domains/environment_domains/terraform.tf
  terraform/custom_domains/infrastructure/.terraform.lock.hcl
  terraform/custom_domains/infrastructure/terraform.tf
Labels: Devops, deploy_v2

#4465 Update Teacher Training API to return `selectable_school`
  app/serializers/api/public/v1/serializable_provider.rb
  bin/build-docs
  docs/source/release-notes.html.md.erb
  guides/api.md
  spec/controllers/api/public/v1/providers_controller_spec.rb
  spec/factories/providers.rb
  spec/serializers/api/public/v1/serializable_provider_spec.rb
  swagger/public_v1/api_spec.json
  swagger/public_v1/component_schemas/CourseAttributes.yml
  swagger/public_v1/component_schemas/ProviderAttributes.yml
Labels: deploy_v2

#4468 Make sure undergraduate courses and non duplicates appear on the API
  app/controllers/api/public/v1/courses_controller.rb
  app/controllers/api/public/v1/providers/courses_controller.rb
  app/services/api_course_search_service.rb
  app/services/course_search_service.rb
  spec/controllers/api/public/v1/courses_controller_spec.rb
  spec/controllers/api/public/v1/providers/courses_controller_spec.rb
  spec/services/api_course_search_service_spec.rb
Labels: deploy_v2

#4471 [2200] Tighten up routes
  config/routes/find.rb
Labels: deploy_v2
