Repository DFE-Digital/publish-teacher-training, pull requests merged in 2025-02, with the labels that each got.

#4881 Skip verify_authorized for Publish::ErrorsController
  app/controllers/publish/errors_controller.rb
Labels: deploy

#4878 Add shortcuts to Publish from Support
  app/views/support/courses/index.html.erb
  app/views/support/providers/_navigation.html.erb
  app/views/support/providers/accredited_partnerships/index.html.erb
  app/views/support/providers/accredited_providers/index.html.erb
  app/views/support/providers/show.html.erb
  app/views/support/providers/users/index.html.erb
  app/views/support/schools/index.html.erb
Labels: deploy

#4887 [610] Add visa sponsorship application deadline attribute to course object
  app/serializers/api/public/v1/serializable_course.rb
  spec/controllers/api/public/v1/courses_controller_spec.rb
  spec/serializers/api/public/v1/serializable_course_spec.rb
  swagger/public_v1/api_spec.json
  swagger/public_v1/component_schemas/CourseAttributes.yml
Labels: deploy

#4891 Add storage account for sanitised backups
  terraform/aks/.terraform.lock.hcl
  terraform/aks/storage.tf
  terraform/aks/variables.tf
  terraform/aks/workspace_variables/production.tfvars.json
Labels: Devops, deploy

#4858 Add Data migration to create ProviderPartnerships from enrichments
  db/data/20250124165440_migrate_provider_partnerships_from_enrichments.rb
Labels: deploy

#4912 Bug fix: can change accredited provider description before save
  app/controllers/publish/providers/accredited_partnerships_controller.rb
  spec/features/publish/accredited_partnership_spec.rb
Labels: deploy

#4926 Fix issue where you search, click on a course and return to search
  app/views/find/courses/show.html.erb
  spec/system/find/v2/results/view_course_spec.rb
Labels: deploy

#4879 Enable OIDC for GitHub actions
  .github/actions/deploy/action.yml
  .github/actions/restore/action.yml
  .github/workflows/build-and-deploy.yml
  .github/workflows/build-nocache.yml
  .github/workflows/database-restore.yml
  .github/workflows/delete-review-app.yml
  .github/workflows/deploy-review-app.yml
  .github/workflows/deploy.yml
  .github/workflows/disable-maintenance.yml
  .github/workflows/enable-maintenance.yml
  Makefile
  guides/aks-cheatsheet.md
  terraform/aks/providers.tf
Labels: Devops, deploy

#4931 Enable /v2/results to just /results if feature is active
  app/controllers/find/v2/primary_subjects_controller.rb
  app/controllers/find/v2/secondary_subjects_controller.rb
  app/lib/find_v1_results_constraint.rb
  app/lib/find_v2_results_constraint.rb
  app/views/find/search/locations/_form.html.erb
  app/views/find/v2/primary_subjects/index.erb
  app/views/find/v2/results/index.html.erb
  app/views/find/v2/secondary_subjects/index.erb
  config/routes/find.rb
  spec/system/find/v2/results/search_results_disabled_spec.rb
  spec/system/find/v2/results/search_results_enabled_spec.rb
  spec/system/find/v2/results/search_results_no_results_spec.rb
  spec/system/find/v2/results/search_results_ordering_spec.rb
  spec/system/find/v2/results/search_results_subject_and_location_spec.rb
  spec/system/find/v2/results/search_results_tracking_spec.rb
  spec/system/find/v2/results/view_course_spec.rb
Labels: deploy

#4868 Workflows for Disaster Recovery
  .github/workflows/postgres-ptr.yml
  .github/workflows/postgres-restore.yml
Labels: Devops

#4938 The scrollable filter items needs to be partially hidden
  app/assets/stylesheets/find/components/_filter-search.scss
  app/views/find/v2/results/index.html.erb
Labels: deploy

#4930 DataMigration correct visa sponsorship data
  db/data/20250218095818_correct_course_visa_data.rb
Labels: deploy

#4942 Set SRID 4326 for spatial queries in course location calculations
  app/services/courses/nearest_school_query.rb
  app/services/courses/query.rb
  app/services/courses/school_distances_query.rb
Labels: deploy

#4934 Enable manual postgres backup
  .github/workflows/database-restore.yml
  Makefile
  guides/setup-development.md
Labels: Devops, deploy

#4946 Add course start date filter
  app/controllers/find/v2/results_controller.rb
  app/forms/courses/search_form.rb
  app/services/courses/query.rb
  app/views/find/v2/results/index.html.erb
  config/locales/find.yml
  spec/services/courses/query_spec.rb
  spec/system/find/v2/results/search_results_enabled_spec.rb
Labels: deploy

#4945 Enable pre filtering feature flag through /feature-flags
  app/lib/feature_flags.rb
  app/lib/find_v1_results_constraint.rb
  app/lib/find_v2_results_constraint.rb
  app/views/find/courses/show.html.erb
  app/views/find/search/locations/_form.html.erb
  config/settings.yml
  config/settings/qa.yml
  config/settings/review.yml
  spec/system/find/v2/quick_links/primary_subjects_spec.rb
  spec/system/find/v2/quick_links/secondary_subjects_spec.rb
  spec/system/find/v2/results/search_results_enabled_spec.rb
  spec/system/find/v2/results/search_results_no_results_spec.rb
  spec/system/find/v2/results/search_results_ordering_spec.rb
  spec/system/find/v2/results/search_results_subject_and_location_spec.rb
  spec/system/find/v2/results/search_results_tracking_spec.rb
  spec/system/find/v2/results/view_course_spec.rb
Labels: deploy

#4959 Add all urls to review app PR deploy comment
  .github/workflows/build-and-deploy.yml
Labels: Devops, deploy

#4955 Add Engineers teach physics filter
  app/controllers/find/v2/results_controller.rb
  app/forms/courses/search_form.rb
  app/services/courses/query.rb
  app/views/find/v2/results/filters/_all.html.erb
  app/views/find/v2/results/index.html.erb
  config/locales/find.yml
  spec/forms/courses/search_form_spec.rb
  spec/services/courses/query_spec.rb
  spec/system/find/v2/results/search_results_enabled_spec.rb
Labels: deploy

#4961 Round up school placement distances in results summary cards
  app/components/courses/summary_card_component.rb
  spec/components/courses/summary_card_component_spec.rb
Labels: deploy

#4969 Clear the dfe-autocomplete select value on input
  app/javascript/find/controllers/provider_autocomplete_controller.js
Labels: deploy

#4962 Don't show filters on mobile on page load
  app/assets/stylesheets/find/components/_filter-layout.scss
  app/assets/stylesheets/find/components/_filter.scss
  app/javascript/find/application.js
  app/javascript/find/controllers/visibility_controller.js
  app/javascript/find/filter-toggle-button.js
  app/views/find/result_filters/_all.html.erb
  app/views/find/results/index.html.erb
  app/views/find/v2/results/index.html.erb
Labels: deploy

#4974 Show filter button when there are no results
  app/views/find/v2/results/index.html.erb
Labels: deploy

#4972 Set search radius of 50 on large geocoded areas
  app/forms/courses/search_form.rb
  spec/forms/courses/search_form_spec.rb
Labels: deploy
